### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.WSHttpBindingCollectionElement
  commentId: T:CoreWCF.Configuration.WSHttpBindingCollectionElement
  id: WSHttpBindingCollectionElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.WSHttpBindingCollectionElement.#ctor
  langs:
  - csharp
  - vb
  name: WSHttpBindingCollectionElement
  nameWithType: WSHttpBindingCollectionElement
  fullName: CoreWCF.Configuration.WSHttpBindingCollectionElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a configuration element that contains sub-elements that specify settings for using the wsHttpBinding binding.
  remarks: To be added.
  syntax:
    content: 'public class WSHttpBindingCollectionElement : StandardBindingCollectionElement<WSHttpBinding, WSHttpBindingElement>'
    content.vb: >-
      Public Class WSHttpBindingCollectionElement
          Inherits StandardBindingCollectionElement(Of WSHttpBinding, WSHttpBindingElement)
  inheritance:
  - System.Object
  - CoreWCF.Configuration.BindingCollectionElement
  - CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.WSHttpBinding,CoreWCF.Configuration.WSHttpBindingElement}
  inheritedMembers:
  - CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.WSHttpBinding,CoreWCF.Configuration.WSHttpBindingElement}.Bindings
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.WSHttpBindingCollectionElement.#ctor
  commentId: M:CoreWCF.Configuration.WSHttpBindingCollectionElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.WSHttpBindingCollectionElement
  langs:
  - csharp
  - vb
  name: WSHttpBindingCollectionElement()
  nameWithType: WSHttpBindingCollectionElement.WSHttpBindingCollectionElement()
  fullName: CoreWCF.Configuration.WSHttpBindingCollectionElement.WSHttpBindingCollectionElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public WSHttpBindingCollectionElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.WSHttpBindingCollectionElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.BindingCollectionElement
  commentId: T:CoreWCF.Configuration.BindingCollectionElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement
  fullName: CoreWCF.Configuration.BindingCollectionElement
- uid: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.WSHttpBinding,CoreWCF.Configuration.WSHttpBindingElement}
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.WSHttpBinding,CoreWCF.Configuration.WSHttpBindingElement}
  parent: CoreWCF.Configuration
  definition: CoreWCF.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<WSHttpBinding, WSHttpBindingElement>
  nameWithType: StandardBindingCollectionElement<WSHttpBinding, WSHttpBindingElement>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<CoreWCF.WSHttpBinding, CoreWCF.Configuration.WSHttpBindingElement>
  nameWithType.vb: StandardBindingCollectionElement(Of WSHttpBinding, WSHttpBindingElement)
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of CoreWCF.WSHttpBinding, CoreWCF.Configuration.WSHttpBindingElement)
  name.vb: StandardBindingCollectionElement(Of WSHttpBinding, WSHttpBindingElement)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.WSHttpBinding
    name: WSHttpBinding
    nameWithType: WSHttpBinding
    fullName: CoreWCF.WSHttpBinding
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: CoreWCF.Configuration.WSHttpBindingElement
    name: WSHttpBindingElement
    nameWithType: WSHttpBindingElement
    fullName: CoreWCF.Configuration.WSHttpBindingElement
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.WSHttpBinding
    name: WSHttpBinding
    nameWithType: WSHttpBinding
    fullName: CoreWCF.WSHttpBinding
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: CoreWCF.Configuration.WSHttpBindingElement
    name: WSHttpBindingElement
    nameWithType: WSHttpBindingElement
    fullName: CoreWCF.Configuration.WSHttpBindingElement
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.WSHttpBinding,CoreWCF.Configuration.WSHttpBindingElement}.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.WSHttpBinding,CoreWCF.Configuration.WSHttpBindingElement}.Bindings
  parent: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.WSHttpBinding,CoreWCF.Configuration.WSHttpBindingElement}
  definition: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  name: Bindings
  nameWithType: StandardBindingCollectionElement<WSHttpBinding, WSHttpBindingElement>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<CoreWCF.WSHttpBinding, CoreWCF.Configuration.WSHttpBindingElement>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of WSHttpBinding, WSHttpBindingElement).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of CoreWCF.WSHttpBinding, CoreWCF.Configuration.WSHttpBindingElement).Bindings
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement`2
  isExternal: true
  name: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  name.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TStandardBinding
    nameWithType: TStandardBinding
    fullName: TStandardBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TStandardBinding
    nameWithType: TStandardBinding
    fullName: TStandardBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  isExternal: true
  name: Bindings
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
- uid: CoreWCF.Configuration.WSHttpBindingCollectionElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.WSHttpBindingCollectionElement.#ctor
  isExternal: true
  name: WSHttpBindingCollectionElement
  nameWithType: WSHttpBindingCollectionElement.WSHttpBindingCollectionElement
  fullName: CoreWCF.Configuration.WSHttpBindingCollectionElement.WSHttpBindingCollectionElement
