### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.IStandardBindingElement
  commentId: T:CoreWCF.Configuration.IStandardBindingElement
  id: IStandardBindingElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.IStandardBindingElement.CreateBinding
  - CoreWCF.Configuration.IStandardBindingElement.Name
  langs:
  - csharp
  - vb
  name: IStandardBindingElement
  nameWithType: IStandardBindingElement
  fullName: CoreWCF.Configuration.IStandardBindingElement
  type: Interface
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public interface IStandardBindingElement
    content.vb: Public Interface IStandardBindingElement
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: CoreWCF.Configuration.IStandardBindingElement.CreateBinding
  commentId: M:CoreWCF.Configuration.IStandardBindingElement.CreateBinding
  id: CreateBinding
  parent: CoreWCF.Configuration.IStandardBindingElement
  langs:
  - csharp
  - vb
  name: CreateBinding()
  nameWithType: IStandardBindingElement.CreateBinding()
  fullName: CoreWCF.Configuration.IStandardBindingElement.CreateBinding()
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: Binding CreateBinding()
    return:
      type: CoreWCF.Channels.Binding
    content.vb: Function CreateBinding As Binding
  overload: CoreWCF.Configuration.IStandardBindingElement.CreateBinding*
- uid: CoreWCF.Configuration.IStandardBindingElement.Name
  commentId: P:CoreWCF.Configuration.IStandardBindingElement.Name
  id: Name
  parent: CoreWCF.Configuration.IStandardBindingElement
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: IStandardBindingElement.Name
  fullName: CoreWCF.Configuration.IStandardBindingElement.Name
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property Name As String
  overload: CoreWCF.Configuration.IStandardBindingElement.Name*
  modifiers.csharp:
  - get
  - set
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: CoreWCF.Configuration.IStandardBindingElement.CreateBinding*
  commentId: Overload:CoreWCF.Configuration.IStandardBindingElement.CreateBinding
  isExternal: true
  name: CreateBinding
  nameWithType: IStandardBindingElement.CreateBinding
  fullName: CoreWCF.Configuration.IStandardBindingElement.CreateBinding
- uid: CoreWCF.Channels.Binding
  commentId: T:CoreWCF.Channels.Binding
  parent: CoreWCF.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: CoreWCF.Channels.Binding
- uid: CoreWCF.Channels
  commentId: N:CoreWCF.Channels
  isExternal: true
  name: CoreWCF.Channels
  nameWithType: CoreWCF.Channels
  fullName: CoreWCF.Channels
- uid: CoreWCF.Configuration.IStandardBindingElement.Name*
  commentId: Overload:CoreWCF.Configuration.IStandardBindingElement.Name
  isExternal: true
  name: Name
  nameWithType: IStandardBindingElement.Name
  fullName: CoreWCF.Configuration.IStandardBindingElement.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
