### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.TcpTransportSecurityElement
  commentId: T:CoreWCF.Configuration.TcpTransportSecurityElement
  id: TcpTransportSecurityElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.TcpTransportSecurityElement.#ctor
  - CoreWCF.Configuration.TcpTransportSecurityElement.ClientCredentialType
  - CoreWCF.Configuration.TcpTransportSecurityElement.SslProtocols
  langs:
  - csharp
  - vb
  name: TcpTransportSecurityElement
  nameWithType: TcpTransportSecurityElement
  fullName: CoreWCF.Configuration.TcpTransportSecurityElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: An XML element that defines the security settings for a TcpTransport binding. This class cannot be inherited.
  remarks: To be added.
  syntax:
    content: 'public class TcpTransportSecurityElement : ServiceModelConfigurationElement'
    content.vb: >-
      Public Class TcpTransportSecurityElement
          Inherits ServiceModelConfigurationElement
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElement
  inheritedMembers:
  - CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.TcpTransportSecurityElement.#ctor
  commentId: M:CoreWCF.Configuration.TcpTransportSecurityElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  - vb
  name: TcpTransportSecurityElement()
  nameWithType: TcpTransportSecurityElement.TcpTransportSecurityElement()
  fullName: CoreWCF.Configuration.TcpTransportSecurityElement.TcpTransportSecurityElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public TcpTransportSecurityElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.TcpTransportSecurityElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.TcpTransportSecurityElement.ClientCredentialType
  commentId: P:CoreWCF.Configuration.TcpTransportSecurityElement.ClientCredentialType
  id: ClientCredentialType
  parent: CoreWCF.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  - vb
  name: ClientCredentialType
  nameWithType: TcpTransportSecurityElement.ClientCredentialType
  fullName: CoreWCF.Configuration.TcpTransportSecurityElement.ClientCredentialType
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public TcpClientCredentialType ClientCredentialType { get; set; }
    parameters: []
    return:
      type: CoreWCF.TcpClientCredentialType
    content.vb: Public Property ClientCredentialType As TcpClientCredentialType
  overload: CoreWCF.Configuration.TcpTransportSecurityElement.ClientCredentialType*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.TcpTransportSecurityElement.SslProtocols
  commentId: P:CoreWCF.Configuration.TcpTransportSecurityElement.SslProtocols
  id: SslProtocols
  parent: CoreWCF.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  - vb
  name: SslProtocols
  nameWithType: TcpTransportSecurityElement.SslProtocols
  fullName: CoreWCF.Configuration.TcpTransportSecurityElement.SslProtocols
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public SslProtocols SslProtocols { get; }
    parameters: []
    return:
      type: System.Security.Authentication.SslProtocols
    content.vb: Public ReadOnly Property SslProtocols As SslProtocols
  overload: CoreWCF.Configuration.TcpTransportSecurityElement.SslProtocols*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: CoreWCF.Configuration.ServiceModelConfigurationElement
  definition: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  isExternal: true
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.TcpTransportSecurityElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.TcpTransportSecurityElement.#ctor
  isExternal: true
  name: TcpTransportSecurityElement
  nameWithType: TcpTransportSecurityElement.TcpTransportSecurityElement
  fullName: CoreWCF.Configuration.TcpTransportSecurityElement.TcpTransportSecurityElement
- uid: CoreWCF.Configuration.TcpTransportSecurityElement.ClientCredentialType*
  commentId: Overload:CoreWCF.Configuration.TcpTransportSecurityElement.ClientCredentialType
  isExternal: true
  name: ClientCredentialType
  nameWithType: TcpTransportSecurityElement.ClientCredentialType
  fullName: CoreWCF.Configuration.TcpTransportSecurityElement.ClientCredentialType
- uid: CoreWCF.TcpClientCredentialType
  commentId: T:CoreWCF.TcpClientCredentialType
  parent: CoreWCF
  isExternal: true
  name: TcpClientCredentialType
  nameWithType: TcpClientCredentialType
  fullName: CoreWCF.TcpClientCredentialType
- uid: CoreWCF
  commentId: N:CoreWCF
  isExternal: true
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: CoreWCF.Configuration.TcpTransportSecurityElement.SslProtocols*
  commentId: Overload:CoreWCF.Configuration.TcpTransportSecurityElement.SslProtocols
  isExternal: true
  name: SslProtocols
  nameWithType: TcpTransportSecurityElement.SslProtocols
  fullName: CoreWCF.Configuration.TcpTransportSecurityElement.SslProtocols
- uid: System.Security.Authentication.SslProtocols
  isExternal: true
  name: SslProtocols
  nameWithType: SslProtocols
  fullName: System.Security.Authentication.SslProtocols
