### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.BindingsSection
  commentId: T:CoreWCF.Configuration.BindingsSection
  id: BindingsSection
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.BindingsSection.#ctor
  - CoreWCF.Configuration.BindingsSection.BasicHttpBinding
  - CoreWCF.Configuration.BindingsSection.CustomBinding
  - CoreWCF.Configuration.BindingsSection.NetHttpBinding
  - CoreWCF.Configuration.BindingsSection.NetTcpBinding
  - CoreWCF.Configuration.BindingsSection.wsHttpBinding
  langs:
  - csharp
  - vb
  name: BindingsSection
  nameWithType: BindingsSection
  fullName: CoreWCF.Configuration.BindingsSection
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a collection of binding elements. This class cannot be inherited.
  syntax:
    content: 'public sealed class BindingsSection : ConfigurationSection'
    content.vb: >-
      Public NotInheritable Class BindingsSection
          Inherits ConfigurationSection
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.BindingsSection.#ctor
  commentId: M:CoreWCF.Configuration.BindingsSection.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.BindingsSection
  langs:
  - csharp
  - vb
  name: BindingsSection()
  summary: Initializes a new instance of the [BindingsSection](xref:CoreWCF.Configuration.BindingsSection) class.
  nameWithType: BindingsSection.BindingsSection()
  fullName: CoreWCF.Configuration.BindingsSection.BindingsSection()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public BindingsSection()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.BindingsSection.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.BindingsSection.BasicHttpBinding
  commentId: P:CoreWCF.Configuration.BindingsSection.BasicHttpBinding
  id: BasicHttpBinding
  parent: CoreWCF.Configuration.BindingsSection
  langs:
  - csharp
  - vb
  name: BasicHttpBinding
  summary: Gets the configuration element that contains a collection of [BasicHttpBindingElement](xref:CoreWCF.Configuration.BasicHttpBindingElement) objects.
  nameWithType: BindingsSection.BasicHttpBinding
  fullName: CoreWCF.Configuration.BindingsSection.BasicHttpBinding
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public BasicHttpBindingCollectionElement BasicHttpBinding { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.BasicHttpBindingCollectionElement
      description: A [BasicHttpBindingCollectionElement](xref:CoreWCF.Configuration.BasicHttpBindingCollectionElement) object that defines the configuration section that contains a collection of [BasicHttpBindingElement](xref:CoreWCF.Configuration.BasicHttpBindingElement) objects.
    content.vb: Public ReadOnly Property BasicHttpBinding As BasicHttpBindingCollectionElement
  overload: CoreWCF.Configuration.BindingsSection.BasicHttpBinding*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: CoreWCF.Configuration.BindingsSection.NetTcpBinding
  commentId: P:CoreWCF.Configuration.BindingsSection.NetTcpBinding
  id: NetTcpBinding
  parent: CoreWCF.Configuration.BindingsSection
  langs:
  - csharp
  - vb
  name: NetTcpBinding
  summary: Gets the configuration element that contains a collection of [NetTcpBindingElement](xref:CoreWCF.Configuration.BindingsSection.NetTcpBinding) objects.
  nameWithType: BindingsSection.NetTcpBinding
  fullName: CoreWCF.Configuration.BindingsSection.NetTcpBinding
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public NetTcpBindingCollectionElement NetTcpBinding { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.NetTcpBindingCollectionElement
      description: A [NetTcpBindingCollectionElement](xref:CoreWCF.Configuration.NetTcpBindingCollectionElement) that contains a collection of [NetTcpBindingElement](xref:CoreWCF.Configuration.NetTcpBindingElement) objects.
    content.vb: Public ReadOnly Property NetTcpBinding As NetTcpBindingCollectionElement
  overload: CoreWCF.Configuration.BindingsSection.NetTcpBinding*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: CoreWCF.Configuration.BindingsSection.NetHttpBinding
  commentId: P:CoreWCF.Configuration.BindingsSection.NetHttpBinding
  id: NetHttpBinding
  parent: CoreWCF.Configuration.BindingsSection
  langs:
  - csharp
  - vb
  name: NetHttpBinding
  summary: Gets the net HTTPS binding used.
  nameWithType: BindingsSection.NetHttpBinding
  fullName: CoreWCF.Configuration.BindingsSection.NetHttpBinding
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public NetHttpBindingCollectionElement NetHttpBinding { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.NetHttpBindingCollectionElement
      description: A [NetHttpsBindingCollectionElement](xref:CoreWCF.Configuration.NetHttpBindingCollectionElement) object that defines the configuration section that contains a collection of [NetHttpsBindingElement](xref:System.ServiceModel.Configuration.NetHttpsBindingElement) objects.
    content.vb: Public ReadOnly Property NetHttpBinding As NetHttpBindingCollectionElement
  overload: CoreWCF.Configuration.BindingsSection.NetHttpBinding*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: CoreWCF.Configuration.BindingsSection.wsHttpBinding
  commentId: P:CoreWCF.Configuration.BindingsSection.wsHttpBinding
  id: wsHttpBinding
  parent: CoreWCF.Configuration.BindingsSection
  langs:
  - csharp
  - vb
  name: wsHttpBinding
  summary: Gets the configuration element that contains a collection of [WSHttpBindingElement](xref:CoreWCF.Configuration.WSHttpBindingElement) objects.
  nameWithType: BindingsSection.wsHttpBinding
  fullName: CoreWCF.Configuration.BindingsSection.wsHttpBinding
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public WSHttpBindingCollectionElement wsHttpBinding { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.WSHttpBindingCollectionElement
      description: A [WSHttpBindingCollectionElement](xref:CoreWCF.Configuration.WSHttpBindingCollectionElement) that contains a collection of [WSHttpBindingElement](xref:CoreWCF.Configuration.WSHttpBindingElement) objects.
    content.vb: Public ReadOnly Property wsHttpBinding As WSHttpBindingCollectionElement
  overload: CoreWCF.Configuration.BindingsSection.wsHttpBinding*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: CoreWCF.Configuration.BindingsSection.CustomBinding
  commentId: P:CoreWCF.Configuration.BindingsSection.CustomBinding
  id: CustomBinding
  parent: CoreWCF.Configuration.BindingsSection
  langs:
  - csharp
  - vb
  name: CustomBinding
  summary: Gets the configuration section that provides full control over the messaging stack for the user.
  nameWithType: BindingsSection.CustomBinding
  fullName: CoreWCF.Configuration.BindingsSection.CustomBinding
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public CustomBindingCollectionElement CustomBinding { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.CustomBindingCollectionElement
      description: A [CustomBindingCollectionElement](xref:CoreWCF.Configuration.CustomBindingCollectionElement) object that contains a collection of custom binding elements.
    content.vb: Public ReadOnly Property CustomBinding As CustomBindingCollectionElement
  overload: CoreWCF.Configuration.BindingsSection.CustomBinding*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.BindingsSection.#ctor*
  commentId: Overload:CoreWCF.Configuration.BindingsSection.#ctor
  isExternal: true
  name: BindingsSection
  nameWithType: BindingsSection.BindingsSection
  fullName: CoreWCF.Configuration.BindingsSection.BindingsSection
- uid: CoreWCF.Configuration.BindingsSection.BasicHttpBinding*
  commentId: Overload:CoreWCF.Configuration.BindingsSection.BasicHttpBinding
  isExternal: true
  name: BasicHttpBinding
  nameWithType: BindingsSection.BasicHttpBinding
  fullName: CoreWCF.Configuration.BindingsSection.BasicHttpBinding
- uid: CoreWCF.Configuration.BasicHttpBindingCollectionElement
  commentId: T:CoreWCF.Configuration.BasicHttpBindingCollectionElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: BasicHttpBindingCollectionElement
  nameWithType: BasicHttpBindingCollectionElement
  fullName: CoreWCF.Configuration.BasicHttpBindingCollectionElement
- uid: CoreWCF.Configuration.BindingsSection.NetTcpBinding*
  commentId: Overload:CoreWCF.Configuration.BindingsSection.NetTcpBinding
  isExternal: true
  name: NetTcpBinding
  nameWithType: BindingsSection.NetTcpBinding
  fullName: CoreWCF.Configuration.BindingsSection.NetTcpBinding
- uid: CoreWCF.Configuration.NetTcpBindingCollectionElement
  commentId: T:CoreWCF.Configuration.NetTcpBindingCollectionElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: NetTcpBindingCollectionElement
  nameWithType: NetTcpBindingCollectionElement
  fullName: CoreWCF.Configuration.NetTcpBindingCollectionElement
- uid: CoreWCF.Configuration.BindingsSection.NetHttpBinding*
  commentId: Overload:CoreWCF.Configuration.BindingsSection.NetHttpBinding
  isExternal: true
  name: NetHttpBinding
  nameWithType: BindingsSection.NetHttpBinding
  fullName: CoreWCF.Configuration.BindingsSection.NetHttpBinding
- uid: CoreWCF.Configuration.NetHttpBindingCollectionElement
  commentId: T:CoreWCF.Configuration.NetHttpBindingCollectionElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: NetHttpBindingCollectionElement
  nameWithType: NetHttpBindingCollectionElement
  fullName: CoreWCF.Configuration.NetHttpBindingCollectionElement
- uid: CoreWCF.Configuration.BindingsSection.wsHttpBinding*
  commentId: Overload:CoreWCF.Configuration.BindingsSection.wsHttpBinding
  isExternal: true
  name: wsHttpBinding
  nameWithType: BindingsSection.wsHttpBinding
  fullName: CoreWCF.Configuration.BindingsSection.wsHttpBinding
- uid: CoreWCF.Configuration.WSHttpBindingCollectionElement
  commentId: T:CoreWCF.Configuration.WSHttpBindingCollectionElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: WSHttpBindingCollectionElement
  nameWithType: WSHttpBindingCollectionElement
  fullName: CoreWCF.Configuration.WSHttpBindingCollectionElement
- uid: CoreWCF.Configuration.BindingsSection.CustomBinding*
  commentId: Overload:CoreWCF.Configuration.BindingsSection.CustomBinding
  isExternal: true
  name: CustomBinding
  nameWithType: BindingsSection.CustomBinding
  fullName: CoreWCF.Configuration.BindingsSection.CustomBinding
- uid: CoreWCF.Configuration.CustomBindingCollectionElement
  commentId: T:CoreWCF.Configuration.CustomBindingCollectionElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: CustomBindingCollectionElement
  nameWithType: CustomBindingCollectionElement
  fullName: CoreWCF.Configuration.CustomBindingCollectionElement
