### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ITransportServiceBuilder
  commentId: T:CoreWCF.Configuration.ITransportServiceBuilder
  id: ITransportServiceBuilder
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ITransportServiceBuilder.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  langs:
  - csharp
  - vb
  name: ITransportServiceBuilder
  nameWithType: ITransportServiceBuilder
  fullName: CoreWCF.Configuration.ITransportServiceBuilder
  type: Interface
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public interface ITransportServiceBuilder
    content.vb: Public Interface ITransportServiceBuilder
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: CoreWCF.Configuration.ITransportServiceBuilder.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  commentId: M:CoreWCF.Configuration.ITransportServiceBuilder.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  id: Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  parent: CoreWCF.Configuration.ITransportServiceBuilder
  langs:
  - csharp
  - vb
  name: Configure(IApplicationBuilder)
  nameWithType: ITransportServiceBuilder.Configure(IApplicationBuilder)
  fullName: CoreWCF.Configuration.ITransportServiceBuilder.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: void Configure(IApplicationBuilder app)
    parameters:
    - id: app
      type: Microsoft.AspNetCore.Builder.IApplicationBuilder
    content.vb: Sub Configure(app As IApplicationBuilder)
  overload: CoreWCF.Configuration.ITransportServiceBuilder.Configure*
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: CoreWCF.Configuration.ITransportServiceBuilder.Configure*
  commentId: Overload:CoreWCF.Configuration.ITransportServiceBuilder.Configure
  isExternal: true
  name: Configure
  nameWithType: ITransportServiceBuilder.Configure
  fullName: CoreWCF.Configuration.ITransportServiceBuilder.Configure
- uid: Microsoft.AspNetCore.Builder.IApplicationBuilder
  isExternal: true
  name: IApplicationBuilder
  nameWithType: IApplicationBuilder
  fullName: Microsoft.AspNetCore.Builder.IApplicationBuilder
