### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceConfigurationBuilder
  commentId: T:CoreWCF.Configuration.ServiceConfigurationBuilder
  id: ServiceConfigurationBuilder
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceConfigurationBuilder.#ctor(System.Type)
  - CoreWCF.Configuration.ServiceConfigurationBuilder.AddServiceEndpoint(System.Type,CoreWCF.Channels.Binding,System.Uri,System.Uri)
  - CoreWCF.Configuration.ServiceConfigurationBuilder.Configure(System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder})
  langs:
  - csharp
  - vb
  name: ServiceConfigurationBuilder
  nameWithType: ServiceConfigurationBuilder
  fullName: CoreWCF.Configuration.ServiceConfigurationBuilder
  type: Class
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public class ServiceConfigurationBuilder : Object'
    content.vb: >-
      Public Class ServiceConfigurationBuilder
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.ServiceConfigurationBuilder.#ctor(System.Type)
  commentId: M:CoreWCF.Configuration.ServiceConfigurationBuilder.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: CoreWCF.Configuration.ServiceConfigurationBuilder
  langs:
  - csharp
  - vb
  name: ServiceConfigurationBuilder(Type)
  nameWithType: ServiceConfigurationBuilder.ServiceConfigurationBuilder(Type)
  fullName: CoreWCF.Configuration.ServiceConfigurationBuilder.ServiceConfigurationBuilder(System.Type)
  type: Constructor
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceConfigurationBuilder(Type serviceType)
    parameters:
    - id: serviceType
      type: System.Type
    content.vb: Public Sub New(serviceType As Type)
  overload: CoreWCF.Configuration.ServiceConfigurationBuilder.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceConfigurationBuilder.Configure(System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder})
  commentId: M:CoreWCF.Configuration.ServiceConfigurationBuilder.Configure(System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder})
  id: Configure(System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder})
  parent: CoreWCF.Configuration.ServiceConfigurationBuilder
  langs:
  - csharp
  - vb
  name: Configure(Action<ServiceConfigurationBuilder>)
  nameWithType: ServiceConfigurationBuilder.Configure(Action<ServiceConfigurationBuilder>)
  fullName: CoreWCF.Configuration.ServiceConfigurationBuilder.Configure(System.Action<CoreWCF.Configuration.ServiceConfigurationBuilder>)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public void Configure(Action<ServiceConfigurationBuilder> configDelegate)
    parameters:
    - id: configDelegate
      type: System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder}
    content.vb: Public Sub Configure(configDelegate As Action(Of ServiceConfigurationBuilder))
  overload: CoreWCF.Configuration.ServiceConfigurationBuilder.Configure*
  nameWithType.vb: ServiceConfigurationBuilder.Configure(Action(Of ServiceConfigurationBuilder))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: CoreWCF.Configuration.ServiceConfigurationBuilder.Configure(System.Action(Of CoreWCF.Configuration.ServiceConfigurationBuilder))
  name.vb: Configure(Action(Of ServiceConfigurationBuilder))
- uid: CoreWCF.Configuration.ServiceConfigurationBuilder.AddServiceEndpoint(System.Type,CoreWCF.Channels.Binding,System.Uri,System.Uri)
  commentId: M:CoreWCF.Configuration.ServiceConfigurationBuilder.AddServiceEndpoint(System.Type,CoreWCF.Channels.Binding,System.Uri,System.Uri)
  id: AddServiceEndpoint(System.Type,CoreWCF.Channels.Binding,System.Uri,System.Uri)
  parent: CoreWCF.Configuration.ServiceConfigurationBuilder
  langs:
  - csharp
  - vb
  name: AddServiceEndpoint(Type, Binding, Uri, Uri)
  nameWithType: ServiceConfigurationBuilder.AddServiceEndpoint(Type, Binding, Uri, Uri)
  fullName: CoreWCF.Configuration.ServiceConfigurationBuilder.AddServiceEndpoint(System.Type, CoreWCF.Channels.Binding, System.Uri, System.Uri)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public void AddServiceEndpoint(Type implementedContract, Binding binding, Uri address, Uri listenUri)
    parameters:
    - id: implementedContract
      type: System.Type
    - id: binding
      type: CoreWCF.Channels.Binding
    - id: address
      type: System.Uri
    - id: listenUri
      type: System.Uri
    content.vb: Public Sub AddServiceEndpoint(implementedContract As Type, binding As Binding, address As Uri, listenUri As Uri)
  overload: CoreWCF.Configuration.ServiceConfigurationBuilder.AddServiceEndpoint*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceConfigurationBuilder.#ctor*
  commentId: Overload:CoreWCF.Configuration.ServiceConfigurationBuilder.#ctor
  isExternal: true
  name: ServiceConfigurationBuilder
  nameWithType: ServiceConfigurationBuilder.ServiceConfigurationBuilder
  fullName: CoreWCF.Configuration.ServiceConfigurationBuilder.ServiceConfigurationBuilder
- uid: System.Type
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: CoreWCF.Configuration.ServiceConfigurationBuilder.Configure*
  commentId: Overload:CoreWCF.Configuration.ServiceConfigurationBuilder.Configure
  isExternal: true
  name: Configure
  nameWithType: ServiceConfigurationBuilder.Configure
  fullName: CoreWCF.Configuration.ServiceConfigurationBuilder.Configure
- uid: System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder}
  commentId: '!:System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder}'
  definition: System.Action`1
  name: Action<ServiceConfigurationBuilder>
  nameWithType: Action<ServiceConfigurationBuilder>
  fullName: System.Action<CoreWCF.Configuration.ServiceConfigurationBuilder>
  nameWithType.vb: Action(Of ServiceConfigurationBuilder)
  fullName.vb: System.Action(Of CoreWCF.Configuration.ServiceConfigurationBuilder)
  name.vb: Action(Of ServiceConfigurationBuilder)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.Configuration.ServiceConfigurationBuilder
    name: ServiceConfigurationBuilder
    nameWithType: ServiceConfigurationBuilder
    fullName: CoreWCF.Configuration.ServiceConfigurationBuilder
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.Configuration.ServiceConfigurationBuilder
    name: ServiceConfigurationBuilder
    nameWithType: ServiceConfigurationBuilder
    fullName: CoreWCF.Configuration.ServiceConfigurationBuilder
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Action`1
  isExternal: true
  name: Action<>
  nameWithType: Action<>
  fullName: System.Action<>
  nameWithType.vb: Action(Of )
  fullName.vb: System.Action(Of )
  name.vb: Action(Of )
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceConfigurationBuilder.AddServiceEndpoint*
  commentId: Overload:CoreWCF.Configuration.ServiceConfigurationBuilder.AddServiceEndpoint
  isExternal: true
  name: AddServiceEndpoint
  nameWithType: ServiceConfigurationBuilder.AddServiceEndpoint
  fullName: CoreWCF.Configuration.ServiceConfigurationBuilder.AddServiceEndpoint
- uid: CoreWCF.Channels.Binding
  commentId: T:CoreWCF.Channels.Binding
  parent: CoreWCF.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: CoreWCF.Channels.Binding
- uid: System.Uri
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: CoreWCF.Channels
  commentId: N:CoreWCF.Channels
  isExternal: true
  name: CoreWCF.Channels
  nameWithType: CoreWCF.Channels
  fullName: CoreWCF.Channels
