### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.XmlElementElementCollection
  commentId: T:CoreWCF.Configuration.XmlElementElementCollection
  id: XmlElementElementCollection
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.XmlElementElementCollection.#ctor
  - CoreWCF.Configuration.XmlElementElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - CoreWCF.Configuration.XmlElementElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - CoreWCF.Configuration.XmlElementElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  langs:
  - csharp
  - vb
  name: XmlElementElementCollection
  nameWithType: XmlElementElementCollection
  fullName: CoreWCF.Configuration.XmlElementElementCollection
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a collection of  instances. This class cannot be inherited.
  remarks: To be added.
  syntax:
    content: 'public sealed class XmlElementElementCollection : ServiceModelConfigurationElementCollection<XmlElementElement>'
    content.vb: >-
      Public NotInheritable Class XmlElementElementCollection
          Inherits ServiceModelConfigurationElementCollection(Of XmlElementElement)
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.XmlElementElement}
  inheritedMembers:
  - CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.XmlElementElement}.CreateNewElement
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.XmlElementElementCollection.#ctor
  commentId: M:CoreWCF.Configuration.XmlElementElementCollection.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.XmlElementElementCollection
  langs:
  - csharp
  - vb
  name: XmlElementElementCollection()
  nameWithType: XmlElementElementCollection.XmlElementElementCollection()
  fullName: CoreWCF.Configuration.XmlElementElementCollection.XmlElementElementCollection()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public XmlElementElementCollection()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.XmlElementElementCollection.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.XmlElementElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  commentId: M:CoreWCF.Configuration.XmlElementElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: CoreWCF.Configuration.XmlElementElementCollection
  langs:
  - csharp
  - vb
  name: GetElementKey(ConfigurationElement)
  nameWithType: XmlElementElementCollection.GetElementKey(ConfigurationElement)
  fullName: CoreWCF.Configuration.XmlElementElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override object GetElementKey(ConfigurationElement element)
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
    return:
      type: System.Object
    content.vb: Protected Overrides Function GetElementKey(element As ConfigurationElement) As Object
  overload: CoreWCF.Configuration.XmlElementElementCollection.GetElementKey*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: CoreWCF.Configuration.XmlElementElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  commentId: M:CoreWCF.Configuration.XmlElementElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  id: Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  parent: CoreWCF.Configuration.XmlElementElementCollection
  langs:
  - csharp
  - vb
  name: Unmerge(ConfigurationElement, ConfigurationElement, ConfigurationSaveMode)
  nameWithType: XmlElementElementCollection.Unmerge(ConfigurationElement, ConfigurationElement, ConfigurationSaveMode)
  fullName: CoreWCF.Configuration.XmlElementElementCollection.Unmerge(System.Configuration.ConfigurationElement, System.Configuration.ConfigurationElement, System.Configuration.ConfigurationSaveMode)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override void Unmerge(ConfigurationElement sourceElement, ConfigurationElement parentElement, ConfigurationSaveMode saveMode)
    parameters:
    - id: sourceElement
      type: System.Configuration.ConfigurationElement
    - id: parentElement
      type: System.Configuration.ConfigurationElement
    - id: saveMode
      type: System.Configuration.ConfigurationSaveMode
    content.vb: Protected Overrides Sub Unmerge(sourceElement As ConfigurationElement, parentElement As ConfigurationElement, saveMode As ConfigurationSaveMode)
  overload: CoreWCF.Configuration.XmlElementElementCollection.Unmerge*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: CoreWCF.Configuration.XmlElementElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  commentId: M:CoreWCF.Configuration.XmlElementElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  id: OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  parent: CoreWCF.Configuration.XmlElementElementCollection
  langs:
  - csharp
  - vb
  name: OnDeserializeUnrecognizedElement(String, XmlReader)
  nameWithType: XmlElementElementCollection.OnDeserializeUnrecognizedElement(String, XmlReader)
  fullName: CoreWCF.Configuration.XmlElementElementCollection.OnDeserializeUnrecognizedElement(System.String, System.Xml.XmlReader)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override bool OnDeserializeUnrecognizedElement(string elementName, XmlReader reader)
    parameters:
    - id: elementName
      type: System.String
    - id: reader
      type: System.Xml.XmlReader
    return:
      type: System.Boolean
    content.vb: Protected Overrides Function OnDeserializeUnrecognizedElement(elementName As String, reader As XmlReader) As Boolean
  overload: CoreWCF.Configuration.XmlElementElementCollection.OnDeserializeUnrecognizedElement*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.XmlElementElement}
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.XmlElementElement}
  parent: CoreWCF.Configuration
  definition: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  name: ServiceModelConfigurationElementCollection<XmlElementElement>
  nameWithType: ServiceModelConfigurationElementCollection<XmlElementElement>
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<CoreWCF.Configuration.XmlElementElement>
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of XmlElementElement)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of CoreWCF.Configuration.XmlElementElement)
  name.vb: ServiceModelConfigurationElementCollection(Of XmlElementElement)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.Configuration.XmlElementElement
    name: XmlElementElement
    nameWithType: XmlElementElement
    fullName: CoreWCF.Configuration.XmlElementElement
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.Configuration.XmlElementElement
    name: XmlElementElement
    nameWithType: XmlElementElement
    fullName: CoreWCF.Configuration.XmlElementElement
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.XmlElementElement}.CreateNewElement
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.XmlElementElement}.CreateNewElement
  parent: CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.XmlElementElement}
  definition: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  name: CreateNewElement()
  nameWithType: ServiceModelConfigurationElementCollection<XmlElementElement>.CreateNewElement()
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<CoreWCF.Configuration.XmlElementElement>.CreateNewElement()
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of XmlElementElement).CreateNewElement()
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of CoreWCF.Configuration.XmlElementElement).CreateNewElement()
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection<XmlElementElement>.CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<CoreWCF.Configuration.XmlElementElement>.CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection(Of XmlElementElement).CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of CoreWCF.Configuration.XmlElementElement).CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  isExternal: true
  name: ServiceModelConfigurationElementCollection<TConfigurationElementType>
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  name.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TConfigurationElementType
    nameWithType: TConfigurationElementType
    fullName: TConfigurationElementType
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TConfigurationElementType
    nameWithType: TConfigurationElementType
    fullName: TConfigurationElementType
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  isExternal: true
  name: CreateNewElement()
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement()
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement()
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement()
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement()
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.XmlElementElementCollection.#ctor*
  commentId: Overload:CoreWCF.Configuration.XmlElementElementCollection.#ctor
  isExternal: true
  name: XmlElementElementCollection
  nameWithType: XmlElementElementCollection.XmlElementElementCollection
  fullName: CoreWCF.Configuration.XmlElementElementCollection.XmlElementElementCollection
- uid: CoreWCF.Configuration.XmlElementElementCollection.GetElementKey*
  commentId: Overload:CoreWCF.Configuration.XmlElementElementCollection.GetElementKey
  isExternal: true
  name: GetElementKey
  nameWithType: XmlElementElementCollection.GetElementKey
  fullName: CoreWCF.Configuration.XmlElementElementCollection.GetElementKey
- uid: System.Configuration.ConfigurationElement
  isExternal: true
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: CoreWCF.Configuration.XmlElementElementCollection.Unmerge*
  commentId: Overload:CoreWCF.Configuration.XmlElementElementCollection.Unmerge
  isExternal: true
  name: Unmerge
  nameWithType: XmlElementElementCollection.Unmerge
  fullName: CoreWCF.Configuration.XmlElementElementCollection.Unmerge
- uid: System.Configuration.ConfigurationSaveMode
  isExternal: true
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
- uid: CoreWCF.Configuration.XmlElementElementCollection.OnDeserializeUnrecognizedElement*
  commentId: Overload:CoreWCF.Configuration.XmlElementElementCollection.OnDeserializeUnrecognizedElement
  isExternal: true
  name: OnDeserializeUnrecognizedElement
  nameWithType: XmlElementElementCollection.OnDeserializeUnrecognizedElement
  fullName: CoreWCF.Configuration.XmlElementElementCollection.OnDeserializeUnrecognizedElement
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xml.XmlReader
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
