### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElement
  id: ServiceModelConfigurationElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceModelConfigurationElement.#ctor
  - CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  langs:
  - csharp
  - vb
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: "\nBinding-related Configuration elements use this base class for WCF-wide commonalities\n"
  syntax:
    content: 'public abstract class ServiceModelConfigurationElement : ConfigurationElement'
    content.vb: >-
      Public MustInherit Class ServiceModelConfigurationElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  derivedClasses:
  - CoreWCF.Configuration.AddressHeaderCollectionElement
  - CoreWCF.Configuration.BasicHttpMessageSecurityElement
  - CoreWCF.Configuration.BasicHttpSecurityElement
  - CoreWCF.Configuration.EndpointAddressElementBase
  - CoreWCF.Configuration.HttpTransportSecurityElement
  - CoreWCF.Configuration.IssuedTokenParametersElement
  - CoreWCF.Configuration.LocalServiceSecuritySettingsElement
  - CoreWCF.Configuration.MessageSecurityOverHttpElement
  - CoreWCF.Configuration.MessageSecurityOverTcpElement
  - CoreWCF.Configuration.NetTcpSecurityElement
  - CoreWCF.Configuration.ServiceModelExtensionCollectionElement`1
  - CoreWCF.Configuration.ServiceModelExtensionElement
  - CoreWCF.Configuration.StandardBindingElement
  - CoreWCF.Configuration.TcpConnectionPoolSettingsElement
  - CoreWCF.Configuration.TcpTransportSecurityElement
  - CoreWCF.Configuration.WebSocketTransportSettingsElement
  - CoreWCF.Configuration.WSHttpSecurityElement
  - CoreWCF.Configuration.WSHttpTransportSecurityElement
  - CoreWCF.Configuration.XmlDictionaryReaderQuotasElement
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  id: SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: CoreWCF.Configuration.ServiceModelConfigurationElement
  langs:
  - csharp
  - vb
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: "\nUsed by InitializeFrom() pattern to avoid writing default values to generated .config files.\n"
  syntax:
    content: protected void SetPropertyValueIfNotDefaultValue<T>(string propertyName, T value)
    parameters:
    - id: propertyName
      type: System.String
      description: ConfigurationProperty.Name for the configuration property to set
    - id: value
      type: '{T}'
      description: Value to set
    typeParameters:
    - id: T
      description: "\n"
    content.vb: Protected Sub SetPropertyValueIfNotDefaultValue(Of T)(propertyName As String, value As T)
  overload: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue*
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.#ctor
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ServiceModelConfigurationElement
  langs:
  - csharp
  - vb
  name: ServiceModelConfigurationElement()
  nameWithType: ServiceModelConfigurationElement.ServiceModelConfigurationElement()
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.ServiceModelConfigurationElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected ServiceModelConfigurationElement()
    content.vb: Protected Sub New
  overload: CoreWCF.Configuration.ServiceModelConfigurationElement.#ctor*
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue*
  commentId: Overload:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue
  isExternal: true
  name: SetPropertyValueIfNotDefaultValue
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.ServiceModelConfigurationElement.#ctor
  isExternal: true
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement.ServiceModelConfigurationElement
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.ServiceModelConfigurationElement
