### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceNameElement
  commentId: T:CoreWCF.Configuration.ServiceNameElement
  id: ServiceNameElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceNameElement.#ctor
  - CoreWCF.Configuration.ServiceNameElement.Name
  langs:
  - csharp
  - vb
  name: ServiceNameElement
  nameWithType: ServiceNameElement
  fullName: CoreWCF.Configuration.ServiceNameElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: The  class represents a configuration element for a service name used in a .
  remarks: To be added.
  syntax:
    content: 'public sealed class ServiceNameElement : ConfigurationElement'
    content.vb: >-
      Public NotInheritable Class ServiceNameElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.ServiceNameElement.#ctor
  commentId: M:CoreWCF.Configuration.ServiceNameElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ServiceNameElement
  langs:
  - csharp
  - vb
  name: ServiceNameElement()
  nameWithType: ServiceNameElement.ServiceNameElement()
  fullName: CoreWCF.Configuration.ServiceNameElement.ServiceNameElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceNameElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.ServiceNameElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceNameElement.Name
  commentId: P:CoreWCF.Configuration.ServiceNameElement.Name
  id: Name
  parent: CoreWCF.Configuration.ServiceNameElement
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ServiceNameElement.Name
  fullName: CoreWCF.Configuration.ServiceNameElement.Name
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: CoreWCF.Configuration.ServiceNameElement.Name*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceNameElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.ServiceNameElement.#ctor
  isExternal: true
  name: ServiceNameElement
  nameWithType: ServiceNameElement.ServiceNameElement
  fullName: CoreWCF.Configuration.ServiceNameElement.ServiceNameElement
- uid: CoreWCF.Configuration.ServiceNameElement.Name*
  commentId: Overload:CoreWCF.Configuration.ServiceNameElement.Name
  isExternal: true
  name: Name
  nameWithType: ServiceNameElement.Name
  fullName: CoreWCF.Configuration.ServiceNameElement.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
