### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement
  commentId: T:CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement
  id: NonDualMessageSecurityOverHttpElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.#ctor
  - CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  langs:
  - csharp
  - vb
  name: NonDualMessageSecurityOverHttpElement
  nameWithType: NonDualMessageSecurityOverHttpElement
  fullName: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents the configuration settings for the security of a message sent using HTTP for non-duplex service contracts. This class cannot be inherited.
  remarks: To be added.
  syntax:
    content: 'public class NonDualMessageSecurityOverHttpElement : MessageSecurityOverHttpElement'
    content.vb: >-
      Public Class NonDualMessageSecurityOverHttpElement
          Inherits MessageSecurityOverHttpElement
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElement
  - CoreWCF.Configuration.MessageSecurityOverHttpElement
  inheritedMembers:
  - CoreWCF.Configuration.MessageSecurityOverHttpElement.ClientCredentialType
  - CoreWCF.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential
  - CoreWCF.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite
  - CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.#ctor
  commentId: M:CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement
  langs:
  - csharp
  - vb
  name: NonDualMessageSecurityOverHttpElement()
  nameWithType: NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement()
  fullName: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public NonDualMessageSecurityOverHttpElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  commentId: P:CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  id: EstablishSecurityContext
  parent: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement
  langs:
  - csharp
  - vb
  name: EstablishSecurityContext
  nameWithType: NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  fullName: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public bool EstablishSecurityContext { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property EstablishSecurityContext As Boolean
  overload: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement
  commentId: T:CoreWCF.Configuration.MessageSecurityOverHttpElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: MessageSecurityOverHttpElement
  nameWithType: MessageSecurityOverHttpElement
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement.ClientCredentialType
  commentId: P:CoreWCF.Configuration.MessageSecurityOverHttpElement.ClientCredentialType
  parent: CoreWCF.Configuration.MessageSecurityOverHttpElement
  isExternal: true
  name: ClientCredentialType
  nameWithType: MessageSecurityOverHttpElement.ClientCredentialType
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement.ClientCredentialType
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential
  commentId: P:CoreWCF.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential
  parent: CoreWCF.Configuration.MessageSecurityOverHttpElement
  isExternal: true
  name: NegotiateServiceCredential
  nameWithType: MessageSecurityOverHttpElement.NegotiateServiceCredential
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite
  commentId: P:CoreWCF.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite
  parent: CoreWCF.Configuration.MessageSecurityOverHttpElement
  isExternal: true
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverHttpElement.AlgorithmSuite
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: CoreWCF.Configuration.ServiceModelConfigurationElement
  definition: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  isExternal: true
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.#ctor
  isExternal: true
  name: NonDualMessageSecurityOverHttpElement
  nameWithType: NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement
  fullName: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.NonDualMessageSecurityOverHttpElement
- uid: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext*
  commentId: Overload:CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  isExternal: true
  name: EstablishSecurityContext
  nameWithType: NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
  fullName: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement.EstablishSecurityContext
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
