### YamlMime:ManagedReference
items:
- uid: CoreWCF.OpenApi.OpenApiContractInfo
  commentId: T:CoreWCF.OpenApi.OpenApiContractInfo
  id: OpenApiContractInfo
  parent: CoreWCF.OpenApi
  children:
  - CoreWCF.OpenApi.OpenApiContractInfo.#ctor
  - CoreWCF.OpenApi.OpenApiContractInfo.Contract
  - CoreWCF.OpenApi.OpenApiContractInfo.ResponseFormat
  langs:
  - csharp
  - vb
  name: OpenApiContractInfo
  nameWithType: OpenApiContractInfo
  fullName: CoreWCF.OpenApi.OpenApiContractInfo
  type: Class
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi
  summary: "\nCaptures information about a WCF contract needed by OpenAPI.\n"
  syntax:
    content: 'public class OpenApiContractInfo : Object'
    content.vb: >-
      Public Class OpenApiContractInfo
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.OpenApi.OpenApiContractInfo.#ctor
  commentId: M:CoreWCF.OpenApi.OpenApiContractInfo.#ctor
  id: '#ctor'
  parent: CoreWCF.OpenApi.OpenApiContractInfo
  langs:
  - csharp
  - vb
  name: OpenApiContractInfo()
  nameWithType: OpenApiContractInfo.OpenApiContractInfo()
  fullName: CoreWCF.OpenApi.OpenApiContractInfo.OpenApiContractInfo()
  type: Constructor
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi
  syntax:
    content: public OpenApiContractInfo()
    content.vb: Public Sub New
  overload: CoreWCF.OpenApi.OpenApiContractInfo.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.OpenApiContractInfo.Contract
  commentId: P:CoreWCF.OpenApi.OpenApiContractInfo.Contract
  id: Contract
  parent: CoreWCF.OpenApi.OpenApiContractInfo
  langs:
  - csharp
  - vb
  name: Contract
  nameWithType: OpenApiContractInfo.Contract
  fullName: CoreWCF.OpenApi.OpenApiContractInfo.Contract
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi
  summary: "\nThe actual contract.\n"
  syntax:
    content: public Type Contract { get; set; }
    parameters: []
    return:
      type: System.Type
    content.vb: Public Property Contract As Type
  overload: CoreWCF.OpenApi.OpenApiContractInfo.Contract*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.OpenApiContractInfo.ResponseFormat
  commentId: P:CoreWCF.OpenApi.OpenApiContractInfo.ResponseFormat
  id: ResponseFormat
  parent: CoreWCF.OpenApi.OpenApiContractInfo
  langs:
  - csharp
  - vb
  name: ResponseFormat
  nameWithType: OpenApiContractInfo.ResponseFormat
  fullName: CoreWCF.OpenApi.OpenApiContractInfo.ResponseFormat
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi
  summary: "\nDefault format of the response.\n"
  syntax:
    content: public WebMessageFormat ResponseFormat { get; set; }
    parameters: []
    return:
      type: CoreWCF.Web.WebMessageFormat
    content.vb: Public Property ResponseFormat As WebMessageFormat
  overload: CoreWCF.OpenApi.OpenApiContractInfo.ResponseFormat*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.OpenApi
  commentId: N:CoreWCF.OpenApi
  isExternal: true
  name: CoreWCF.OpenApi
  nameWithType: CoreWCF.OpenApi
  fullName: CoreWCF.OpenApi
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.OpenApi.OpenApiContractInfo.#ctor*
  commentId: Overload:CoreWCF.OpenApi.OpenApiContractInfo.#ctor
  isExternal: true
  name: OpenApiContractInfo
  nameWithType: OpenApiContractInfo.OpenApiContractInfo
  fullName: CoreWCF.OpenApi.OpenApiContractInfo.OpenApiContractInfo
- uid: CoreWCF.OpenApi.OpenApiContractInfo.Contract*
  commentId: Overload:CoreWCF.OpenApi.OpenApiContractInfo.Contract
  isExternal: true
  name: Contract
  nameWithType: OpenApiContractInfo.Contract
  fullName: CoreWCF.OpenApi.OpenApiContractInfo.Contract
- uid: System.Type
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: CoreWCF.OpenApi.OpenApiContractInfo.ResponseFormat*
  commentId: Overload:CoreWCF.OpenApi.OpenApiContractInfo.ResponseFormat
  isExternal: true
  name: ResponseFormat
  nameWithType: OpenApiContractInfo.ResponseFormat
  fullName: CoreWCF.OpenApi.OpenApiContractInfo.ResponseFormat
- uid: CoreWCF.Web.WebMessageFormat
  commentId: T:CoreWCF.Web.WebMessageFormat
  parent: CoreWCF.Web
  isExternal: true
  name: WebMessageFormat
  nameWithType: WebMessageFormat
  fullName: CoreWCF.Web.WebMessageFormat
- uid: CoreWCF.Web
  commentId: N:CoreWCF.Web
  isExternal: true
  name: CoreWCF.Web
  nameWithType: CoreWCF.Web
  fullName: CoreWCF.Web
