### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ClaimTypeElement
  commentId: T:CoreWCF.Configuration.ClaimTypeElement
  id: ClaimTypeElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ClaimTypeElement.#ctor
  - CoreWCF.Configuration.ClaimTypeElement.#ctor(System.String,System.Boolean)
  - CoreWCF.Configuration.ClaimTypeElement.ClaimType
  - CoreWCF.Configuration.ClaimTypeElement.IsOptional
  langs:
  - csharp
  - vb
  name: ClaimTypeElement
  nameWithType: ClaimTypeElement
  fullName: CoreWCF.Configuration.ClaimTypeElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a configuration element that contains the type of claim. This class cannot be inherited.
  remarks: To be added.
  syntax:
    content: 'public sealed class ClaimTypeElement : ConfigurationElement'
    content.vb: >-
      Public NotInheritable Class ClaimTypeElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.ClaimTypeElement.#ctor
  commentId: M:CoreWCF.Configuration.ClaimTypeElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ClaimTypeElement
  langs:
  - csharp
  - vb
  name: ClaimTypeElement()
  nameWithType: ClaimTypeElement.ClaimTypeElement()
  fullName: CoreWCF.Configuration.ClaimTypeElement.ClaimTypeElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ClaimTypeElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.ClaimTypeElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ClaimTypeElement.#ctor(System.String,System.Boolean)
  commentId: M:CoreWCF.Configuration.ClaimTypeElement.#ctor(System.String,System.Boolean)
  id: '#ctor(System.String,System.Boolean)'
  parent: CoreWCF.Configuration.ClaimTypeElement
  langs:
  - csharp
  - vb
  name: ClaimTypeElement(String, Boolean)
  nameWithType: ClaimTypeElement.ClaimTypeElement(String, Boolean)
  fullName: CoreWCF.Configuration.ClaimTypeElement.ClaimTypeElement(System.String, System.Boolean)
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ClaimTypeElement(string claimType, bool isOptional)
    parameters:
    - id: claimType
      type: System.String
    - id: isOptional
      type: System.Boolean
    content.vb: Public Sub New(claimType As String, isOptional As Boolean)
  overload: CoreWCF.Configuration.ClaimTypeElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ClaimTypeElement.ClaimType
  commentId: P:CoreWCF.Configuration.ClaimTypeElement.ClaimType
  id: ClaimType
  parent: CoreWCF.Configuration.ClaimTypeElement
  langs:
  - csharp
  - vb
  name: ClaimType
  nameWithType: ClaimTypeElement.ClaimType
  fullName: CoreWCF.Configuration.ClaimTypeElement.ClaimType
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string ClaimType { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ClaimType As String
  overload: CoreWCF.Configuration.ClaimTypeElement.ClaimType*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ClaimTypeElement.IsOptional
  commentId: P:CoreWCF.Configuration.ClaimTypeElement.IsOptional
  id: IsOptional
  parent: CoreWCF.Configuration.ClaimTypeElement
  langs:
  - csharp
  - vb
  name: IsOptional
  nameWithType: ClaimTypeElement.IsOptional
  fullName: CoreWCF.Configuration.ClaimTypeElement.IsOptional
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public bool IsOptional { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsOptional As Boolean
  overload: CoreWCF.Configuration.ClaimTypeElement.IsOptional*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ClaimTypeElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.ClaimTypeElement.#ctor
  isExternal: true
  name: ClaimTypeElement
  nameWithType: ClaimTypeElement.ClaimTypeElement
  fullName: CoreWCF.Configuration.ClaimTypeElement.ClaimTypeElement
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: CoreWCF.Configuration.ClaimTypeElement.ClaimType*
  commentId: Overload:CoreWCF.Configuration.ClaimTypeElement.ClaimType
  isExternal: true
  name: ClaimType
  nameWithType: ClaimTypeElement.ClaimType
  fullName: CoreWCF.Configuration.ClaimTypeElement.ClaimType
- uid: CoreWCF.Configuration.ClaimTypeElement.IsOptional*
  commentId: Overload:CoreWCF.Configuration.ClaimTypeElement.IsOptional
  isExternal: true
  name: IsOptional
  nameWithType: ClaimTypeElement.IsOptional
  fullName: CoreWCF.Configuration.ClaimTypeElement.IsOptional
