### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement`2
  id: StandardBindingCollectionElement`2
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.StandardBindingCollectionElement`2.#ctor
  - CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  langs:
  - csharp
  - vb
  name: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Provides a base class for the configuration sections that specify predefined bindings provided by Windows Communication Foundation (WCF).
  remarks: To be added.
  syntax:
    content: 'public class StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration> : BindingCollectionElement where TStandardBinding : Binding where TBindingConfiguration : ConfigurationElement, IDefaultCommunicationTimeouts, IStandardBindingElement, new()'
    typeParameters:
    - id: TStandardBinding
    - id: TBindingConfiguration
    content.vb: >-
      Public Class StandardBindingCollectionElement(Of TStandardBinding As Binding, TBindingConfiguration As {ConfigurationElement, IDefaultCommunicationTimeouts, IStandardBindingElement, New})
          Inherits BindingCollectionElement
  inheritance:
  - System.Object
  - CoreWCF.Configuration.BindingCollectionElement
  derivedClasses:
  - CoreWCF.Configuration.BasicHttpBindingCollectionElement
  - CoreWCF.Configuration.CustomBindingCollectionElement
  - CoreWCF.Configuration.NetHttpBindingCollectionElement
  - CoreWCF.Configuration.NetTcpBindingCollectionElement
  - CoreWCF.Configuration.WSHttpBindingCollectionElement
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  name.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2.#ctor
  commentId: M:CoreWCF.Configuration.StandardBindingCollectionElement`2.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.StandardBindingCollectionElement`2
  langs:
  - csharp
  - vb
  name: StandardBindingCollectionElement()
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.StandardBindingCollectionElement()
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.StandardBindingCollectionElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public StandardBindingCollectionElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.StandardBindingCollectionElement`2.#ctor*
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).StandardBindingCollectionElement()
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).StandardBindingCollectionElement()
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  id: Bindings
  parent: CoreWCF.Configuration.StandardBindingCollectionElement`2
  langs:
  - csharp
  - vb
  name: Bindings
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public StandardBindingElementCollection<TBindingConfiguration> Bindings { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.StandardBindingElementCollection{{TBindingConfiguration}}
    content.vb: Public ReadOnly Property Bindings As StandardBindingElementCollection(Of TBindingConfiguration)
  overload: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings*
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.BindingCollectionElement
  commentId: T:CoreWCF.Configuration.BindingCollectionElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement
  fullName: CoreWCF.Configuration.BindingCollectionElement
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2.#ctor*
  commentId: Overload:CoreWCF.Configuration.StandardBindingCollectionElement`2.#ctor
  isExternal: true
  name: StandardBindingCollectionElement
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.StandardBindingCollectionElement
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.StandardBindingCollectionElement
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).StandardBindingCollectionElement
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).StandardBindingCollectionElement
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings*
  commentId: Overload:CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  isExternal: true
  name: Bindings
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
- uid: CoreWCF.Configuration.StandardBindingElementCollection{{TBindingConfiguration}}
  commentId: T:CoreWCF.Configuration.StandardBindingElementCollection{`1}
  parent: CoreWCF.Configuration
  definition: CoreWCF.Configuration.StandardBindingElementCollection`1
  name: StandardBindingElementCollection<TBindingConfiguration>
  nameWithType: StandardBindingElementCollection<TBindingConfiguration>
  fullName: CoreWCF.Configuration.StandardBindingElementCollection<TBindingConfiguration>
  nameWithType.vb: StandardBindingElementCollection(Of TBindingConfiguration)
  fullName.vb: CoreWCF.Configuration.StandardBindingElementCollection(Of TBindingConfiguration)
  name.vb: StandardBindingElementCollection(Of TBindingConfiguration)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingElementCollection`1
    name: StandardBindingElementCollection
    nameWithType: StandardBindingElementCollection
    fullName: CoreWCF.Configuration.StandardBindingElementCollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingElementCollection`1
    name: StandardBindingElementCollection
    nameWithType: StandardBindingElementCollection
    fullName: CoreWCF.Configuration.StandardBindingElementCollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingElementCollection`1
  commentId: T:CoreWCF.Configuration.StandardBindingElementCollection`1
  isExternal: true
  name: StandardBindingElementCollection<TBindingConfiguration>
  nameWithType: StandardBindingElementCollection<TBindingConfiguration>
  fullName: CoreWCF.Configuration.StandardBindingElementCollection<TBindingConfiguration>
  nameWithType.vb: StandardBindingElementCollection(Of TBindingConfiguration)
  fullName.vb: CoreWCF.Configuration.StandardBindingElementCollection(Of TBindingConfiguration)
  name.vb: StandardBindingElementCollection(Of TBindingConfiguration)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingElementCollection`1
    name: StandardBindingElementCollection
    nameWithType: StandardBindingElementCollection
    fullName: CoreWCF.Configuration.StandardBindingElementCollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingElementCollection`1
    name: StandardBindingElementCollection
    nameWithType: StandardBindingElementCollection
    fullName: CoreWCF.Configuration.StandardBindingElementCollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: )
    nameWithType: )
    fullName: )
