### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  id: ServiceModelConfigurationElementCollection`1
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  langs:
  - csharp
  - vb
  name: ServiceModelConfigurationElementCollection<TConfigurationElementType>
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents an abstract base class for a  used within the  namespace.
  remarks: To be added.
  syntax:
    content: 'public abstract class ServiceModelConfigurationElementCollection<TConfigurationElementType> : ConfigurationElementCollection where TConfigurationElementType : ConfigurationElement, new()'
    typeParameters:
    - id: TConfigurationElementType
    content.vb: >-
      Public MustInherit Class ServiceModelConfigurationElementCollection(Of TConfigurationElementType As {ConfigurationElement, New})
          Inherits ConfigurationElementCollection
  inheritance:
  - System.Object
  derivedClasses:
  - CoreWCF.Configuration.ClaimTypeElementCollection
  - CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
  - CoreWCF.Configuration.XmlElementElementCollection
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  name.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  id: CreateNewElement
  parent: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  langs:
  - csharp
  - vb
  name: CreateNewElement()
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement()
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement()
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override ConfigurationElement CreateNewElement()
    return:
      type: System.Configuration.ConfigurationElement
    content.vb: Protected Overrides Function CreateNewElement As ConfigurationElement
  overload: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement*
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement()
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement()
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement*
  commentId: Overload:CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  isExternal: true
  name: CreateNewElement
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement
- uid: System.Configuration.ConfigurationElement
  isExternal: true
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
