### YamlMime:ManagedReference
items:
- uid: CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute
  id: OpenApiHiddenAttribute
  parent: CoreWCF.OpenApi.Attributes
  children:
  - CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute.#ctor
  langs:
  - csharp
  - vb
  name: OpenApiHiddenAttribute
  nameWithType: OpenApiHiddenAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute
  type: Class
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nAttribute to denote that something is hidden.\n"
  syntax:
    content: 'public sealed class OpenApiHiddenAttribute : Attribute'
    content.vb: >-
      Public NotInheritable Class OpenApiHiddenAttribute
          Inherits Attribute
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute.#ctor
  commentId: M:CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute.#ctor
  id: '#ctor'
  parent: CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute
  langs:
  - csharp
  - vb
  name: OpenApiHiddenAttribute()
  nameWithType: OpenApiHiddenAttribute.OpenApiHiddenAttribute()
  fullName: CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute.OpenApiHiddenAttribute()
  type: Constructor
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  syntax:
    content: public OpenApiHiddenAttribute()
    content.vb: Public Sub New
  overload: CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.OpenApi.Attributes
  commentId: N:CoreWCF.OpenApi.Attributes
  isExternal: true
  name: CoreWCF.OpenApi.Attributes
  nameWithType: CoreWCF.OpenApi.Attributes
  fullName: CoreWCF.OpenApi.Attributes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute.#ctor*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute.#ctor
  isExternal: true
  name: OpenApiHiddenAttribute
  nameWithType: OpenApiHiddenAttribute.OpenApiHiddenAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute.OpenApiHiddenAttribute
