### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.MetadataServiceCollectionExtensions
  commentId: T:CoreWCF.Configuration.MetadataServiceCollectionExtensions
  id: MetadataServiceCollectionExtensions
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.MetadataServiceCollectionExtensions.AddServiceModelMetadata(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  langs:
  - csharp
  - vb
  name: MetadataServiceCollectionExtensions
  nameWithType: MetadataServiceCollectionExtensions
  fullName: CoreWCF.Configuration.MetadataServiceCollectionExtensions
  type: Class
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public static class MetadataServiceCollectionExtensions : Object'
    content.vb: >-
      Public Module MetadataServiceCollectionExtensions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: CoreWCF.Configuration.MetadataServiceCollectionExtensions.AddServiceModelMetadata(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  commentId: M:CoreWCF.Configuration.MetadataServiceCollectionExtensions.AddServiceModelMetadata(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  id: AddServiceModelMetadata(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  isExtensionMethod: true
  parent: CoreWCF.Configuration.MetadataServiceCollectionExtensions
  langs:
  - csharp
  - vb
  name: AddServiceModelMetadata(IServiceCollection)
  nameWithType: MetadataServiceCollectionExtensions.AddServiceModelMetadata(IServiceCollection)
  fullName: CoreWCF.Configuration.MetadataServiceCollectionExtensions.AddServiceModelMetadata(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public static IServiceCollection AddServiceModelMetadata(this IServiceCollection services)
    parameters:
    - id: services
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
    return:
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function AddServiceModelMetadata(services As IServiceCollection) As IServiceCollection
  overload: CoreWCF.Configuration.MetadataServiceCollectionExtensions.AddServiceModelMetadata*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.MetadataServiceCollectionExtensions.AddServiceModelMetadata*
  commentId: Overload:CoreWCF.Configuration.MetadataServiceCollectionExtensions.AddServiceModelMetadata
  isExternal: true
  name: AddServiceModelMetadata
  nameWithType: MetadataServiceCollectionExtensions.AddServiceModelMetadata
  fullName: CoreWCF.Configuration.MetadataServiceCollectionExtensions.AddServiceModelMetadata
- uid: Microsoft.Extensions.DependencyInjection.IServiceCollection
  isExternal: true
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: Microsoft.Extensions.DependencyInjection.IServiceCollection
