### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.TcpConnectionPoolSettingsElement
  commentId: T:CoreWCF.Configuration.TcpConnectionPoolSettingsElement
  id: TcpConnectionPoolSettingsElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.TcpConnectionPoolSettingsElement.#ctor
  - CoreWCF.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  - CoreWCF.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  langs:
  - csharp
  - vb
  name: TcpConnectionPoolSettingsElement
  nameWithType: TcpConnectionPoolSettingsElement
  fullName: CoreWCF.Configuration.TcpConnectionPoolSettingsElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a configuration element that specifies additional connection pool settings for a TCP transport. This class cannot be inherited.
  remarks: To be added.
  syntax:
    content: 'public sealed class TcpConnectionPoolSettingsElement : ServiceModelConfigurationElement'
    content.vb: >-
      Public NotInheritable Class TcpConnectionPoolSettingsElement
          Inherits ServiceModelConfigurationElement
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElement
  inheritedMembers:
  - CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.#ctor
  commentId: M:CoreWCF.Configuration.TcpConnectionPoolSettingsElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  - vb
  name: TcpConnectionPoolSettingsElement()
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  fullName: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public TcpConnectionPoolSettingsElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  commentId: P:CoreWCF.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  id: IdleTimeout
  parent: CoreWCF.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  - vb
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
  fullName: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Property IdleTimeout As TimeSpan
  overload: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  commentId: P:CoreWCF.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: CoreWCF.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  - vb
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxOutboundConnectionsPerEndpoint As Integer
  overload: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: CoreWCF.Configuration.ServiceModelConfigurationElement
  definition: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  isExternal: true
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.TcpConnectionPoolSettingsElement.#ctor
  isExternal: true
  name: TcpConnectionPoolSettingsElement
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement
  fullName: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement
- uid: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout*
  commentId: Overload:CoreWCF.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  isExternal: true
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
  fullName: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
- uid: System.TimeSpan
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  commentId: Overload:CoreWCF.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  isExternal: true
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: CoreWCF.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
