### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.IXmlConfigEndpoint
  commentId: T:CoreWCF.Configuration.IXmlConfigEndpoint
  id: IXmlConfigEndpoint
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.IXmlConfigEndpoint.Address
  - CoreWCF.Configuration.IXmlConfigEndpoint.Binding
  - CoreWCF.Configuration.IXmlConfigEndpoint.Contract
  - CoreWCF.Configuration.IXmlConfigEndpoint.Service
  langs:
  - csharp
  - vb
  name: IXmlConfigEndpoint
  nameWithType: IXmlConfigEndpoint
  fullName: CoreWCF.Configuration.IXmlConfigEndpoint
  type: Interface
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public interface IXmlConfigEndpoint
    content.vb: Public Interface IXmlConfigEndpoint
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: CoreWCF.Configuration.IXmlConfigEndpoint.Address
  commentId: P:CoreWCF.Configuration.IXmlConfigEndpoint.Address
  id: Address
  parent: CoreWCF.Configuration.IXmlConfigEndpoint
  langs:
  - csharp
  - vb
  name: Address
  nameWithType: IXmlConfigEndpoint.Address
  fullName: CoreWCF.Configuration.IXmlConfigEndpoint.Address
  type: Property
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: Uri Address { get; }
    parameters: []
    return:
      type: System.Uri
    content.vb: ReadOnly Property Address As Uri
  overload: CoreWCF.Configuration.IXmlConfigEndpoint.Address*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: CoreWCF.Configuration.IXmlConfigEndpoint.Binding
  commentId: P:CoreWCF.Configuration.IXmlConfigEndpoint.Binding
  id: Binding
  parent: CoreWCF.Configuration.IXmlConfigEndpoint
  langs:
  - csharp
  - vb
  name: Binding
  nameWithType: IXmlConfigEndpoint.Binding
  fullName: CoreWCF.Configuration.IXmlConfigEndpoint.Binding
  type: Property
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: Binding Binding { get; }
    parameters: []
    return:
      type: CoreWCF.Channels.Binding
    content.vb: ReadOnly Property Binding As Binding
  overload: CoreWCF.Configuration.IXmlConfigEndpoint.Binding*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: CoreWCF.Configuration.IXmlConfigEndpoint.Contract
  commentId: P:CoreWCF.Configuration.IXmlConfigEndpoint.Contract
  id: Contract
  parent: CoreWCF.Configuration.IXmlConfigEndpoint
  langs:
  - csharp
  - vb
  name: Contract
  nameWithType: IXmlConfigEndpoint.Contract
  fullName: CoreWCF.Configuration.IXmlConfigEndpoint.Contract
  type: Property
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: Type Contract { get; }
    parameters: []
    return:
      type: System.Type
    content.vb: ReadOnly Property Contract As Type
  overload: CoreWCF.Configuration.IXmlConfigEndpoint.Contract*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: CoreWCF.Configuration.IXmlConfigEndpoint.Service
  commentId: P:CoreWCF.Configuration.IXmlConfigEndpoint.Service
  id: Service
  parent: CoreWCF.Configuration.IXmlConfigEndpoint
  langs:
  - csharp
  - vb
  name: Service
  nameWithType: IXmlConfigEndpoint.Service
  fullName: CoreWCF.Configuration.IXmlConfigEndpoint.Service
  type: Property
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: Type Service { get; }
    parameters: []
    return:
      type: System.Type
    content.vb: ReadOnly Property Service As Type
  overload: CoreWCF.Configuration.IXmlConfigEndpoint.Service*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: CoreWCF.Configuration.IXmlConfigEndpoint.Address*
  commentId: Overload:CoreWCF.Configuration.IXmlConfigEndpoint.Address
  isExternal: true
  name: Address
  nameWithType: IXmlConfigEndpoint.Address
  fullName: CoreWCF.Configuration.IXmlConfigEndpoint.Address
- uid: System.Uri
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: CoreWCF.Configuration.IXmlConfigEndpoint.Binding*
  commentId: Overload:CoreWCF.Configuration.IXmlConfigEndpoint.Binding
  isExternal: true
  name: Binding
  nameWithType: IXmlConfigEndpoint.Binding
  fullName: CoreWCF.Configuration.IXmlConfigEndpoint.Binding
- uid: CoreWCF.Channels.Binding
  commentId: T:CoreWCF.Channels.Binding
  parent: CoreWCF.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: CoreWCF.Channels.Binding
- uid: CoreWCF.Channels
  commentId: N:CoreWCF.Channels
  isExternal: true
  name: CoreWCF.Channels
  nameWithType: CoreWCF.Channels
  fullName: CoreWCF.Channels
- uid: CoreWCF.Configuration.IXmlConfigEndpoint.Contract*
  commentId: Overload:CoreWCF.Configuration.IXmlConfigEndpoint.Contract
  isExternal: true
  name: Contract
  nameWithType: IXmlConfigEndpoint.Contract
  fullName: CoreWCF.Configuration.IXmlConfigEndpoint.Contract
- uid: System.Type
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: CoreWCF.Configuration.IXmlConfigEndpoint.Service*
  commentId: Overload:CoreWCF.Configuration.IXmlConfigEndpoint.Service
  isExternal: true
  name: Service
  nameWithType: IXmlConfigEndpoint.Service
  fullName: CoreWCF.Configuration.IXmlConfigEndpoint.Service
