### YamlMime:ManagedReference
items:
- uid: CoreWCF.IdentityModel.Configuration
  commentId: N:CoreWCF.IdentityModel.Configuration
  id: CoreWCF.IdentityModel.Configuration
  children:
  - CoreWCF.IdentityModel.Configuration.IdentityConfiguration
  - CoreWCF.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  - vb
  name: CoreWCF.IdentityModel.Configuration
  nameWithType: CoreWCF.IdentityModel.Configuration
  fullName: CoreWCF.IdentityModel.Configuration
  type: Namespace
  assemblies:
  - CoreWCF.Primitives
references:
- uid: CoreWCF.IdentityModel.Configuration.IdentityConfiguration
  commentId: T:CoreWCF.IdentityModel.Configuration.IdentityConfiguration
  parent: CoreWCF.IdentityModel.Configuration
  isExternal: true
  name: IdentityConfiguration
  nameWithType: IdentityConfiguration
  fullName: CoreWCF.IdentityModel.Configuration.IdentityConfiguration
- uid: CoreWCF.IdentityModel.Configuration.IdentityModelCaches
  commentId: T:CoreWCF.IdentityModel.Configuration.IdentityModelCaches
  parent: CoreWCF.IdentityModel.Configuration
  isExternal: true
  name: IdentityModelCaches
  nameWithType: IdentityModelCaches
  fullName: CoreWCF.IdentityModel.Configuration.IdentityModelCaches
- uid: CoreWCF.IdentityModel.Configuration
  commentId: N:CoreWCF.IdentityModel.Configuration
  isExternal: true
  name: CoreWCF.IdentityModel.Configuration
  nameWithType: CoreWCF.IdentityModel.Configuration
  fullName: CoreWCF.IdentityModel.Configuration
