### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ClaimTypeElementCollection
  commentId: T:CoreWCF.Configuration.ClaimTypeElementCollection
  id: ClaimTypeElementCollection
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ClaimTypeElementCollection.#ctor
  - CoreWCF.Configuration.ClaimTypeElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  - vb
  name: ClaimTypeElementCollection
  nameWithType: ClaimTypeElementCollection
  fullName: CoreWCF.Configuration.ClaimTypeElementCollection
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: "Represents a collection of <xref:CoreWCF.Configuration.ClaimTypeElement> instances. This class cannot be inherited."
  remarks: To be added.
  syntax:
    content: 'public sealed class ClaimTypeElementCollection : ServiceModelConfigurationElementCollection<ClaimTypeElement>'
    content.vb: >-
      Public NotInheritable Class ClaimTypeElementCollection
          Inherits ServiceModelConfigurationElementCollection(Of ClaimTypeElement)
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.ClaimTypeElement}
  inheritedMembers:
  - CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.ClaimTypeElement}.CreateNewElement
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.ClaimTypeElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  commentId: M:CoreWCF.Configuration.ClaimTypeElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: CoreWCF.Configuration.ClaimTypeElementCollection
  langs:
  - csharp
  - vb
  name: GetElementKey(ConfigurationElement)
  nameWithType: ClaimTypeElementCollection.GetElementKey(ConfigurationElement)
  fullName: CoreWCF.Configuration.ClaimTypeElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Gets the element key for a specified configuration element when overridden in a derived class.
  syntax:
    content: protected override object GetElementKey(ConfigurationElement element)
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "The <xref:System.Configuration.ConfigurationElement> to return the key for."
    return:
      type: System.Object
      description: "An <xref:System.Object> that acts as the key for the specified <xref:System.Configuration.ConfigurationElement>."
    content.vb: Protected Overrides Function GetElementKey(element As ConfigurationElement) As Object
  overload: CoreWCF.Configuration.ClaimTypeElementCollection.GetElementKey*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: CoreWCF.Configuration.ClaimTypeElementCollection.#ctor
  commentId: M:CoreWCF.Configuration.ClaimTypeElementCollection.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ClaimTypeElementCollection
  langs:
  - csharp
  - vb
  name: ClaimTypeElementCollection()
  nameWithType: ClaimTypeElementCollection.ClaimTypeElementCollection()
  fullName: CoreWCF.Configuration.ClaimTypeElementCollection.ClaimTypeElementCollection()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: "Initializes a new instance of the <xref:CoreWCF.Configuration.ClaimTypeElementCollection> class."
  syntax:
    content: public ClaimTypeElementCollection()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.ClaimTypeElementCollection.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.ClaimTypeElement}
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.ClaimTypeElement}
  parent: CoreWCF.Configuration
  definition: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  name: ServiceModelConfigurationElementCollection<ClaimTypeElement>
  nameWithType: ServiceModelConfigurationElementCollection<ClaimTypeElement>
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<CoreWCF.Configuration.ClaimTypeElement>
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of ClaimTypeElement)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of CoreWCF.Configuration.ClaimTypeElement)
  name.vb: ServiceModelConfigurationElementCollection(Of ClaimTypeElement)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.Configuration.ClaimTypeElement
    name: ClaimTypeElement
    nameWithType: ClaimTypeElement
    fullName: CoreWCF.Configuration.ClaimTypeElement
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.Configuration.ClaimTypeElement
    name: ClaimTypeElement
    nameWithType: ClaimTypeElement
    fullName: CoreWCF.Configuration.ClaimTypeElement
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.ClaimTypeElement}.CreateNewElement
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.ClaimTypeElement}.CreateNewElement
  parent: CoreWCF.Configuration.ServiceModelConfigurationElementCollection{CoreWCF.Configuration.ClaimTypeElement}
  definition: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  name: CreateNewElement()
  nameWithType: ServiceModelConfigurationElementCollection<ClaimTypeElement>.CreateNewElement()
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<CoreWCF.Configuration.ClaimTypeElement>.CreateNewElement()
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of ClaimTypeElement).CreateNewElement()
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of CoreWCF.Configuration.ClaimTypeElement).CreateNewElement()
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection<ClaimTypeElement>.CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<CoreWCF.Configuration.ClaimTypeElement>.CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection(Of ClaimTypeElement).CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of CoreWCF.Configuration.ClaimTypeElement).CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  isExternal: true
  name: ServiceModelConfigurationElementCollection<TConfigurationElementType>
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  name.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TConfigurationElementType
    nameWithType: TConfigurationElementType
    fullName: TConfigurationElementType
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TConfigurationElementType
    nameWithType: TConfigurationElementType
    fullName: TConfigurationElementType
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  isExternal: true
  name: CreateNewElement()
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement()
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement()
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement()
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement()
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ClaimTypeElementCollection.GetElementKey*
  commentId: Overload:CoreWCF.Configuration.ClaimTypeElementCollection.GetElementKey
  isExternal: true
  name: GetElementKey
  nameWithType: ClaimTypeElementCollection.GetElementKey
  fullName: CoreWCF.Configuration.ClaimTypeElementCollection.GetElementKey
- uid: System.Configuration.ConfigurationElement
  isExternal: true
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: CoreWCF.Configuration.ClaimTypeElementCollection.#ctor*
  commentId: Overload:CoreWCF.Configuration.ClaimTypeElementCollection.#ctor
  isExternal: true
  name: ClaimTypeElementCollection
  nameWithType: ClaimTypeElementCollection.ClaimTypeElementCollection
  fullName: CoreWCF.Configuration.ClaimTypeElementCollection.ClaimTypeElementCollection
