### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceElement
  commentId: T:CoreWCF.Configuration.ServiceElement
  id: ServiceElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceElement.#ctor
  - CoreWCF.Configuration.ServiceElement.BehaviorConfiguration
  - CoreWCF.Configuration.ServiceElement.Endpoints
  - CoreWCF.Configuration.ServiceElement.Name
  langs:
  - csharp
  - vb
  name: ServiceElement
  nameWithType: ServiceElement
  fullName: CoreWCF.Configuration.ServiceElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents an XML element that contains the settings for a Windows Communication Foundation (WCF) service, as well as endpoints that expose the service. This class cannot be inherited.
  remarks: To be added.
  syntax:
    content: 'public class ServiceElement : ConfigurationElement'
    content.vb: >-
      Public Class ServiceElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.ServiceElement.#ctor
  commentId: M:CoreWCF.Configuration.ServiceElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ServiceElement
  langs:
  - csharp
  - vb
  name: ServiceElement()
  nameWithType: ServiceElement.ServiceElement()
  fullName: CoreWCF.Configuration.ServiceElement.ServiceElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.ServiceElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceElement.BehaviorConfiguration
  commentId: P:CoreWCF.Configuration.ServiceElement.BehaviorConfiguration
  id: BehaviorConfiguration
  parent: CoreWCF.Configuration.ServiceElement
  langs:
  - csharp
  - vb
  name: BehaviorConfiguration
  nameWithType: ServiceElement.BehaviorConfiguration
  fullName: CoreWCF.Configuration.ServiceElement.BehaviorConfiguration
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string BehaviorConfiguration { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BehaviorConfiguration As String
  overload: CoreWCF.Configuration.ServiceElement.BehaviorConfiguration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceElement.Endpoints
  commentId: P:CoreWCF.Configuration.ServiceElement.Endpoints
  id: Endpoints
  parent: CoreWCF.Configuration.ServiceElement
  langs:
  - csharp
  - vb
  name: Endpoints
  nameWithType: ServiceElement.Endpoints
  fullName: CoreWCF.Configuration.ServiceElement.Endpoints
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceEndpointElementCollection Endpoints { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.ServiceEndpointElementCollection
    content.vb: Public ReadOnly Property Endpoints As ServiceEndpointElementCollection
  overload: CoreWCF.Configuration.ServiceElement.Endpoints*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: CoreWCF.Configuration.ServiceElement.Name
  commentId: P:CoreWCF.Configuration.ServiceElement.Name
  id: Name
  parent: CoreWCF.Configuration.ServiceElement
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ServiceElement.Name
  fullName: CoreWCF.Configuration.ServiceElement.Name
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: CoreWCF.Configuration.ServiceElement.Name*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.ServiceElement.#ctor
  isExternal: true
  name: ServiceElement
  nameWithType: ServiceElement.ServiceElement
  fullName: CoreWCF.Configuration.ServiceElement.ServiceElement
- uid: CoreWCF.Configuration.ServiceElement.BehaviorConfiguration*
  commentId: Overload:CoreWCF.Configuration.ServiceElement.BehaviorConfiguration
  isExternal: true
  name: BehaviorConfiguration
  nameWithType: ServiceElement.BehaviorConfiguration
  fullName: CoreWCF.Configuration.ServiceElement.BehaviorConfiguration
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.Configuration.ServiceElement.Endpoints*
  commentId: Overload:CoreWCF.Configuration.ServiceElement.Endpoints
  isExternal: true
  name: Endpoints
  nameWithType: ServiceElement.Endpoints
  fullName: CoreWCF.Configuration.ServiceElement.Endpoints
- uid: CoreWCF.Configuration.ServiceEndpointElementCollection
  commentId: T:CoreWCF.Configuration.ServiceEndpointElementCollection
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceEndpointElementCollection
  nameWithType: ServiceEndpointElementCollection
  fullName: CoreWCF.Configuration.ServiceEndpointElementCollection
- uid: CoreWCF.Configuration.ServiceElement.Name*
  commentId: Overload:CoreWCF.Configuration.ServiceElement.Name
  isExternal: true
  name: Name
  nameWithType: ServiceElement.Name
  fullName: CoreWCF.Configuration.ServiceElement.Name
