### YamlMime:ManagedReference
items:
- uid: CoreWCF.IdentityModel.Configuration.IdentityModelCaches
  commentId: T:CoreWCF.IdentityModel.Configuration.IdentityModelCaches
  id: IdentityModelCaches
  parent: CoreWCF.IdentityModel.Configuration
  children:
  - CoreWCF.IdentityModel.Configuration.IdentityModelCaches.#ctor
  - CoreWCF.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  - CoreWCF.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  langs:
  - csharp
  - vb
  name: IdentityModelCaches
  nameWithType: IdentityModelCaches
  fullName: CoreWCF.IdentityModel.Configuration.IdentityModelCaches
  type: Class
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.IdentityModel.Configuration
  summary: "\nDefines caches supported by IdentityModel for TokenReplay and SecuritySessionTokens\n"
  syntax:
    content: 'public sealed class IdentityModelCaches : Object'
    content.vb: >-
      Public NotInheritable Class IdentityModelCaches
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.#ctor
  commentId: M:CoreWCF.IdentityModel.Configuration.IdentityModelCaches.#ctor
  id: '#ctor'
  parent: CoreWCF.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  - vb
  name: IdentityModelCaches()
  nameWithType: IdentityModelCaches.IdentityModelCaches()
  fullName: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.IdentityModelCaches()
  type: Constructor
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.IdentityModel.Configuration
  syntax:
    content: public IdentityModelCaches()
    content.vb: Public Sub New
  overload: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  commentId: P:CoreWCF.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  id: TokenReplayCache
  parent: CoreWCF.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  - vb
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
  fullName: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  type: Property
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.IdentityModel.Configuration
  summary: "\nGets or sets the TokenReplayCache that is used to determine replayed token.\n"
  syntax:
    content: public TokenReplayCache TokenReplayCache { get; set; }
    parameters: []
    return:
      type: CoreWCF.IdentityModel.Tokens.TokenReplayCache
    content.vb: Public Property TokenReplayCache As TokenReplayCache
  overload: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  commentId: P:CoreWCF.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  id: SessionSecurityTokenCache
  parent: CoreWCF.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  - vb
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
  fullName: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  type: Property
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.IdentityModel.Configuration
  summary: "\nGets or sets the SessionSecurityTokenCache that is used to cache the <xref href=\"CoreWCF.IdentityModel.Tokens.SessionSecurityToken\" data-throw-if-not-resolved=\"false\"></xref>"
  syntax:
    content: public SessionSecurityTokenCache SessionSecurityTokenCache { get; set; }
    parameters: []
    return:
      type: CoreWCF.IdentityModel.Tokens.SessionSecurityTokenCache
    content.vb: Public Property SessionSecurityTokenCache As SessionSecurityTokenCache
  overload: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.IdentityModel.Configuration
  commentId: N:CoreWCF.IdentityModel.Configuration
  isExternal: true
  name: CoreWCF.IdentityModel.Configuration
  nameWithType: CoreWCF.IdentityModel.Configuration
  fullName: CoreWCF.IdentityModel.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.#ctor*
  commentId: Overload:CoreWCF.IdentityModel.Configuration.IdentityModelCaches.#ctor
  isExternal: true
  name: IdentityModelCaches
  nameWithType: IdentityModelCaches.IdentityModelCaches
  fullName: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.IdentityModelCaches
- uid: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache*
  commentId: Overload:CoreWCF.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  isExternal: true
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
  fullName: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
- uid: CoreWCF.IdentityModel.Tokens.TokenReplayCache
  commentId: T:CoreWCF.IdentityModel.Tokens.TokenReplayCache
  parent: CoreWCF.IdentityModel.Tokens
  isExternal: true
  name: TokenReplayCache
  nameWithType: TokenReplayCache
  fullName: CoreWCF.IdentityModel.Tokens.TokenReplayCache
- uid: CoreWCF.IdentityModel.Tokens
  commentId: N:CoreWCF.IdentityModel.Tokens
  isExternal: true
  name: CoreWCF.IdentityModel.Tokens
  nameWithType: CoreWCF.IdentityModel.Tokens
  fullName: CoreWCF.IdentityModel.Tokens
- uid: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache*
  commentId: Overload:CoreWCF.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  isExternal: true
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
  fullName: CoreWCF.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
- uid: CoreWCF.IdentityModel.Tokens.SessionSecurityTokenCache
  commentId: T:CoreWCF.IdentityModel.Tokens.SessionSecurityTokenCache
  parent: CoreWCF.IdentityModel.Tokens
  isExternal: true
  name: SessionSecurityTokenCache
  nameWithType: SessionSecurityTokenCache
  fullName: CoreWCF.IdentityModel.Tokens.SessionSecurityTokenCache
