### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceEndpointElement
  commentId: T:CoreWCF.Configuration.ServiceEndpointElement
  id: ServiceEndpointElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceEndpointElement.#ctor
  - CoreWCF.Configuration.ServiceEndpointElement.Address
  - CoreWCF.Configuration.ServiceEndpointElement.BehaviorConfiguration
  - CoreWCF.Configuration.ServiceEndpointElement.Binding
  - CoreWCF.Configuration.ServiceEndpointElement.BindingConfiguration
  - CoreWCF.Configuration.ServiceEndpointElement.BindingName
  - CoreWCF.Configuration.ServiceEndpointElement.BindingNamespace
  - CoreWCF.Configuration.ServiceEndpointElement.Contract
  - CoreWCF.Configuration.ServiceEndpointElement.EndpointConfiguration
  - CoreWCF.Configuration.ServiceEndpointElement.IsSystemEndpoint
  - CoreWCF.Configuration.ServiceEndpointElement.Kind
  - CoreWCF.Configuration.ServiceEndpointElement.ListenUri
  - CoreWCF.Configuration.ServiceEndpointElement.Name
  langs:
  - csharp
  - vb
  name: ServiceEndpointElement
  nameWithType: ServiceEndpointElement
  fullName: CoreWCF.Configuration.ServiceEndpointElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a configuration element that provides settings for binding, contract, and address properties for a service endpoint, which is used to expose services. This class cannot be inherited.
  remarks: To be added.
  syntax:
    content: 'public class ServiceEndpointElement : ConfigurationElement'
    content.vb: >-
      Public Class ServiceEndpointElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.ServiceEndpointElement.#ctor
  commentId: M:CoreWCF.Configuration.ServiceEndpointElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: ServiceEndpointElement()
  nameWithType: ServiceEndpointElement.ServiceEndpointElement()
  fullName: CoreWCF.Configuration.ServiceEndpointElement.ServiceEndpointElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceEndpointElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.ServiceEndpointElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpointElement.Address
  commentId: P:CoreWCF.Configuration.ServiceEndpointElement.Address
  id: Address
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: Address
  nameWithType: ServiceEndpointElement.Address
  fullName: CoreWCF.Configuration.ServiceEndpointElement.Address
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public Uri Address { get; set; }
    parameters: []
    return:
      type: System.Uri
    content.vb: Public Property Address As Uri
  overload: CoreWCF.Configuration.ServiceEndpointElement.Address*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpointElement.BehaviorConfiguration
  commentId: P:CoreWCF.Configuration.ServiceEndpointElement.BehaviorConfiguration
  id: BehaviorConfiguration
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: BehaviorConfiguration
  nameWithType: ServiceEndpointElement.BehaviorConfiguration
  fullName: CoreWCF.Configuration.ServiceEndpointElement.BehaviorConfiguration
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string BehaviorConfiguration { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BehaviorConfiguration As String
  overload: CoreWCF.Configuration.ServiceEndpointElement.BehaviorConfiguration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpointElement.Binding
  commentId: P:CoreWCF.Configuration.ServiceEndpointElement.Binding
  id: Binding
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: Binding
  nameWithType: ServiceEndpointElement.Binding
  fullName: CoreWCF.Configuration.ServiceEndpointElement.Binding
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string Binding { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Binding As String
  overload: CoreWCF.Configuration.ServiceEndpointElement.Binding*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpointElement.BindingConfiguration
  commentId: P:CoreWCF.Configuration.ServiceEndpointElement.BindingConfiguration
  id: BindingConfiguration
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: BindingConfiguration
  nameWithType: ServiceEndpointElement.BindingConfiguration
  fullName: CoreWCF.Configuration.ServiceEndpointElement.BindingConfiguration
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string BindingConfiguration { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BindingConfiguration As String
  overload: CoreWCF.Configuration.ServiceEndpointElement.BindingConfiguration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpointElement.Name
  commentId: P:CoreWCF.Configuration.ServiceEndpointElement.Name
  id: Name
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ServiceEndpointElement.Name
  fullName: CoreWCF.Configuration.ServiceEndpointElement.Name
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: CoreWCF.Configuration.ServiceEndpointElement.Name*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpointElement.BindingName
  commentId: P:CoreWCF.Configuration.ServiceEndpointElement.BindingName
  id: BindingName
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: BindingName
  nameWithType: ServiceEndpointElement.BindingName
  fullName: CoreWCF.Configuration.ServiceEndpointElement.BindingName
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string BindingName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BindingName As String
  overload: CoreWCF.Configuration.ServiceEndpointElement.BindingName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpointElement.BindingNamespace
  commentId: P:CoreWCF.Configuration.ServiceEndpointElement.BindingNamespace
  id: BindingNamespace
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: BindingNamespace
  nameWithType: ServiceEndpointElement.BindingNamespace
  fullName: CoreWCF.Configuration.ServiceEndpointElement.BindingNamespace
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string BindingNamespace { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BindingNamespace As String
  overload: CoreWCF.Configuration.ServiceEndpointElement.BindingNamespace*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpointElement.Contract
  commentId: P:CoreWCF.Configuration.ServiceEndpointElement.Contract
  id: Contract
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: Contract
  nameWithType: ServiceEndpointElement.Contract
  fullName: CoreWCF.Configuration.ServiceEndpointElement.Contract
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string Contract { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Contract As String
  overload: CoreWCF.Configuration.ServiceEndpointElement.Contract*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpointElement.ListenUri
  commentId: P:CoreWCF.Configuration.ServiceEndpointElement.ListenUri
  id: ListenUri
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: ListenUri
  nameWithType: ServiceEndpointElement.ListenUri
  fullName: CoreWCF.Configuration.ServiceEndpointElement.ListenUri
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public Uri ListenUri { get; set; }
    parameters: []
    return:
      type: System.Uri
    content.vb: Public Property ListenUri As Uri
  overload: CoreWCF.Configuration.ServiceEndpointElement.ListenUri*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpointElement.IsSystemEndpoint
  commentId: P:CoreWCF.Configuration.ServiceEndpointElement.IsSystemEndpoint
  id: IsSystemEndpoint
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: IsSystemEndpoint
  nameWithType: ServiceEndpointElement.IsSystemEndpoint
  fullName: CoreWCF.Configuration.ServiceEndpointElement.IsSystemEndpoint
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public bool IsSystemEndpoint { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsSystemEndpoint As Boolean
  overload: CoreWCF.Configuration.ServiceEndpointElement.IsSystemEndpoint*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpointElement.Kind
  commentId: P:CoreWCF.Configuration.ServiceEndpointElement.Kind
  id: Kind
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: Kind
  nameWithType: ServiceEndpointElement.Kind
  fullName: CoreWCF.Configuration.ServiceEndpointElement.Kind
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string Kind { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Kind As String
  overload: CoreWCF.Configuration.ServiceEndpointElement.Kind*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpointElement.EndpointConfiguration
  commentId: P:CoreWCF.Configuration.ServiceEndpointElement.EndpointConfiguration
  id: EndpointConfiguration
  parent: CoreWCF.Configuration.ServiceEndpointElement
  langs:
  - csharp
  - vb
  name: EndpointConfiguration
  nameWithType: ServiceEndpointElement.EndpointConfiguration
  fullName: CoreWCF.Configuration.ServiceEndpointElement.EndpointConfiguration
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string EndpointConfiguration { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property EndpointConfiguration As String
  overload: CoreWCF.Configuration.ServiceEndpointElement.EndpointConfiguration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceEndpointElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.#ctor
  isExternal: true
  name: ServiceEndpointElement
  nameWithType: ServiceEndpointElement.ServiceEndpointElement
  fullName: CoreWCF.Configuration.ServiceEndpointElement.ServiceEndpointElement
- uid: CoreWCF.Configuration.ServiceEndpointElement.Address*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.Address
  isExternal: true
  name: Address
  nameWithType: ServiceEndpointElement.Address
  fullName: CoreWCF.Configuration.ServiceEndpointElement.Address
- uid: System.Uri
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: CoreWCF.Configuration.ServiceEndpointElement.BehaviorConfiguration*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.BehaviorConfiguration
  isExternal: true
  name: BehaviorConfiguration
  nameWithType: ServiceEndpointElement.BehaviorConfiguration
  fullName: CoreWCF.Configuration.ServiceEndpointElement.BehaviorConfiguration
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.Configuration.ServiceEndpointElement.Binding*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.Binding
  isExternal: true
  name: Binding
  nameWithType: ServiceEndpointElement.Binding
  fullName: CoreWCF.Configuration.ServiceEndpointElement.Binding
- uid: CoreWCF.Configuration.ServiceEndpointElement.BindingConfiguration*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.BindingConfiguration
  isExternal: true
  name: BindingConfiguration
  nameWithType: ServiceEndpointElement.BindingConfiguration
  fullName: CoreWCF.Configuration.ServiceEndpointElement.BindingConfiguration
- uid: CoreWCF.Configuration.ServiceEndpointElement.Name*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.Name
  isExternal: true
  name: Name
  nameWithType: ServiceEndpointElement.Name
  fullName: CoreWCF.Configuration.ServiceEndpointElement.Name
- uid: CoreWCF.Configuration.ServiceEndpointElement.BindingName*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.BindingName
  isExternal: true
  name: BindingName
  nameWithType: ServiceEndpointElement.BindingName
  fullName: CoreWCF.Configuration.ServiceEndpointElement.BindingName
- uid: CoreWCF.Configuration.ServiceEndpointElement.BindingNamespace*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.BindingNamespace
  isExternal: true
  name: BindingNamespace
  nameWithType: ServiceEndpointElement.BindingNamespace
  fullName: CoreWCF.Configuration.ServiceEndpointElement.BindingNamespace
- uid: CoreWCF.Configuration.ServiceEndpointElement.Contract*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.Contract
  isExternal: true
  name: Contract
  nameWithType: ServiceEndpointElement.Contract
  fullName: CoreWCF.Configuration.ServiceEndpointElement.Contract
- uid: CoreWCF.Configuration.ServiceEndpointElement.ListenUri*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.ListenUri
  isExternal: true
  name: ListenUri
  nameWithType: ServiceEndpointElement.ListenUri
  fullName: CoreWCF.Configuration.ServiceEndpointElement.ListenUri
- uid: CoreWCF.Configuration.ServiceEndpointElement.IsSystemEndpoint*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.IsSystemEndpoint
  isExternal: true
  name: IsSystemEndpoint
  nameWithType: ServiceEndpointElement.IsSystemEndpoint
  fullName: CoreWCF.Configuration.ServiceEndpointElement.IsSystemEndpoint
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: CoreWCF.Configuration.ServiceEndpointElement.Kind*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.Kind
  isExternal: true
  name: Kind
  nameWithType: ServiceEndpointElement.Kind
  fullName: CoreWCF.Configuration.ServiceEndpointElement.Kind
- uid: CoreWCF.Configuration.ServiceEndpointElement.EndpointConfiguration*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElement.EndpointConfiguration
  isExternal: true
  name: EndpointConfiguration
  nameWithType: ServiceEndpointElement.EndpointConfiguration
  fullName: CoreWCF.Configuration.ServiceEndpointElement.EndpointConfiguration
