### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceModelServiceCollectionExtensions
  commentId: T:CoreWCF.Configuration.ServiceModelServiceCollectionExtensions
  id: ServiceModelServiceCollectionExtensions
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceModelServiceCollectionExtensions.AddServiceModelServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  langs:
  - csharp
  - vb
  name: ServiceModelServiceCollectionExtensions
  nameWithType: ServiceModelServiceCollectionExtensions
  fullName: CoreWCF.Configuration.ServiceModelServiceCollectionExtensions
  type: Class
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public static class ServiceModelServiceCollectionExtensions : Object'
    content.vb: >-
      Public Module ServiceModelServiceCollectionExtensions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: CoreWCF.Configuration.ServiceModelServiceCollectionExtensions.AddServiceModelServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  commentId: M:CoreWCF.Configuration.ServiceModelServiceCollectionExtensions.AddServiceModelServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  id: AddServiceModelServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  isExtensionMethod: true
  parent: CoreWCF.Configuration.ServiceModelServiceCollectionExtensions
  langs:
  - csharp
  - vb
  name: AddServiceModelServices(IServiceCollection)
  nameWithType: ServiceModelServiceCollectionExtensions.AddServiceModelServices(IServiceCollection)
  fullName: CoreWCF.Configuration.ServiceModelServiceCollectionExtensions.AddServiceModelServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public static IServiceCollection AddServiceModelServices(this IServiceCollection services)
    parameters:
    - id: services
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
    return:
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function AddServiceModelServices(services As IServiceCollection) As IServiceCollection
  overload: CoreWCF.Configuration.ServiceModelServiceCollectionExtensions.AddServiceModelServices*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelServiceCollectionExtensions.AddServiceModelServices*
  commentId: Overload:CoreWCF.Configuration.ServiceModelServiceCollectionExtensions.AddServiceModelServices
  isExternal: true
  name: AddServiceModelServices
  nameWithType: ServiceModelServiceCollectionExtensions.AddServiceModelServices
  fullName: CoreWCF.Configuration.ServiceModelServiceCollectionExtensions.AddServiceModelServices
- uid: Microsoft.Extensions.DependencyInjection.IServiceCollection
  isExternal: true
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: Microsoft.Extensions.DependencyInjection.IServiceCollection
