### YamlMime:ManagedReference
items:
- uid: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiTagAttribute
  id: OpenApiTagAttribute
  parent: CoreWCF.OpenApi.Attributes
  children:
  - CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.#ctor(System.String)
  - CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.Tag
  langs:
  - csharp
  - vb
  name: OpenApiTagAttribute
  nameWithType: OpenApiTagAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute
  type: Class
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nAttribute to denote a tag for a method.\n"
  syntax:
    content: 'public sealed class OpenApiTagAttribute : Attribute'
    content.vb: >-
      Public NotInheritable Class OpenApiTagAttribute
          Inherits Attribute
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.#ctor(System.String)
  commentId: M:CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute
  langs:
  - csharp
  - vb
  name: OpenApiTagAttribute(String)
  nameWithType: OpenApiTagAttribute.OpenApiTagAttribute(String)
  fullName: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.OpenApiTagAttribute(System.String)
  type: Constructor
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nConstructor.\n"
  syntax:
    content: public OpenApiTagAttribute(string tag)
    parameters:
    - id: tag
      type: System.String
      description: The tag name.
    content.vb: Public Sub New(tag As String)
  overload: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.Tag
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.Tag
  id: Tag
  parent: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute
  langs:
  - csharp
  - vb
  name: Tag
  nameWithType: OpenApiTagAttribute.Tag
  fullName: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.Tag
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nThe tag name.\n"
  syntax:
    content: public string Tag { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Tag As String
  overload: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.Tag*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: CoreWCF.OpenApi.Attributes
  commentId: N:CoreWCF.OpenApi.Attributes
  isExternal: true
  name: CoreWCF.OpenApi.Attributes
  nameWithType: CoreWCF.OpenApi.Attributes
  fullName: CoreWCF.OpenApi.Attributes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.#ctor*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.#ctor
  isExternal: true
  name: OpenApiTagAttribute
  nameWithType: OpenApiTagAttribute.OpenApiTagAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.OpenApiTagAttribute
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.Tag*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.Tag
  isExternal: true
  name: Tag
  nameWithType: OpenApiTagAttribute.Tag
  fullName: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute.Tag
