### YamlMime:ManagedReference
items:
- uid: CoreWCF.HttpTransportSecurity
  commentId: T:CoreWCF.HttpTransportSecurity
  id: HttpTransportSecurity
  parent: CoreWCF
  children:
  - CoreWCF.HttpTransportSecurity.#ctor
  - CoreWCF.HttpTransportSecurity.ClientCredentialType
  - CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy
  - CoreWCF.HttpTransportSecurity.Realm
  langs:
  - csharp
  - vb
  name: HttpTransportSecurity
  nameWithType: HttpTransportSecurity
  fullName: CoreWCF.HttpTransportSecurity
  type: Class
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  summary: Represents the transport-level security settings for the .
  remarks: "This class is used by &lt;xref:CoreWCF.WSHttpSecurity.Transport%2A> to set the transport-level security settings for a binding.  \n\n"
  syntax:
    content: 'public sealed class HttpTransportSecurity : Object'
    content.vb: >-
      Public NotInheritable Class HttpTransportSecurity
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.HttpTransportSecurity.#ctor
  commentId: M:CoreWCF.HttpTransportSecurity.#ctor
  id: '#ctor'
  parent: CoreWCF.HttpTransportSecurity
  langs:
  - csharp
  - vb
  name: HttpTransportSecurity()
  nameWithType: HttpTransportSecurity.HttpTransportSecurity()
  fullName: CoreWCF.HttpTransportSecurity.HttpTransportSecurity()
  type: Constructor
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public HttpTransportSecurity()
    content.vb: Public Sub New
  overload: CoreWCF.HttpTransportSecurity.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.HttpTransportSecurity.ClientCredentialType
  commentId: P:CoreWCF.HttpTransportSecurity.ClientCredentialType
  id: ClientCredentialType
  parent: CoreWCF.HttpTransportSecurity
  langs:
  - csharp
  - vb
  name: ClientCredentialType
  nameWithType: HttpTransportSecurity.ClientCredentialType
  fullName: CoreWCF.HttpTransportSecurity.ClientCredentialType
  type: Property
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public HttpClientCredentialType ClientCredentialType { get; set; }
    parameters: []
    return:
      type: CoreWCF.HttpClientCredentialType
    content.vb: Public Property ClientCredentialType As HttpClientCredentialType
  overload: CoreWCF.HttpTransportSecurity.ClientCredentialType*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.HttpTransportSecurity.Realm
  commentId: P:CoreWCF.HttpTransportSecurity.Realm
  id: Realm
  parent: CoreWCF.HttpTransportSecurity
  langs:
  - csharp
  - vb
  name: Realm
  nameWithType: HttpTransportSecurity.Realm
  fullName: CoreWCF.HttpTransportSecurity.Realm
  type: Property
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public string Realm { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Realm As String
  overload: CoreWCF.HttpTransportSecurity.Realm*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy
  commentId: P:CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy
  id: ExtendedProtectionPolicy
  parent: CoreWCF.HttpTransportSecurity
  langs:
  - csharp
  - vb
  name: ExtendedProtectionPolicy
  nameWithType: HttpTransportSecurity.ExtendedProtectionPolicy
  fullName: CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy
  type: Property
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public ExtendedProtectionPolicy ExtendedProtectionPolicy { get; set; }
    parameters: []
    return:
      type: System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy
    content.vb: Public Property ExtendedProtectionPolicy As ExtendedProtectionPolicy
  overload: CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF
  commentId: N:CoreWCF
  isExternal: true
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.HttpTransportSecurity.#ctor*
  commentId: Overload:CoreWCF.HttpTransportSecurity.#ctor
  isExternal: true
  name: HttpTransportSecurity
  nameWithType: HttpTransportSecurity.HttpTransportSecurity
  fullName: CoreWCF.HttpTransportSecurity.HttpTransportSecurity
- uid: CoreWCF.HttpTransportSecurity.ClientCredentialType*
  commentId: Overload:CoreWCF.HttpTransportSecurity.ClientCredentialType
  isExternal: true
  name: ClientCredentialType
  nameWithType: HttpTransportSecurity.ClientCredentialType
  fullName: CoreWCF.HttpTransportSecurity.ClientCredentialType
- uid: CoreWCF.HttpClientCredentialType
  commentId: T:CoreWCF.HttpClientCredentialType
  parent: CoreWCF
  isExternal: true
  name: HttpClientCredentialType
  nameWithType: HttpClientCredentialType
  fullName: CoreWCF.HttpClientCredentialType
- uid: CoreWCF.HttpTransportSecurity.Realm*
  commentId: Overload:CoreWCF.HttpTransportSecurity.Realm
  isExternal: true
  name: Realm
  nameWithType: HttpTransportSecurity.Realm
  fullName: CoreWCF.HttpTransportSecurity.Realm
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy*
  commentId: Overload:CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy
  isExternal: true
  name: ExtendedProtectionPolicy
  nameWithType: HttpTransportSecurity.ExtendedProtectionPolicy
  fullName: CoreWCF.HttpTransportSecurity.ExtendedProtectionPolicy
- uid: System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy
  isExternal: true
  name: ExtendedProtectionPolicy
  nameWithType: ExtendedProtectionPolicy
  fullName: System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy
