### YamlMime:ManagedReference
items:
- uid: CoreWCF.BasicHttpSecurity
  commentId: T:CoreWCF.BasicHttpSecurity
  id: BasicHttpSecurity
  parent: CoreWCF
  children:
  - CoreWCF.BasicHttpSecurity.#ctor
  - CoreWCF.BasicHttpSecurity.Message
  - CoreWCF.BasicHttpSecurity.Mode
  - CoreWCF.BasicHttpSecurity.Transport
  langs:
  - csharp
  - vb
  name: BasicHttpSecurity
  nameWithType: BasicHttpSecurity
  fullName: CoreWCF.BasicHttpSecurity
  type: Class
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  summary: Configures the security settings of a basicHttpBinding binding.
  syntax:
    content: 'public sealed class BasicHttpSecurity : Object'
    content.vb: >-
      Public NotInheritable Class BasicHttpSecurity

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.BasicHttpSecurity.#ctor
  commentId: M:CoreWCF.BasicHttpSecurity.#ctor
  id: '#ctor'
  parent: CoreWCF.BasicHttpSecurity
  langs:
  - csharp
  - vb
  name: BasicHttpSecurity()
  nameWithType: BasicHttpSecurity.BasicHttpSecurity()
  fullName: CoreWCF.BasicHttpSecurity.BasicHttpSecurity()
  type: Constructor
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  summary: "Initializes a new instance of the <xref: CoreWCF.BasicHttpSecurity> class."
  syntax:
    content: public BasicHttpSecurity()
    content.vb: Public Sub New
  overload: CoreWCF.BasicHttpSecurity.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.BasicHttpSecurity.Mode
  commentId: P:CoreWCF.BasicHttpSecurity.Mode
  id: Mode
  parent: CoreWCF.BasicHttpSecurity
  langs:
  - csharp
  - vb
  name: Mode
  nameWithType: BasicHttpSecurity.Mode
  fullName: CoreWCF.BasicHttpSecurity.Mode
  type: Property
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  summary: Gets or sets the security mode for a basicHttpBinding binding.
  syntax:
    content: public BasicHttpSecurityMode Mode { get; set; }
    parameters: []
    return:
      type: CoreWCF.Channels.BasicHttpSecurityMode
      description: "A value in the BasicHttpSecurityMode enumeration. The default value for this property is None."
    content.vb: Public Property Mode As BasicHttpSecurityMode
  overload: CoreWCF.BasicHttpSecurity.Mode*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  Exceptions: ""
  remarks: "The value of this property affects which settings in <xref:CoreWCF.BasicHttpSecurity.Transport> or <xref:CoreWCF.BasicHttpSecurity.Message> become effective."
- uid: CoreWCF.BasicHttpSecurity.Transport
  commentId: P:CoreWCF.BasicHttpSecurity.Transport
  id: Transport
  parent: CoreWCF.BasicHttpSecurity
  langs:
  - csharp
  - vb
  name: Transport
  nameWithType: BasicHttpSecurity.Transport
  fullName: CoreWCF.BasicHttpSecurity.Transport
  type: Property
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  summary: Gets the transport-level security settings for a basicHttpBinding binding.
  syntax:
    content: public HttpTransportSecurity Transport { get; set; }
    parameters: []
    return:
      type: CoreWCF.HttpTransportSecurity
      description: "The transport-level security settings for a basicHttpBinding binding."
    content.vb: Public Property Transport As HttpTransportSecurity
  overload: CoreWCF.BasicHttpSecurity.Transport*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  remarks: "The <xref:CoreWCF.HttpTransportSecurity> object returned by this property contains properties that control authentication parameters for the HTTP transport."
- uid: CoreWCF.BasicHttpSecurity.Message
  commentId: P:CoreWCF.BasicHttpSecurity.Message
  id: Message
  parent: CoreWCF.BasicHttpSecurity
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: BasicHttpSecurity.Message
  fullName: CoreWCF.BasicHttpSecurity.Message
  type: Property
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  summary: Gets the message-level security settings for a basicHttpBinding binding.
  syntax:
    content: public BasicHttpMessageSecurity Message { get; set; }
    parameters: []
    return:
      type: CoreWCF.BasicHttpMessageSecurity
      description: "A <xref: CoreWCF.BasicHttpMessageSecurity>, which represents the message-level security settings for this binding."
    content.vb: Public Property Message As BasicHttpMessageSecurity
  overload: CoreWCF.BasicHttpSecurity.Message*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  remarks: "The default security settings are: a <xref: CoreWCF.BasicHttpMessageSecurity.ClientCredentialType> of <xref: CoreWCF.BasicHttpMessageCredentialType.UserName>; and an <xref: CoreWCF.BasicHttpMessageSecurity.AlgorithmSuite> of <xref:CoreWCF.Security.SecurityAlgorithmSuite.Basic256>."
references:
- uid: CoreWCF
  commentId: N:CoreWCF
  isExternal: true
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.BasicHttpSecurity.#ctor*
  commentId: Overload:CoreWCF.BasicHttpSecurity.#ctor
  isExternal: true
  name: BasicHttpSecurity
  nameWithType: BasicHttpSecurity.BasicHttpSecurity
  fullName: CoreWCF.BasicHttpSecurity.BasicHttpSecurity
- uid: CoreWCF.BasicHttpSecurity.Mode*
  commentId: Overload:CoreWCF.BasicHttpSecurity.Mode
  isExternal: true
  name: Mode
  nameWithType: BasicHttpSecurity.Mode
  fullName: CoreWCF.BasicHttpSecurity.Mode
- uid: CoreWCF.Channels.BasicHttpSecurityMode
  commentId: T:CoreWCF.Channels.BasicHttpSecurityMode
  parent: CoreWCF.Channels
  isExternal: true
  name: BasicHttpSecurityMode
  nameWithType: BasicHttpSecurityMode
  fullName: CoreWCF.Channels.BasicHttpSecurityMode
- uid: CoreWCF.Channels
  commentId: N:CoreWCF.Channels
  isExternal: true
  name: CoreWCF.Channels
  nameWithType: CoreWCF.Channels
  fullName: CoreWCF.Channels
- uid: CoreWCF.BasicHttpSecurity.Transport*
  commentId: Overload:CoreWCF.BasicHttpSecurity.Transport
  isExternal: true
  name: Transport
  nameWithType: BasicHttpSecurity.Transport
  fullName: CoreWCF.BasicHttpSecurity.Transport
- uid: CoreWCF.HttpTransportSecurity
  commentId: T:CoreWCF.HttpTransportSecurity
  parent: CoreWCF
  isExternal: true
  name: HttpTransportSecurity
  nameWithType: HttpTransportSecurity
  fullName: CoreWCF.HttpTransportSecurity
- uid: CoreWCF.BasicHttpSecurity.Message*
  commentId: Overload:CoreWCF.BasicHttpSecurity.Message
  isExternal: true
  name: Message
  nameWithType: BasicHttpSecurity.Message
  fullName: CoreWCF.BasicHttpSecurity.Message
- uid: CoreWCF.BasicHttpMessageSecurity
  commentId: T:CoreWCF.BasicHttpMessageSecurity
  parent: CoreWCF
  isExternal: true
  name: BasicHttpMessageSecurity
  nameWithType: BasicHttpMessageSecurity
  fullName: CoreWCF.BasicHttpMessageSecurity
