### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ConfigurationManagerExtensions
  commentId: T:CoreWCF.Configuration.ConfigurationManagerExtensions
  id: ConfigurationManagerExtensions
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile(Microsoft.Extensions.DependencyInjection.IServiceCollection,System.String)
  langs:
  - csharp
  - vb
  name: ConfigurationManagerExtensions
  nameWithType: ConfigurationManagerExtensions
  fullName: CoreWCF.Configuration.ConfigurationManagerExtensions
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public static class ConfigurationManagerExtensions : Object'
    content.vb: >-
      Public Module ConfigurationManagerExtensions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile(Microsoft.Extensions.DependencyInjection.IServiceCollection,System.String)
  commentId: M:CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile(Microsoft.Extensions.DependencyInjection.IServiceCollection,System.String)
  id: AddServiceModelConfigurationManagerFile(Microsoft.Extensions.DependencyInjection.IServiceCollection,System.String)
  isExtensionMethod: true
  parent: CoreWCF.Configuration.ConfigurationManagerExtensions
  langs:
  - csharp
  - vb
  name: AddServiceModelConfigurationManagerFile(IServiceCollection, String)
  nameWithType: ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile(IServiceCollection, String)
  fullName: CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.String)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public static IServiceCollection AddServiceModelConfigurationManagerFile(this IServiceCollection builder, string path)
    parameters:
    - id: builder
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
    - id: path
      type: System.String
    return:
      type: Microsoft.Extensions.DependencyInjection.IServiceCollection
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function AddServiceModelConfigurationManagerFile(builder As IServiceCollection, path As String) As IServiceCollection
  overload: CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile*
  commentId: Overload:CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile
  isExternal: true
  name: AddServiceModelConfigurationManagerFile
  nameWithType: ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile
  fullName: CoreWCF.Configuration.ConfigurationManagerExtensions.AddServiceModelConfigurationManagerFile
- uid: Microsoft.Extensions.DependencyInjection.IServiceCollection
  isExternal: true
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: Microsoft.Extensions.DependencyInjection.IServiceCollection
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
