### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.BindingNotFoundException
  commentId: T:CoreWCF.Configuration.BindingNotFoundException
  id: BindingNotFoundException
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.BindingNotFoundException.#ctor
  - CoreWCF.Configuration.BindingNotFoundException.#ctor(System.String)
  - CoreWCF.Configuration.BindingNotFoundException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  - vb
  name: BindingNotFoundException
  nameWithType: BindingNotFoundException
  fullName: CoreWCF.Configuration.BindingNotFoundException
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public class BindingNotFoundException : Exception'
    content.vb: >-
      Public Class BindingNotFoundException
          Inherits Exception
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.BindingNotFoundException.#ctor
  commentId: M:CoreWCF.Configuration.BindingNotFoundException.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.BindingNotFoundException
  langs:
  - csharp
  - vb
  name: BindingNotFoundException()
  nameWithType: BindingNotFoundException.BindingNotFoundException()
  fullName: CoreWCF.Configuration.BindingNotFoundException.BindingNotFoundException()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public BindingNotFoundException()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.BindingNotFoundException.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.BindingNotFoundException.#ctor(System.String)
  commentId: M:CoreWCF.Configuration.BindingNotFoundException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: CoreWCF.Configuration.BindingNotFoundException
  langs:
  - csharp
  - vb
  name: BindingNotFoundException(String)
  nameWithType: BindingNotFoundException.BindingNotFoundException(String)
  fullName: CoreWCF.Configuration.BindingNotFoundException.BindingNotFoundException(System.String)
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public BindingNotFoundException(string message)
    parameters:
    - id: message
      type: System.String
    content.vb: Public Sub New(message As String)
  overload: CoreWCF.Configuration.BindingNotFoundException.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.BindingNotFoundException.#ctor(System.String,System.Exception)
  commentId: M:CoreWCF.Configuration.BindingNotFoundException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: CoreWCF.Configuration.BindingNotFoundException
  langs:
  - csharp
  - vb
  name: BindingNotFoundException(String, Exception)
  nameWithType: BindingNotFoundException.BindingNotFoundException(String, Exception)
  fullName: CoreWCF.Configuration.BindingNotFoundException.BindingNotFoundException(System.String, System.Exception)
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public BindingNotFoundException(string message, Exception innerException)
    parameters:
    - id: message
      type: System.String
    - id: innerException
      type: System.Exception
    content.vb: Public Sub New(message As String, innerException As Exception)
  overload: CoreWCF.Configuration.BindingNotFoundException.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.BindingNotFoundException.#ctor*
  commentId: Overload:CoreWCF.Configuration.BindingNotFoundException.#ctor
  isExternal: true
  name: BindingNotFoundException
  nameWithType: BindingNotFoundException.BindingNotFoundException
  fullName: CoreWCF.Configuration.BindingNotFoundException.BindingNotFoundException
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
