### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.CustomBindingCollectionElement
  commentId: T:CoreWCF.Configuration.CustomBindingCollectionElement
  id: CustomBindingCollectionElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.CustomBindingCollectionElement.#ctor
  langs:
  - csharp
  - vb
  name: CustomBindingCollectionElement
  nameWithType: CustomBindingCollectionElement
  fullName: CoreWCF.Configuration.CustomBindingCollectionElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a collection of  configuration elements that provide full control over the messaging stack for the user. This class cannot be inherited.
  remarks: "Custom bindings provide full control over the Windows Communication Foundation (WCF) messaging stack. An individual binding defines the message stack by specifying the configuration elements for the stack elements in the order they appear on the stack. Each element defines and configures the one element of the stack. There must be one and only one transport element in each custom binding. Without this element, the messaging stack is incomplete.  \n\nThe order in which elements appear in the stack matters, because it is the order in which operations are applied to the message. The recommended order of stack elements is the following:  \n\n1.  Transactions (optional)  \n\n2.  Reliable Messaging (optional)  \n\n3.  Security (optional)  \n\n4.  Transport  \n\n5.  Encoder (optional)  \n\n"
  syntax:
    content: 'public class CustomBindingCollectionElement : StandardBindingCollectionElement<CustomBinding, CustomBindingElement>'
    content.vb: >-
      Public Class CustomBindingCollectionElement
          Inherits StandardBindingCollectionElement(Of CustomBinding, CustomBindingElement)
  inheritance:
  - System.Object
  - CoreWCF.Configuration.BindingCollectionElement
  - CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.Channels.CustomBinding,CoreWCF.Configuration.CustomBindingElement}
  inheritedMembers:
  - CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.Channels.CustomBinding,CoreWCF.Configuration.CustomBindingElement}.Bindings
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.CustomBindingCollectionElement.#ctor
  commentId: M:CoreWCF.Configuration.CustomBindingCollectionElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.CustomBindingCollectionElement
  langs:
  - csharp
  - vb
  name: CustomBindingCollectionElement()
  nameWithType: CustomBindingCollectionElement.CustomBindingCollectionElement()
  fullName: CoreWCF.Configuration.CustomBindingCollectionElement.CustomBindingCollectionElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public CustomBindingCollectionElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.CustomBindingCollectionElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.BindingCollectionElement
  commentId: T:CoreWCF.Configuration.BindingCollectionElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement
  fullName: CoreWCF.Configuration.BindingCollectionElement
- uid: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.Channels.CustomBinding,CoreWCF.Configuration.CustomBindingElement}
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.Channels.CustomBinding,CoreWCF.Configuration.CustomBindingElement}
  parent: CoreWCF.Configuration
  definition: CoreWCF.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<CustomBinding, CustomBindingElement>
  nameWithType: StandardBindingCollectionElement<CustomBinding, CustomBindingElement>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<CoreWCF.Channels.CustomBinding, CoreWCF.Configuration.CustomBindingElement>
  nameWithType.vb: StandardBindingCollectionElement(Of CustomBinding, CustomBindingElement)
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of CoreWCF.Channels.CustomBinding, CoreWCF.Configuration.CustomBindingElement)
  name.vb: StandardBindingCollectionElement(Of CustomBinding, CustomBindingElement)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.Channels.CustomBinding
    name: CustomBinding
    nameWithType: CustomBinding
    fullName: CoreWCF.Channels.CustomBinding
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: CoreWCF.Configuration.CustomBindingElement
    name: CustomBindingElement
    nameWithType: CustomBindingElement
    fullName: CoreWCF.Configuration.CustomBindingElement
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.Channels.CustomBinding
    name: CustomBinding
    nameWithType: CustomBinding
    fullName: CoreWCF.Channels.CustomBinding
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: CoreWCF.Configuration.CustomBindingElement
    name: CustomBindingElement
    nameWithType: CustomBindingElement
    fullName: CoreWCF.Configuration.CustomBindingElement
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.Channels.CustomBinding,CoreWCF.Configuration.CustomBindingElement}.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.Channels.CustomBinding,CoreWCF.Configuration.CustomBindingElement}.Bindings
  parent: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.Channels.CustomBinding,CoreWCF.Configuration.CustomBindingElement}
  definition: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  name: Bindings
  nameWithType: StandardBindingCollectionElement<CustomBinding, CustomBindingElement>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<CoreWCF.Channels.CustomBinding, CoreWCF.Configuration.CustomBindingElement>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of CustomBinding, CustomBindingElement).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of CoreWCF.Channels.CustomBinding, CoreWCF.Configuration.CustomBindingElement).Bindings
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement`2
  isExternal: true
  name: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  name.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TStandardBinding
    nameWithType: TStandardBinding
    fullName: TStandardBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TStandardBinding
    nameWithType: TStandardBinding
    fullName: TStandardBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  isExternal: true
  name: Bindings
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
- uid: CoreWCF.Configuration.CustomBindingCollectionElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.CustomBindingCollectionElement.#ctor
  isExternal: true
  name: CustomBindingCollectionElement
  nameWithType: CustomBindingCollectionElement.CustomBindingCollectionElement
  fullName: CoreWCF.Configuration.CustomBindingCollectionElement.CustomBindingCollectionElement
