### YamlMime:ManagedReference
items:
- uid: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute
  id: OpenApiOperationAttribute
  parent: CoreWCF.OpenApi.Attributes
  children:
  - CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.#ctor
  - CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Description
  - CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Summary
  langs:
  - csharp
  - vb
  name: OpenApiOperationAttribute
  nameWithType: OpenApiOperationAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute
  type: Class
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nAttribute to denote information about an operation.\n"
  syntax:
    content: 'public sealed class OpenApiOperationAttribute : Attribute'
    content.vb: >-
      Public NotInheritable Class OpenApiOperationAttribute
          Inherits Attribute
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.#ctor
  commentId: M:CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.#ctor
  id: '#ctor'
  parent: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute
  langs:
  - csharp
  - vb
  name: OpenApiOperationAttribute()
  nameWithType: OpenApiOperationAttribute.OpenApiOperationAttribute()
  fullName: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.OpenApiOperationAttribute()
  type: Constructor
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  syntax:
    content: public OpenApiOperationAttribute()
    content.vb: Public Sub New
  overload: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Summary
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Summary
  id: Summary
  parent: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute
  langs:
  - csharp
  - vb
  name: Summary
  nameWithType: OpenApiOperationAttribute.Summary
  fullName: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Summary
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nA short summary about an operation.\n"
  syntax:
    content: public string Summary { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Summary As String
  overload: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Summary*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Description
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Description
  id: Description
  parent: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: OpenApiOperationAttribute.Description
  fullName: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Description
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nDescription of an operation\n"
  syntax:
    content: public string Description { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Description As String
  overload: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Description*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.OpenApi.Attributes
  commentId: N:CoreWCF.OpenApi.Attributes
  isExternal: true
  name: CoreWCF.OpenApi.Attributes
  nameWithType: CoreWCF.OpenApi.Attributes
  fullName: CoreWCF.OpenApi.Attributes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.#ctor*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.#ctor
  isExternal: true
  name: OpenApiOperationAttribute
  nameWithType: OpenApiOperationAttribute.OpenApiOperationAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.OpenApiOperationAttribute
- uid: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Summary*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Summary
  isExternal: true
  name: Summary
  nameWithType: OpenApiOperationAttribute.Summary
  fullName: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Summary
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Description*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Description
  isExternal: true
  name: Description
  nameWithType: OpenApiOperationAttribute.Description
  fullName: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute.Description
