### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceModelExtensionElement
  commentId: T:CoreWCF.Configuration.ServiceModelExtensionElement
  id: ServiceModelExtensionElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceModelExtensionElement.#ctor
  - CoreWCF.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - CoreWCF.Configuration.ServiceModelExtensionElement.CopyFrom(CoreWCF.Configuration.ServiceModelExtensionElement)
  - CoreWCF.Configuration.ServiceModelExtensionElement.ExtensionCollectionName
  langs:
  - csharp
  - vb
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: CoreWCF.Configuration.ServiceModelExtensionElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: An abstract base class for a configuration element that contains a dynamic collection of heterogeneous child elements.
  remarks: To be added.
  syntax:
    content: 'public abstract class ServiceModelExtensionElement : ServiceModelConfigurationElement'
    content.vb: >-
      Public MustInherit Class ServiceModelExtensionElement
          Inherits ServiceModelConfigurationElement
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElement
  derivedClasses:
  - CoreWCF.Configuration.BindingElementExtensionElement
  inheritedMembers:
  - CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: CoreWCF.Configuration.ServiceModelExtensionElement.CopyFrom(CoreWCF.Configuration.ServiceModelExtensionElement)
  commentId: M:CoreWCF.Configuration.ServiceModelExtensionElement.CopyFrom(CoreWCF.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(CoreWCF.Configuration.ServiceModelExtensionElement)
  parent: CoreWCF.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  - vb
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: ServiceModelExtensionElement.CopyFrom(ServiceModelExtensionElement)
  fullName: CoreWCF.Configuration.ServiceModelExtensionElement.CopyFrom(CoreWCF.Configuration.ServiceModelExtensionElement)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public virtual void CopyFrom(ServiceModelExtensionElement from)
    parameters:
    - id: from
      type: CoreWCF.Configuration.ServiceModelExtensionElement
    content.vb: Public Overridable Sub CopyFrom(from As ServiceModelExtensionElement)
  overload: CoreWCF.Configuration.ServiceModelExtensionElement.CopyFrom*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
- uid: CoreWCF.Configuration.ServiceModelExtensionElement.#ctor
  commentId: M:CoreWCF.Configuration.ServiceModelExtensionElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  - vb
  name: ServiceModelExtensionElement()
  nameWithType: ServiceModelExtensionElement.ServiceModelExtensionElement()
  fullName: CoreWCF.Configuration.ServiceModelExtensionElement.ServiceModelExtensionElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected ServiceModelExtensionElement()
    content.vb: Protected Sub New
  overload: CoreWCF.Configuration.ServiceModelExtensionElement.#ctor*
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: CoreWCF.Configuration.ServiceModelExtensionElement.ExtensionCollectionName
  commentId: P:CoreWCF.Configuration.ServiceModelExtensionElement.ExtensionCollectionName
  id: ExtensionCollectionName
  parent: CoreWCF.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  - vb
  name: ExtensionCollectionName
  nameWithType: ServiceModelExtensionElement.ExtensionCollectionName
  fullName: CoreWCF.Configuration.ServiceModelExtensionElement.ExtensionCollectionName
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string ExtensionCollectionName { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ExtensionCollectionName As String
  overload: CoreWCF.Configuration.ServiceModelExtensionElement.ExtensionCollectionName*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
- uid: CoreWCF.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  commentId: P:CoreWCF.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  id: ConfigurationElementName
  parent: CoreWCF.Configuration.ServiceModelExtensionElement
  langs:
  - csharp
  - vb
  name: ConfigurationElementName
  nameWithType: ServiceModelExtensionElement.ConfigurationElementName
  fullName: CoreWCF.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string ConfigurationElementName { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ConfigurationElementName As String
  overload: CoreWCF.Configuration.ServiceModelExtensionElement.ConfigurationElementName*
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: CoreWCF.Configuration.ServiceModelConfigurationElement
  definition: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  isExternal: true
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceModelExtensionElement.CopyFrom*
  commentId: Overload:CoreWCF.Configuration.ServiceModelExtensionElement.CopyFrom
  isExternal: true
  name: CopyFrom
  nameWithType: ServiceModelExtensionElement.CopyFrom
  fullName: CoreWCF.Configuration.ServiceModelExtensionElement.CopyFrom
- uid: CoreWCF.Configuration.ServiceModelExtensionElement
  commentId: T:CoreWCF.Configuration.ServiceModelExtensionElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: CoreWCF.Configuration.ServiceModelExtensionElement
- uid: CoreWCF.Configuration.ServiceModelExtensionElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.ServiceModelExtensionElement.#ctor
  isExternal: true
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement.ServiceModelExtensionElement
  fullName: CoreWCF.Configuration.ServiceModelExtensionElement.ServiceModelExtensionElement
- uid: CoreWCF.Configuration.ServiceModelExtensionElement.ExtensionCollectionName*
  commentId: Overload:CoreWCF.Configuration.ServiceModelExtensionElement.ExtensionCollectionName
  isExternal: true
  name: ExtensionCollectionName
  nameWithType: ServiceModelExtensionElement.ExtensionCollectionName
  fullName: CoreWCF.Configuration.ServiceModelExtensionElement.ExtensionCollectionName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.Configuration.ServiceModelExtensionElement.ConfigurationElementName*
  commentId: Overload:CoreWCF.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  isExternal: true
  name: ConfigurationElementName
  nameWithType: ServiceModelExtensionElement.ConfigurationElementName
  fullName: CoreWCF.Configuration.ServiceModelExtensionElement.ConfigurationElementName
