### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement
  commentId: T:CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement
  id: IssuedTokenParametersEndpointAddressElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor
  - CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  - CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  langs:
  - csharp
  - vb
  name: IssuedTokenParametersEndpointAddressElement
  nameWithType: IssuedTokenParametersEndpointAddressElement
  fullName: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a configuration element that specifies an endpoint that issues a security token. This class cannot be inherited.
  remarks: To be added.
  syntax:
    content: 'public sealed class IssuedTokenParametersEndpointAddressElement : EndpointAddressElementBase'
    content.vb: >-
      Public NotInheritable Class IssuedTokenParametersEndpointAddressElement
          Inherits EndpointAddressElementBase
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElement
  - CoreWCF.Configuration.EndpointAddressElementBase
  inheritedMembers:
  - CoreWCF.Configuration.EndpointAddressElementBase.Copy(CoreWCF.Configuration.EndpointAddressElementBase)
  - CoreWCF.Configuration.EndpointAddressElementBase.InitializeFrom(CoreWCF.EndpointAddress)
  - CoreWCF.Configuration.EndpointAddressElementBase.Address
  - CoreWCF.Configuration.EndpointAddressElementBase.Headers
  - CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor
  commentId: M:CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement
  langs:
  - csharp
  - vb
  name: IssuedTokenParametersEndpointAddressElement()
  nameWithType: IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement()
  fullName: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public IssuedTokenParametersEndpointAddressElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  commentId: P:CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  id: Binding
  parent: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement
  langs:
  - csharp
  - vb
  name: Binding
  nameWithType: IssuedTokenParametersEndpointAddressElement.Binding
  fullName: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string Binding { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Binding As String
  overload: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.Binding*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  commentId: P:CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  id: BindingConfiguration
  parent: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement
  langs:
  - csharp
  - vb
  name: BindingConfiguration
  nameWithType: IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  fullName: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string BindingConfiguration { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BindingConfiguration As String
  overload: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement
- uid: CoreWCF.Configuration.EndpointAddressElementBase
  commentId: T:CoreWCF.Configuration.EndpointAddressElementBase
  parent: CoreWCF.Configuration
  isExternal: true
  name: EndpointAddressElementBase
  nameWithType: EndpointAddressElementBase
  fullName: CoreWCF.Configuration.EndpointAddressElementBase
- uid: CoreWCF.Configuration.EndpointAddressElementBase.Copy(CoreWCF.Configuration.EndpointAddressElementBase)
  commentId: M:CoreWCF.Configuration.EndpointAddressElementBase.Copy(CoreWCF.Configuration.EndpointAddressElementBase)
  parent: CoreWCF.Configuration.EndpointAddressElementBase
  isExternal: true
  name: Copy(EndpointAddressElementBase)
  nameWithType: EndpointAddressElementBase.Copy(EndpointAddressElementBase)
  fullName: CoreWCF.Configuration.EndpointAddressElementBase.Copy(CoreWCF.Configuration.EndpointAddressElementBase)
  spec.csharp:
  - uid: CoreWCF.Configuration.EndpointAddressElementBase.Copy(CoreWCF.Configuration.EndpointAddressElementBase)
    name: Copy
    nameWithType: EndpointAddressElementBase.Copy
    fullName: CoreWCF.Configuration.EndpointAddressElementBase.Copy
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: CoreWCF.Configuration.EndpointAddressElementBase
    name: EndpointAddressElementBase
    nameWithType: EndpointAddressElementBase
    fullName: CoreWCF.Configuration.EndpointAddressElementBase
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.EndpointAddressElementBase.Copy(CoreWCF.Configuration.EndpointAddressElementBase)
    name: Copy
    nameWithType: EndpointAddressElementBase.Copy
    fullName: CoreWCF.Configuration.EndpointAddressElementBase.Copy
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: CoreWCF.Configuration.EndpointAddressElementBase
    name: EndpointAddressElementBase
    nameWithType: EndpointAddressElementBase
    fullName: CoreWCF.Configuration.EndpointAddressElementBase
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.EndpointAddressElementBase.InitializeFrom(CoreWCF.EndpointAddress)
  commentId: M:CoreWCF.Configuration.EndpointAddressElementBase.InitializeFrom(CoreWCF.EndpointAddress)
  parent: CoreWCF.Configuration.EndpointAddressElementBase
  isExternal: true
  name: InitializeFrom(EndpointAddress)
  nameWithType: EndpointAddressElementBase.InitializeFrom(EndpointAddress)
  fullName: CoreWCF.Configuration.EndpointAddressElementBase.InitializeFrom(CoreWCF.EndpointAddress)
  spec.csharp:
  - uid: CoreWCF.Configuration.EndpointAddressElementBase.InitializeFrom(CoreWCF.EndpointAddress)
    name: InitializeFrom
    nameWithType: EndpointAddressElementBase.InitializeFrom
    fullName: CoreWCF.Configuration.EndpointAddressElementBase.InitializeFrom
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: CoreWCF.EndpointAddress
    name: EndpointAddress
    nameWithType: EndpointAddress
    fullName: CoreWCF.EndpointAddress
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.EndpointAddressElementBase.InitializeFrom(CoreWCF.EndpointAddress)
    name: InitializeFrom
    nameWithType: EndpointAddressElementBase.InitializeFrom
    fullName: CoreWCF.Configuration.EndpointAddressElementBase.InitializeFrom
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: CoreWCF.EndpointAddress
    name: EndpointAddress
    nameWithType: EndpointAddress
    fullName: CoreWCF.EndpointAddress
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.EndpointAddressElementBase.Address
  commentId: P:CoreWCF.Configuration.EndpointAddressElementBase.Address
  parent: CoreWCF.Configuration.EndpointAddressElementBase
  isExternal: true
  name: Address
  nameWithType: EndpointAddressElementBase.Address
  fullName: CoreWCF.Configuration.EndpointAddressElementBase.Address
- uid: CoreWCF.Configuration.EndpointAddressElementBase.Headers
  commentId: P:CoreWCF.Configuration.EndpointAddressElementBase.Headers
  parent: CoreWCF.Configuration.EndpointAddressElementBase
  isExternal: true
  name: Headers
  nameWithType: EndpointAddressElementBase.Headers
  fullName: CoreWCF.Configuration.EndpointAddressElementBase.Headers
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: CoreWCF.Configuration.ServiceModelConfigurationElement
  definition: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  isExternal: true
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor
  isExternal: true
  name: IssuedTokenParametersEndpointAddressElement
  nameWithType: IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement
  fullName: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement
- uid: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.Binding*
  commentId: Overload:CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  isExternal: true
  name: Binding
  nameWithType: IssuedTokenParametersEndpointAddressElement.Binding
  fullName: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration*
  commentId: Overload:CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  isExternal: true
  name: BindingConfiguration
  nameWithType: IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  fullName: CoreWCF.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
