### YamlMime:ManagedReference
items:
- uid: CoreWCF.OpenApi.Attributes
  commentId: N:CoreWCF.OpenApi.Attributes
  id: CoreWCF.OpenApi.Attributes
  children:
  - CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute
  - CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute
  - CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute
  - CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute
  - CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
  - CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute
  - CoreWCF.OpenApi.Attributes.OpenApiTagAttribute
  langs:
  - csharp
  - vb
  name: CoreWCF.OpenApi.Attributes
  nameWithType: CoreWCF.OpenApi.Attributes
  fullName: CoreWCF.OpenApi.Attributes
  type: Namespace
  assemblies:
  - CoreWCF.WebHttp
references:
- uid: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute
  isExternal: true
  name: OpenApiBasePathAttribute
  nameWithType: OpenApiBasePathAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute
- uid: CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute
  isExternal: true
  name: OpenApiHiddenAttribute
  nameWithType: OpenApiHiddenAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiHiddenAttribute
- uid: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute
  isExternal: true
  name: OpenApiOperationAttribute
  nameWithType: OpenApiOperationAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiOperationAttribute
- uid: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute
  isExternal: true
  name: OpenApiParameterAttribute
  nameWithType: OpenApiParameterAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
  isExternal: true
  name: OpenApiPropertyAttribute
  nameWithType: OpenApiPropertyAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
- uid: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute
  isExternal: true
  name: OpenApiResponseAttribute
  nameWithType: OpenApiResponseAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute
- uid: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiTagAttribute
  isExternal: true
  name: OpenApiTagAttribute
  nameWithType: OpenApiTagAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiTagAttribute
