### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions
  commentId: T:CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions
  id: ServiceModelApplicationBuilderExtensions
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  - CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.Action{CoreWCF.Configuration.IServiceBuilder})
  langs:
  - csharp
  - vb
  name: ServiceModelApplicationBuilderExtensions
  nameWithType: ServiceModelApplicationBuilderExtensions
  fullName: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions
  type: Class
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public static class ServiceModelApplicationBuilderExtensions : Object'
    content.vb: >-
      Public Module ServiceModelApplicationBuilderExtensions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.Action{CoreWCF.Configuration.IServiceBuilder})
  commentId: M:CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.Action{CoreWCF.Configuration.IServiceBuilder})
  id: UseServiceModel(Microsoft.AspNetCore.Builder.IApplicationBuilder,System.Action{CoreWCF.Configuration.IServiceBuilder})
  isExtensionMethod: true
  parent: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions
  langs:
  - csharp
  - vb
  name: UseServiceModel(IApplicationBuilder, Action<IServiceBuilder>)
  nameWithType: ServiceModelApplicationBuilderExtensions.UseServiceModel(IApplicationBuilder, Action<IServiceBuilder>)
  fullName: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(Microsoft.AspNetCore.Builder.IApplicationBuilder, System.Action<CoreWCF.Configuration.IServiceBuilder>)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public static IApplicationBuilder UseServiceModel(this IApplicationBuilder app, Action<IServiceBuilder> configureServices)
    parameters:
    - id: app
      type: Microsoft.AspNetCore.Builder.IApplicationBuilder
    - id: configureServices
      type: System.Action{CoreWCF.Configuration.IServiceBuilder}
    return:
      type: Microsoft.AspNetCore.Builder.IApplicationBuilder
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function UseServiceModel(app As IApplicationBuilder, configureServices As Action(Of IServiceBuilder)) As IApplicationBuilder
  overload: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel*
  nameWithType.vb: ServiceModelApplicationBuilderExtensions.UseServiceModel(IApplicationBuilder, Action(Of IServiceBuilder))
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(Microsoft.AspNetCore.Builder.IApplicationBuilder, System.Action(Of CoreWCF.Configuration.IServiceBuilder))
  name.vb: UseServiceModel(IApplicationBuilder, Action(Of IServiceBuilder))
- uid: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  commentId: M:CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  id: UseServiceModel(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  isExtensionMethod: true
  parent: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions
  langs:
  - csharp
  - vb
  name: UseServiceModel(IApplicationBuilder)
  nameWithType: ServiceModelApplicationBuilderExtensions.UseServiceModel(IApplicationBuilder)
  fullName: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public static IApplicationBuilder UseServiceModel(this IApplicationBuilder app)
    parameters:
    - id: app
      type: Microsoft.AspNetCore.Builder.IApplicationBuilder
    return:
      type: Microsoft.AspNetCore.Builder.IApplicationBuilder
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function UseServiceModel(app As IApplicationBuilder) As IApplicationBuilder
  overload: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel*
  commentId: Overload:CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel
  isExternal: true
  name: UseServiceModel
  nameWithType: ServiceModelApplicationBuilderExtensions.UseServiceModel
  fullName: CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel
- uid: Microsoft.AspNetCore.Builder.IApplicationBuilder
  isExternal: true
  name: IApplicationBuilder
  nameWithType: IApplicationBuilder
  fullName: Microsoft.AspNetCore.Builder.IApplicationBuilder
- uid: System.Action{CoreWCF.Configuration.IServiceBuilder}
  commentId: '!:System.Action{CoreWCF.Configuration.IServiceBuilder}'
  definition: System.Action`1
  name: Action<IServiceBuilder>
  nameWithType: Action<IServiceBuilder>
  fullName: System.Action<CoreWCF.Configuration.IServiceBuilder>
  nameWithType.vb: Action(Of IServiceBuilder)
  fullName.vb: System.Action(Of CoreWCF.Configuration.IServiceBuilder)
  name.vb: Action(Of IServiceBuilder)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.Configuration.IServiceBuilder
    name: IServiceBuilder
    nameWithType: IServiceBuilder
    fullName: CoreWCF.Configuration.IServiceBuilder
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.Configuration.IServiceBuilder
    name: IServiceBuilder
    nameWithType: IServiceBuilder
    fullName: CoreWCF.Configuration.IServiceBuilder
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Action`1
  isExternal: true
  name: Action<>
  nameWithType: Action<>
  fullName: System.Action<>
  nameWithType.vb: Action(Of )
  fullName.vb: System.Action(Of )
  name.vb: Action(Of )
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
