### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.NetTcpBindingCollectionElement
  commentId: T:CoreWCF.Configuration.NetTcpBindingCollectionElement
  id: NetTcpBindingCollectionElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.NetTcpBindingCollectionElement.#ctor
  langs:
  - csharp
  - vb
  name: NetTcpBindingCollectionElement
  nameWithType: NetTcpBindingCollectionElement
  fullName: CoreWCF.Configuration.NetTcpBindingCollectionElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a configuration element that contains a collection of  instances.
  remarks: To be added.
  syntax:
    content: 'public class NetTcpBindingCollectionElement : StandardBindingCollectionElement<NetTcpBinding, NetTcpBindingElement>'
    content.vb: >-
      Public Class NetTcpBindingCollectionElement
          Inherits StandardBindingCollectionElement(Of NetTcpBinding, NetTcpBindingElement)
  inheritance:
  - System.Object
  - CoreWCF.Configuration.BindingCollectionElement
  - CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetTcpBinding,CoreWCF.Configuration.NetTcpBindingElement}
  inheritedMembers:
  - CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetTcpBinding,CoreWCF.Configuration.NetTcpBindingElement}.Bindings
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.NetTcpBindingCollectionElement.#ctor
  commentId: M:CoreWCF.Configuration.NetTcpBindingCollectionElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.NetTcpBindingCollectionElement
  langs:
  - csharp
  - vb
  name: NetTcpBindingCollectionElement()
  nameWithType: NetTcpBindingCollectionElement.NetTcpBindingCollectionElement()
  fullName: CoreWCF.Configuration.NetTcpBindingCollectionElement.NetTcpBindingCollectionElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public NetTcpBindingCollectionElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.NetTcpBindingCollectionElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.BindingCollectionElement
  commentId: T:CoreWCF.Configuration.BindingCollectionElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement
  fullName: CoreWCF.Configuration.BindingCollectionElement
- uid: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetTcpBinding,CoreWCF.Configuration.NetTcpBindingElement}
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetTcpBinding,CoreWCF.Configuration.NetTcpBindingElement}
  parent: CoreWCF.Configuration
  definition: CoreWCF.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<NetTcpBinding, NetTcpBindingElement>
  nameWithType: StandardBindingCollectionElement<NetTcpBinding, NetTcpBindingElement>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<CoreWCF.NetTcpBinding, CoreWCF.Configuration.NetTcpBindingElement>
  nameWithType.vb: StandardBindingCollectionElement(Of NetTcpBinding, NetTcpBindingElement)
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of CoreWCF.NetTcpBinding, CoreWCF.Configuration.NetTcpBindingElement)
  name.vb: StandardBindingCollectionElement(Of NetTcpBinding, NetTcpBindingElement)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.NetTcpBinding
    name: NetTcpBinding
    nameWithType: NetTcpBinding
    fullName: CoreWCF.NetTcpBinding
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: CoreWCF.Configuration.NetTcpBindingElement
    name: NetTcpBindingElement
    nameWithType: NetTcpBindingElement
    fullName: CoreWCF.Configuration.NetTcpBindingElement
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.NetTcpBinding
    name: NetTcpBinding
    nameWithType: NetTcpBinding
    fullName: CoreWCF.NetTcpBinding
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: CoreWCF.Configuration.NetTcpBindingElement
    name: NetTcpBindingElement
    nameWithType: NetTcpBindingElement
    fullName: CoreWCF.Configuration.NetTcpBindingElement
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetTcpBinding,CoreWCF.Configuration.NetTcpBindingElement}.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetTcpBinding,CoreWCF.Configuration.NetTcpBindingElement}.Bindings
  parent: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetTcpBinding,CoreWCF.Configuration.NetTcpBindingElement}
  definition: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  name: Bindings
  nameWithType: StandardBindingCollectionElement<NetTcpBinding, NetTcpBindingElement>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<CoreWCF.NetTcpBinding, CoreWCF.Configuration.NetTcpBindingElement>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of NetTcpBinding, NetTcpBindingElement).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of CoreWCF.NetTcpBinding, CoreWCF.Configuration.NetTcpBindingElement).Bindings
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement`2
  isExternal: true
  name: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  name.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TStandardBinding
    nameWithType: TStandardBinding
    fullName: TStandardBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TStandardBinding
    nameWithType: TStandardBinding
    fullName: TStandardBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  isExternal: true
  name: Bindings
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
- uid: CoreWCF.Configuration.NetTcpBindingCollectionElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.NetTcpBindingCollectionElement.#ctor
  isExternal: true
  name: NetTcpBindingCollectionElement
  nameWithType: NetTcpBindingCollectionElement.NetTcpBindingCollectionElement
  fullName: CoreWCF.Configuration.NetTcpBindingCollectionElement.NetTcpBindingCollectionElement
