### YamlMime:ManagedReference
items:
- uid: CoreWCF.WSFederationHttpSecurity
  commentId: T:CoreWCF.WSFederationHttpSecurity
  id: WSFederationHttpSecurity
  parent: CoreWCF
  children:
  - CoreWCF.WSFederationHttpSecurity.#ctor
  - CoreWCF.WSFederationHttpSecurity.Message
  - CoreWCF.WSFederationHttpSecurity.Mode
  langs:
  - csharp
  - vb
  name: WSFederationHttpSecurity
  nameWithType: WSFederationHttpSecurity
  fullName: CoreWCF.WSFederationHttpSecurity
  type: Class
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  summary: Specifies the security settings for the . This class cannot be inherited.
  remarks: "This class specifies the kind of security to be applied to the `wsFederationHttpBinding` binding and the specific security settings.  \n\n"
  syntax:
    content: 'public sealed class WSFederationHttpSecurity : Object'
    content.vb: >-
      Public NotInheritable Class WSFederationHttpSecurity
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.WSFederationHttpSecurity.#ctor
  commentId: M:CoreWCF.WSFederationHttpSecurity.#ctor
  id: '#ctor'
  parent: CoreWCF.WSFederationHttpSecurity
  langs:
  - csharp
  - vb
  name: WSFederationHttpSecurity()
  nameWithType: WSFederationHttpSecurity.WSFederationHttpSecurity()
  fullName: CoreWCF.WSFederationHttpSecurity.WSFederationHttpSecurity()
  type: Constructor
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public WSFederationHttpSecurity()
    content.vb: Public Sub New
  overload: CoreWCF.WSFederationHttpSecurity.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.WSFederationHttpSecurity.Mode
  commentId: P:CoreWCF.WSFederationHttpSecurity.Mode
  id: Mode
  parent: CoreWCF.WSFederationHttpSecurity
  langs:
  - csharp
  - vb
  name: Mode
  nameWithType: WSFederationHttpSecurity.Mode
  fullName: CoreWCF.WSFederationHttpSecurity.Mode
  type: Property
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public WSFederationHttpSecurityMode Mode { get; set; }
    parameters: []
    return:
      type: CoreWCF.WSFederationHttpSecurityMode
    content.vb: Public Property Mode As WSFederationHttpSecurityMode
  overload: CoreWCF.WSFederationHttpSecurity.Mode*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.WSFederationHttpSecurity.Message
  commentId: P:CoreWCF.WSFederationHttpSecurity.Message
  id: Message
  parent: CoreWCF.WSFederationHttpSecurity
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: WSFederationHttpSecurity.Message
  fullName: CoreWCF.WSFederationHttpSecurity.Message
  type: Property
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public FederatedMessageSecurityOverHttp Message { get; set; }
    parameters: []
    return:
      type: CoreWCF.Security.FederatedMessageSecurityOverHttp
    content.vb: Public Property Message As FederatedMessageSecurityOverHttp
  overload: CoreWCF.WSFederationHttpSecurity.Message*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF
  commentId: N:CoreWCF
  isExternal: true
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.WSFederationHttpSecurity.#ctor*
  commentId: Overload:CoreWCF.WSFederationHttpSecurity.#ctor
  isExternal: true
  name: WSFederationHttpSecurity
  nameWithType: WSFederationHttpSecurity.WSFederationHttpSecurity
  fullName: CoreWCF.WSFederationHttpSecurity.WSFederationHttpSecurity
- uid: CoreWCF.WSFederationHttpSecurity.Mode*
  commentId: Overload:CoreWCF.WSFederationHttpSecurity.Mode
  isExternal: true
  name: Mode
  nameWithType: WSFederationHttpSecurity.Mode
  fullName: CoreWCF.WSFederationHttpSecurity.Mode
- uid: CoreWCF.WSFederationHttpSecurityMode
  commentId: T:CoreWCF.WSFederationHttpSecurityMode
  parent: CoreWCF
  isExternal: true
  name: WSFederationHttpSecurityMode
  nameWithType: WSFederationHttpSecurityMode
  fullName: CoreWCF.WSFederationHttpSecurityMode
- uid: CoreWCF.WSFederationHttpSecurity.Message*
  commentId: Overload:CoreWCF.WSFederationHttpSecurity.Message
  isExternal: true
  name: Message
  nameWithType: WSFederationHttpSecurity.Message
  fullName: CoreWCF.WSFederationHttpSecurity.Message
- uid: CoreWCF.Security.FederatedMessageSecurityOverHttp
  commentId: T:CoreWCF.Security.FederatedMessageSecurityOverHttp
  parent: CoreWCF.Security
  isExternal: true
  name: FederatedMessageSecurityOverHttp
  nameWithType: FederatedMessageSecurityOverHttp
  fullName: CoreWCF.Security.FederatedMessageSecurityOverHttp
- uid: CoreWCF.Security
  commentId: N:CoreWCF.Security
  isExternal: true
  name: CoreWCF.Security
  nameWithType: CoreWCF.Security
  fullName: CoreWCF.Security
