### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceBuilderExtensions
  commentId: T:CoreWCF.Configuration.ServiceBuilderExtensions
  id: ServiceBuilderExtensions
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureAllServiceHostBase(CoreWCF.Configuration.IServiceBuilder,System.Action{CoreWCF.ServiceHostBase})
  - CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase(CoreWCF.Configuration.IServiceBuilder,System.Type,System.Action{CoreWCF.ServiceHostBase})
  - CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase``1(CoreWCF.Configuration.IServiceBuilder,System.Action{CoreWCF.ServiceHostBase})
  langs:
  - csharp
  - vb
  name: ServiceBuilderExtensions
  nameWithType: ServiceBuilderExtensions
  fullName: CoreWCF.Configuration.ServiceBuilderExtensions
  type: Class
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public static class ServiceBuilderExtensions : Object'
    content.vb: >-
      Public Module ServiceBuilderExtensions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase``1(CoreWCF.Configuration.IServiceBuilder,System.Action{CoreWCF.ServiceHostBase})
  commentId: M:CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase``1(CoreWCF.Configuration.IServiceBuilder,System.Action{CoreWCF.ServiceHostBase})
  id: ConfigureServiceHostBase``1(CoreWCF.Configuration.IServiceBuilder,System.Action{CoreWCF.ServiceHostBase})
  isExtensionMethod: true
  parent: CoreWCF.Configuration.ServiceBuilderExtensions
  langs:
  - csharp
  - vb
  name: ConfigureServiceHostBase<TService>(IServiceBuilder, Action<ServiceHostBase>)
  nameWithType: ServiceBuilderExtensions.ConfigureServiceHostBase<TService>(IServiceBuilder, Action<ServiceHostBase>)
  fullName: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase<TService>(CoreWCF.Configuration.IServiceBuilder, System.Action<CoreWCF.ServiceHostBase>)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: >-
      public static void ConfigureServiceHostBase<TService>(this IServiceBuilder builder, Action<ServiceHostBase> func)
          where TService : class
    parameters:
    - id: builder
      type: CoreWCF.Configuration.IServiceBuilder
    - id: func
      type: System.Action{CoreWCF.ServiceHostBase}
    typeParameters:
    - id: TService
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Sub ConfigureServiceHostBase(Of TService As Class)(builder As IServiceBuilder, func As Action(Of ServiceHostBase))
  overload: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase*
  nameWithType.vb: ServiceBuilderExtensions.ConfigureServiceHostBase(Of TService)(IServiceBuilder, Action(Of ServiceHostBase))
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase(Of TService)(CoreWCF.Configuration.IServiceBuilder, System.Action(Of CoreWCF.ServiceHostBase))
  name.vb: ConfigureServiceHostBase(Of TService)(IServiceBuilder, Action(Of ServiceHostBase))
- uid: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase(CoreWCF.Configuration.IServiceBuilder,System.Type,System.Action{CoreWCF.ServiceHostBase})
  commentId: M:CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase(CoreWCF.Configuration.IServiceBuilder,System.Type,System.Action{CoreWCF.ServiceHostBase})
  id: ConfigureServiceHostBase(CoreWCF.Configuration.IServiceBuilder,System.Type,System.Action{CoreWCF.ServiceHostBase})
  isExtensionMethod: true
  parent: CoreWCF.Configuration.ServiceBuilderExtensions
  langs:
  - csharp
  - vb
  name: ConfigureServiceHostBase(IServiceBuilder, Type, Action<ServiceHostBase>)
  nameWithType: ServiceBuilderExtensions.ConfigureServiceHostBase(IServiceBuilder, Type, Action<ServiceHostBase>)
  fullName: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase(CoreWCF.Configuration.IServiceBuilder, System.Type, System.Action<CoreWCF.ServiceHostBase>)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public static void ConfigureServiceHostBase(this IServiceBuilder builder, Type serviceType, Action<ServiceHostBase> func)
    parameters:
    - id: builder
      type: CoreWCF.Configuration.IServiceBuilder
    - id: serviceType
      type: System.Type
    - id: func
      type: System.Action{CoreWCF.ServiceHostBase}
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Sub ConfigureServiceHostBase(builder As IServiceBuilder, serviceType As Type, func As Action(Of ServiceHostBase))
  overload: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase*
  nameWithType.vb: ServiceBuilderExtensions.ConfigureServiceHostBase(IServiceBuilder, Type, Action(Of ServiceHostBase))
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase(CoreWCF.Configuration.IServiceBuilder, System.Type, System.Action(Of CoreWCF.ServiceHostBase))
  name.vb: ConfigureServiceHostBase(IServiceBuilder, Type, Action(Of ServiceHostBase))
- uid: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureAllServiceHostBase(CoreWCF.Configuration.IServiceBuilder,System.Action{CoreWCF.ServiceHostBase})
  commentId: M:CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureAllServiceHostBase(CoreWCF.Configuration.IServiceBuilder,System.Action{CoreWCF.ServiceHostBase})
  id: ConfigureAllServiceHostBase(CoreWCF.Configuration.IServiceBuilder,System.Action{CoreWCF.ServiceHostBase})
  isExtensionMethod: true
  parent: CoreWCF.Configuration.ServiceBuilderExtensions
  langs:
  - csharp
  - vb
  name: ConfigureAllServiceHostBase(IServiceBuilder, Action<ServiceHostBase>)
  nameWithType: ServiceBuilderExtensions.ConfigureAllServiceHostBase(IServiceBuilder, Action<ServiceHostBase>)
  fullName: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureAllServiceHostBase(CoreWCF.Configuration.IServiceBuilder, System.Action<CoreWCF.ServiceHostBase>)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public static void ConfigureAllServiceHostBase(this IServiceBuilder builder, Action<ServiceHostBase> func)
    parameters:
    - id: builder
      type: CoreWCF.Configuration.IServiceBuilder
    - id: func
      type: System.Action{CoreWCF.ServiceHostBase}
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Sub ConfigureAllServiceHostBase(builder As IServiceBuilder, func As Action(Of ServiceHostBase))
  overload: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureAllServiceHostBase*
  nameWithType.vb: ServiceBuilderExtensions.ConfigureAllServiceHostBase(IServiceBuilder, Action(Of ServiceHostBase))
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureAllServiceHostBase(CoreWCF.Configuration.IServiceBuilder, System.Action(Of CoreWCF.ServiceHostBase))
  name.vb: ConfigureAllServiceHostBase(IServiceBuilder, Action(Of ServiceHostBase))
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase*
  commentId: Overload:CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase
  isExternal: true
  name: ConfigureServiceHostBase
  nameWithType: ServiceBuilderExtensions.ConfigureServiceHostBase
  fullName: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureServiceHostBase
- uid: CoreWCF.Configuration.IServiceBuilder
  commentId: T:CoreWCF.Configuration.IServiceBuilder
  parent: CoreWCF.Configuration
  isExternal: true
  name: IServiceBuilder
  nameWithType: IServiceBuilder
  fullName: CoreWCF.Configuration.IServiceBuilder
- uid: System.Action{CoreWCF.ServiceHostBase}
  commentId: '!:System.Action{CoreWCF.ServiceHostBase}'
  definition: System.Action`1
  name: Action<ServiceHostBase>
  nameWithType: Action<ServiceHostBase>
  fullName: System.Action<CoreWCF.ServiceHostBase>
  nameWithType.vb: Action(Of ServiceHostBase)
  fullName.vb: System.Action(Of CoreWCF.ServiceHostBase)
  name.vb: Action(Of ServiceHostBase)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.ServiceHostBase
    name: ServiceHostBase
    nameWithType: ServiceHostBase
    fullName: CoreWCF.ServiceHostBase
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.ServiceHostBase
    name: ServiceHostBase
    nameWithType: ServiceHostBase
    fullName: CoreWCF.ServiceHostBase
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Action`1
  isExternal: true
  name: Action<>
  nameWithType: Action<>
  fullName: System.Action<>
  nameWithType.vb: Action(Of )
  fullName.vb: System.Action(Of )
  name.vb: Action(Of )
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Type
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureAllServiceHostBase*
  commentId: Overload:CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureAllServiceHostBase
  isExternal: true
  name: ConfigureAllServiceHostBase
  nameWithType: ServiceBuilderExtensions.ConfigureAllServiceHostBase
  fullName: CoreWCF.Configuration.ServiceBuilderExtensions.ConfigureAllServiceHostBase
