### YamlMime:ManagedReference
items:
- uid: CoreWCF.OpenApi.OpenApiSchemaBuilder
  commentId: T:CoreWCF.OpenApi.OpenApiSchemaBuilder
  id: OpenApiSchemaBuilder
  parent: CoreWCF.OpenApi
  children:
  - CoreWCF.OpenApi.OpenApiSchemaBuilder.BuildOpenApiSpecificationDocument(CoreWCF.OpenApi.OpenApiOptions,System.Collections.Generic.IEnumerable{CoreWCF.OpenApi.OpenApiContractInfo})
  langs:
  - csharp
  - vb
  name: OpenApiSchemaBuilder
  nameWithType: OpenApiSchemaBuilder
  fullName: CoreWCF.OpenApi.OpenApiSchemaBuilder
  type: Class
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi
  summary: "\nThis class builds an OpenAPI specification file out of attributes applied to WCF service interfaces.\n"
  syntax:
    content: 'public static class OpenApiSchemaBuilder : Object'
    content.vb: >-
      Public Module OpenApiSchemaBuilder
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: CoreWCF.OpenApi.OpenApiSchemaBuilder.BuildOpenApiSpecificationDocument(CoreWCF.OpenApi.OpenApiOptions,System.Collections.Generic.IEnumerable{CoreWCF.OpenApi.OpenApiContractInfo})
  commentId: M:CoreWCF.OpenApi.OpenApiSchemaBuilder.BuildOpenApiSpecificationDocument(CoreWCF.OpenApi.OpenApiOptions,System.Collections.Generic.IEnumerable{CoreWCF.OpenApi.OpenApiContractInfo})
  id: BuildOpenApiSpecificationDocument(CoreWCF.OpenApi.OpenApiOptions,System.Collections.Generic.IEnumerable{CoreWCF.OpenApi.OpenApiContractInfo})
  parent: CoreWCF.OpenApi.OpenApiSchemaBuilder
  langs:
  - csharp
  - vb
  name: BuildOpenApiSpecificationDocument(OpenApiOptions, IEnumerable<OpenApiContractInfo>)
  nameWithType: OpenApiSchemaBuilder.BuildOpenApiSpecificationDocument(OpenApiOptions, IEnumerable<OpenApiContractInfo>)
  fullName: CoreWCF.OpenApi.OpenApiSchemaBuilder.BuildOpenApiSpecificationDocument(CoreWCF.OpenApi.OpenApiOptions, System.Collections.Generic.IEnumerable<CoreWCF.OpenApi.OpenApiContractInfo>)
  type: Method
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi
  summary: "\nBuild the OpenAPI specification file.\n"
  syntax:
    content: public static OpenApiDocument BuildOpenApiSpecificationDocument(OpenApiOptions info, IEnumerable<OpenApiContractInfo> contracts)
    parameters:
    - id: info
      type: CoreWCF.OpenApi.OpenApiOptions
      description: Top level information about the API.
    - id: contracts
      type: System.Collections.Generic.IEnumerable{CoreWCF.OpenApi.OpenApiContractInfo}
      description: One or more service contracts.
    return:
      type: Microsoft.OpenApi.Models.OpenApiDocument
      description: An OpenAPI specification file.
    content.vb: Public Shared Function BuildOpenApiSpecificationDocument(info As OpenApiOptions, contracts As IEnumerable(Of OpenApiContractInfo)) As OpenApiDocument
  overload: CoreWCF.OpenApi.OpenApiSchemaBuilder.BuildOpenApiSpecificationDocument*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n"
  nameWithType.vb: OpenApiSchemaBuilder.BuildOpenApiSpecificationDocument(OpenApiOptions, IEnumerable(Of OpenApiContractInfo))
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: CoreWCF.OpenApi.OpenApiSchemaBuilder.BuildOpenApiSpecificationDocument(CoreWCF.OpenApi.OpenApiOptions, System.Collections.Generic.IEnumerable(Of CoreWCF.OpenApi.OpenApiContractInfo))
  name.vb: BuildOpenApiSpecificationDocument(OpenApiOptions, IEnumerable(Of OpenApiContractInfo))
references:
- uid: CoreWCF.OpenApi
  commentId: N:CoreWCF.OpenApi
  isExternal: true
  name: CoreWCF.OpenApi
  nameWithType: CoreWCF.OpenApi
  fullName: CoreWCF.OpenApi
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.OpenApi.OpenApiSchemaBuilder.BuildOpenApiSpecificationDocument*
  commentId: Overload:CoreWCF.OpenApi.OpenApiSchemaBuilder.BuildOpenApiSpecificationDocument
  isExternal: true
  name: BuildOpenApiSpecificationDocument
  nameWithType: OpenApiSchemaBuilder.BuildOpenApiSpecificationDocument
  fullName: CoreWCF.OpenApi.OpenApiSchemaBuilder.BuildOpenApiSpecificationDocument
- uid: System.ArgumentNullException
  commentId: T:System.ArgumentNullException
  isExternal: true
- uid: CoreWCF.OpenApi.OpenApiOptions
  commentId: T:CoreWCF.OpenApi.OpenApiOptions
  parent: CoreWCF.OpenApi
  isExternal: true
  name: OpenApiOptions
  nameWithType: OpenApiOptions
  fullName: CoreWCF.OpenApi.OpenApiOptions
- uid: System.Collections.Generic.IEnumerable{CoreWCF.OpenApi.OpenApiContractInfo}
  commentId: '!:System.Collections.Generic.IEnumerable{CoreWCF.OpenApi.OpenApiContractInfo}'
  definition: System.Collections.Generic.IEnumerable`1
  name: IEnumerable<OpenApiContractInfo>
  nameWithType: IEnumerable<OpenApiContractInfo>
  fullName: System.Collections.Generic.IEnumerable<CoreWCF.OpenApi.OpenApiContractInfo>
  nameWithType.vb: IEnumerable(Of OpenApiContractInfo)
  fullName.vb: System.Collections.Generic.IEnumerable(Of CoreWCF.OpenApi.OpenApiContractInfo)
  name.vb: IEnumerable(Of OpenApiContractInfo)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.OpenApi.OpenApiContractInfo
    name: OpenApiContractInfo
    nameWithType: OpenApiContractInfo
    fullName: CoreWCF.OpenApi.OpenApiContractInfo
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.OpenApi.OpenApiContractInfo
    name: OpenApiContractInfo
    nameWithType: OpenApiContractInfo
    fullName: CoreWCF.OpenApi.OpenApiContractInfo
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.OpenApi.Models.OpenApiDocument
  commentId: '!:Microsoft.OpenApi.Models.OpenApiDocument'
  isExternal: true
  name: OpenApiDocument
  nameWithType: OpenApiDocument
  fullName: Microsoft.OpenApi.Models.OpenApiDocument
- uid: System.Collections.Generic.IEnumerable`1
  isExternal: true
  name: IEnumerable<>
  nameWithType: IEnumerable<>
  fullName: System.Collections.Generic.IEnumerable<>
  nameWithType.vb: IEnumerable(Of )
  fullName.vb: System.Collections.Generic.IEnumerable(Of )
  name.vb: IEnumerable(Of )
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
