### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceEndpoint
  commentId: T:CoreWCF.Configuration.ServiceEndpoint
  id: ServiceEndpoint
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceEndpoint.#ctor
  - CoreWCF.Configuration.ServiceEndpoint.Address
  - CoreWCF.Configuration.ServiceEndpoint.Binding
  - CoreWCF.Configuration.ServiceEndpoint.BindingConfiguration
  - CoreWCF.Configuration.ServiceEndpoint.Contract
  - CoreWCF.Configuration.ServiceEndpoint.Name
  - CoreWCF.Configuration.ServiceEndpoint.ServiceName
  langs:
  - csharp
  - vb
  name: ServiceEndpoint
  nameWithType: ServiceEndpoint
  fullName: CoreWCF.Configuration.ServiceEndpoint
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents the endpoint for a service that allows clients of the service to find and communicate with the service.
  remarks: "The service endpoint contains the information about the address, binding, contract, and behavior required by a client to find and interact with the service at this endpoint.  \n\n\n\n"
  syntax:
    content: 'public class ServiceEndpoint : Object'
    content.vb: >-
      Public Class ServiceEndpoint
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.ServiceEndpoint.#ctor
  commentId: M:CoreWCF.Configuration.ServiceEndpoint.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ServiceEndpoint
  langs:
  - csharp
  - vb
  name: ServiceEndpoint()
  nameWithType: ServiceEndpoint.ServiceEndpoint()
  fullName: CoreWCF.Configuration.ServiceEndpoint.ServiceEndpoint()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceEndpoint()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.ServiceEndpoint.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpoint.ServiceName
  commentId: P:CoreWCF.Configuration.ServiceEndpoint.ServiceName
  id: ServiceName
  parent: CoreWCF.Configuration.ServiceEndpoint
  langs:
  - csharp
  - vb
  name: ServiceName
  nameWithType: ServiceEndpoint.ServiceName
  fullName: CoreWCF.Configuration.ServiceEndpoint.ServiceName
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string ServiceName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ServiceName As String
  overload: CoreWCF.Configuration.ServiceEndpoint.ServiceName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpoint.Address
  commentId: P:CoreWCF.Configuration.ServiceEndpoint.Address
  id: Address
  parent: CoreWCF.Configuration.ServiceEndpoint
  langs:
  - csharp
  - vb
  name: Address
  nameWithType: ServiceEndpoint.Address
  fullName: CoreWCF.Configuration.ServiceEndpoint.Address
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public Uri Address { get; set; }
    parameters: []
    return:
      type: System.Uri
    content.vb: Public Property Address As Uri
  overload: CoreWCF.Configuration.ServiceEndpoint.Address*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpoint.Binding
  commentId: P:CoreWCF.Configuration.ServiceEndpoint.Binding
  id: Binding
  parent: CoreWCF.Configuration.ServiceEndpoint
  langs:
  - csharp
  - vb
  name: Binding
  nameWithType: ServiceEndpoint.Binding
  fullName: CoreWCF.Configuration.ServiceEndpoint.Binding
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string Binding { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Binding As String
  overload: CoreWCF.Configuration.ServiceEndpoint.Binding*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpoint.BindingConfiguration
  commentId: P:CoreWCF.Configuration.ServiceEndpoint.BindingConfiguration
  id: BindingConfiguration
  parent: CoreWCF.Configuration.ServiceEndpoint
  langs:
  - csharp
  - vb
  name: BindingConfiguration
  nameWithType: ServiceEndpoint.BindingConfiguration
  fullName: CoreWCF.Configuration.ServiceEndpoint.BindingConfiguration
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string BindingConfiguration { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property BindingConfiguration As String
  overload: CoreWCF.Configuration.ServiceEndpoint.BindingConfiguration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpoint.Name
  commentId: P:CoreWCF.Configuration.ServiceEndpoint.Name
  id: Name
  parent: CoreWCF.Configuration.ServiceEndpoint
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ServiceEndpoint.Name
  fullName: CoreWCF.Configuration.ServiceEndpoint.Name
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: CoreWCF.Configuration.ServiceEndpoint.Name*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceEndpoint.Contract
  commentId: P:CoreWCF.Configuration.ServiceEndpoint.Contract
  id: Contract
  parent: CoreWCF.Configuration.ServiceEndpoint
  langs:
  - csharp
  - vb
  name: Contract
  nameWithType: ServiceEndpoint.Contract
  fullName: CoreWCF.Configuration.ServiceEndpoint.Contract
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public string Contract { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Contract As String
  overload: CoreWCF.Configuration.ServiceEndpoint.Contract*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceEndpoint.#ctor*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpoint.#ctor
  isExternal: true
  name: ServiceEndpoint
  nameWithType: ServiceEndpoint.ServiceEndpoint
  fullName: CoreWCF.Configuration.ServiceEndpoint.ServiceEndpoint
- uid: CoreWCF.Configuration.ServiceEndpoint.ServiceName*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpoint.ServiceName
  isExternal: true
  name: ServiceName
  nameWithType: ServiceEndpoint.ServiceName
  fullName: CoreWCF.Configuration.ServiceEndpoint.ServiceName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.Configuration.ServiceEndpoint.Address*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpoint.Address
  isExternal: true
  name: Address
  nameWithType: ServiceEndpoint.Address
  fullName: CoreWCF.Configuration.ServiceEndpoint.Address
- uid: System.Uri
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: CoreWCF.Configuration.ServiceEndpoint.Binding*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpoint.Binding
  isExternal: true
  name: Binding
  nameWithType: ServiceEndpoint.Binding
  fullName: CoreWCF.Configuration.ServiceEndpoint.Binding
- uid: CoreWCF.Configuration.ServiceEndpoint.BindingConfiguration*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpoint.BindingConfiguration
  isExternal: true
  name: BindingConfiguration
  nameWithType: ServiceEndpoint.BindingConfiguration
  fullName: CoreWCF.Configuration.ServiceEndpoint.BindingConfiguration
- uid: CoreWCF.Configuration.ServiceEndpoint.Name*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpoint.Name
  isExternal: true
  name: Name
  nameWithType: ServiceEndpoint.Name
  fullName: CoreWCF.Configuration.ServiceEndpoint.Name
- uid: CoreWCF.Configuration.ServiceEndpoint.Contract*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpoint.Contract
  isExternal: true
  name: Contract
  nameWithType: ServiceEndpoint.Contract
  fullName: CoreWCF.Configuration.ServiceEndpoint.Contract
