### YamlMime:ManagedReference
items:
- uid: CoreWCF.OpenApi
  commentId: N:CoreWCF.OpenApi
  id: CoreWCF.OpenApi
  children:
  - CoreWCF.OpenApi.OpenApiContractInfo
  - CoreWCF.OpenApi.OpenApiOptions
  - CoreWCF.OpenApi.OpenApiSchemaBuilder
  langs:
  - csharp
  - vb
  name: CoreWCF.OpenApi
  nameWithType: CoreWCF.OpenApi
  fullName: CoreWCF.OpenApi
  type: Namespace
  assemblies:
  - CoreWCF.WebHttp
references:
- uid: CoreWCF.OpenApi.OpenApiContractInfo
  commentId: T:CoreWCF.OpenApi.OpenApiContractInfo
  isExternal: true
  name: OpenApiContractInfo
  nameWithType: OpenApiContractInfo
  fullName: CoreWCF.OpenApi.OpenApiContractInfo
- uid: CoreWCF.OpenApi.OpenApiOptions
  commentId: T:CoreWCF.OpenApi.OpenApiOptions
  parent: CoreWCF.OpenApi
  isExternal: true
  name: OpenApiOptions
  nameWithType: OpenApiOptions
  fullName: CoreWCF.OpenApi.OpenApiOptions
- uid: CoreWCF.OpenApi.OpenApiSchemaBuilder
  commentId: T:CoreWCF.OpenApi.OpenApiSchemaBuilder
  isExternal: true
  name: OpenApiSchemaBuilder
  nameWithType: OpenApiSchemaBuilder
  fullName: CoreWCF.OpenApi.OpenApiSchemaBuilder
- uid: CoreWCF.OpenApi
  commentId: N:CoreWCF.OpenApi
  isExternal: true
  name: CoreWCF.OpenApi
  nameWithType: CoreWCF.OpenApi
  fullName: CoreWCF.OpenApi
