### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.NetHttpWebSocketTransportSettingsElement
  commentId: T:CoreWCF.Configuration.NetHttpWebSocketTransportSettingsElement
  id: NetHttpWebSocketTransportSettingsElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.NetHttpWebSocketTransportSettingsElement.#ctor
  langs:
  - csharp
  - vb
  name: NetHttpWebSocketTransportSettingsElement
  nameWithType: NetHttpWebSocketTransportSettingsElement
  fullName: CoreWCF.Configuration.NetHttpWebSocketTransportSettingsElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents NetHttpWebSocketTransportSettingsElement for WebSocketTransportSettings.
  remarks: To be added.
  syntax:
    content: 'public class NetHttpWebSocketTransportSettingsElement : Object'
    content.vb: >-
      Public Class NetHttpWebSocketTransportSettingsElement
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.NetHttpWebSocketTransportSettingsElement.#ctor
  commentId: M:CoreWCF.Configuration.NetHttpWebSocketTransportSettingsElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.NetHttpWebSocketTransportSettingsElement
  langs:
  - csharp
  - vb
  name: NetHttpWebSocketTransportSettingsElement()
  nameWithType: NetHttpWebSocketTransportSettingsElement.NetHttpWebSocketTransportSettingsElement()
  fullName: CoreWCF.Configuration.NetHttpWebSocketTransportSettingsElement.NetHttpWebSocketTransportSettingsElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public NetHttpWebSocketTransportSettingsElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.NetHttpWebSocketTransportSettingsElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.NetHttpWebSocketTransportSettingsElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.NetHttpWebSocketTransportSettingsElement.#ctor
  isExternal: true
  name: NetHttpWebSocketTransportSettingsElement
  nameWithType: NetHttpWebSocketTransportSettingsElement.NetHttpWebSocketTransportSettingsElement
  fullName: CoreWCF.Configuration.NetHttpWebSocketTransportSettingsElement.NetHttpWebSocketTransportSettingsElement
