### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions
  commentId: T:CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions
  id: ServiceModelWebHostBuilderExtensions
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder)
  - CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Int32)
  - CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Net.IPAddress)
  - CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Net.IPAddress,System.Int32)
  langs:
  - csharp
  - vb
  name: ServiceModelWebHostBuilderExtensions
  nameWithType: ServiceModelWebHostBuilderExtensions
  fullName: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions
  type: Class
  source:
    path: CoreWCF.NetTcp
    isExternal: true
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public static class ServiceModelWebHostBuilderExtensions : Object'
    content.vb: >-
      Public Module ServiceModelWebHostBuilderExtensions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder)
  commentId: M:CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder)
  id: UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder)
  isExtensionMethod: true
  parent: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions
  langs:
  - csharp
  - vb
  name: UseNetTcp(IWebHostBuilder)
  nameWithType: ServiceModelWebHostBuilderExtensions.UseNetTcp(IWebHostBuilder)
  fullName: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder)
  type: Method
  source:
    path: CoreWCF.NetTcp
    isExternal: true
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  syntax:
    content: public static IWebHostBuilder UseNetTcp(this IWebHostBuilder webHostBuilder)
    parameters:
    - id: webHostBuilder
      type: Microsoft.AspNetCore.Hosting.IWebHostBuilder
    return:
      type: Microsoft.AspNetCore.Hosting.IWebHostBuilder
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function UseNetTcp(webHostBuilder As IWebHostBuilder) As IWebHostBuilder
  overload: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Int32)
  commentId: M:CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Int32)
  id: UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Int32)
  isExtensionMethod: true
  parent: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions
  langs:
  - csharp
  - vb
  name: UseNetTcp(IWebHostBuilder, Int32)
  nameWithType: ServiceModelWebHostBuilderExtensions.UseNetTcp(IWebHostBuilder, Int32)
  fullName: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder, System.Int32)
  type: Method
  source:
    path: CoreWCF.NetTcp
    isExternal: true
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  syntax:
    content: public static IWebHostBuilder UseNetTcp(this IWebHostBuilder webHostBuilder, int port)
    parameters:
    - id: webHostBuilder
      type: Microsoft.AspNetCore.Hosting.IWebHostBuilder
    - id: port
      type: System.Int32
    return:
      type: Microsoft.AspNetCore.Hosting.IWebHostBuilder
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function UseNetTcp(webHostBuilder As IWebHostBuilder, port As Integer) As IWebHostBuilder
  overload: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Net.IPAddress)
  commentId: M:CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Net.IPAddress)
  id: UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Net.IPAddress)
  isExtensionMethod: true
  parent: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions
  langs:
  - csharp
  - vb
  name: UseNetTcp(IWebHostBuilder, IPAddress)
  nameWithType: ServiceModelWebHostBuilderExtensions.UseNetTcp(IWebHostBuilder, IPAddress)
  fullName: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder, System.Net.IPAddress)
  type: Method
  source:
    path: CoreWCF.NetTcp
    isExternal: true
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  syntax:
    content: public static IWebHostBuilder UseNetTcp(this IWebHostBuilder webHostBuilder, IPAddress ipAddress)
    parameters:
    - id: webHostBuilder
      type: Microsoft.AspNetCore.Hosting.IWebHostBuilder
    - id: ipAddress
      type: System.Net.IPAddress
    return:
      type: Microsoft.AspNetCore.Hosting.IWebHostBuilder
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function UseNetTcp(webHostBuilder As IWebHostBuilder, ipAddress As IPAddress) As IWebHostBuilder
  overload: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Net.IPAddress,System.Int32)
  commentId: M:CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Net.IPAddress,System.Int32)
  id: UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder,System.Net.IPAddress,System.Int32)
  isExtensionMethod: true
  parent: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions
  langs:
  - csharp
  - vb
  name: UseNetTcp(IWebHostBuilder, IPAddress, Int32)
  nameWithType: ServiceModelWebHostBuilderExtensions.UseNetTcp(IWebHostBuilder, IPAddress, Int32)
  fullName: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp(Microsoft.AspNetCore.Hosting.IWebHostBuilder, System.Net.IPAddress, System.Int32)
  type: Method
  source:
    path: CoreWCF.NetTcp
    isExternal: true
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  syntax:
    content: public static IWebHostBuilder UseNetTcp(this IWebHostBuilder webHostBuilder, IPAddress ipAddress, int port)
    parameters:
    - id: webHostBuilder
      type: Microsoft.AspNetCore.Hosting.IWebHostBuilder
    - id: ipAddress
      type: System.Net.IPAddress
    - id: port
      type: System.Int32
    return:
      type: Microsoft.AspNetCore.Hosting.IWebHostBuilder
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function UseNetTcp(webHostBuilder As IWebHostBuilder, ipAddress As IPAddress, port As Integer) As IWebHostBuilder
  overload: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp*
  commentId: Overload:CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp
  isExternal: true
  name: UseNetTcp
  nameWithType: ServiceModelWebHostBuilderExtensions.UseNetTcp
  fullName: CoreWCF.Configuration.ServiceModelWebHostBuilderExtensions.UseNetTcp
- uid: Microsoft.AspNetCore.Hosting.IWebHostBuilder
  isExternal: true
  name: IWebHostBuilder
  nameWithType: IWebHostBuilder
  fullName: Microsoft.AspNetCore.Hosting.IWebHostBuilder
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.IPAddress
  isExternal: true
  name: IPAddress
  nameWithType: IPAddress
  fullName: System.Net.IPAddress
