### YamlMime:ManagedReference
items:
- uid: CoreWCF.BasicHttpMessageSecurity
  commentId: T:CoreWCF.BasicHttpMessageSecurity
  id: BasicHttpMessageSecurity
  parent: CoreWCF
  children:
  - CoreWCF.BasicHttpMessageSecurity.#ctor
  - CoreWCF.BasicHttpMessageSecurity.AlgorithmSuite
  - CoreWCF.BasicHttpMessageSecurity.ClientCredentialType
  - CoreWCF.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
  - CoreWCF.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
  langs:
  - csharp
  - vb
  name: BasicHttpMessageSecurity
  nameWithType: BasicHttpMessageSecurity
  fullName: CoreWCF.BasicHttpMessageSecurity
  type: Class
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  summary: "Configures message-level security settings for <xref:CoreWCF.BasicHttpBinding>."
  syntax:
    content: 'public sealed class BasicHttpMessageSecurity : Object'
    content.vb: >-
      Public NotInheritable Class BasicHttpMessageSecurity

          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.BasicHttpMessageSecurity.#ctor
  commentId: M:CoreWCF.BasicHttpMessageSecurity.#ctor
  id: '#ctor'
  parent: CoreWCF.BasicHttpMessageSecurity
  langs:
  - csharp
  - vb
  name: BasicHttpMessageSecurity()
  nameWithType: BasicHttpMessageSecurity.BasicHttpMessageSecurity()
  fullName: CoreWCF.BasicHttpMessageSecurity.BasicHttpMessageSecurity()
  type: Constructor
  summary: "Initializes a new instance of the <xref:CoreWCF.BasicHttpMessageSecurity> class."
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public BasicHttpMessageSecurity()
    content.vb: Public Sub New
  overload: CoreWCF.BasicHttpMessageSecurity.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
  commentId: M:CoreWCF.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
  id: ShouldSerializeAlgorithmSuite
  parent: CoreWCF.BasicHttpMessageSecurity
  langs:
  - csharp
  - vb
  name: ShouldSerializeAlgorithmSuite()
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite()
  fullName: CoreWCF.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite()
  type: Method
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public bool ShouldSerializeAlgorithmSuite()
    return:
      type: System.Boolean
    content.vb: Public Function ShouldSerializeAlgorithmSuite As Boolean
  overload: CoreWCF.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
  commentId: M:CoreWCF.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
  id: ShouldSerializeClientCredentialType
  parent: CoreWCF.BasicHttpMessageSecurity
  langs:
  - csharp
  - vb
  name: ShouldSerializeClientCredentialType()
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeClientCredentialType()
  fullName: CoreWCF.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType()
  type: Method
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  syntax:
    content: public bool ShouldSerializeClientCredentialType()
    return:
      type: System.Boolean
    content.vb: Public Function ShouldSerializeClientCredentialType As Boolean
  overload: CoreWCF.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.BasicHttpMessageSecurity.ClientCredentialType
  commentId: P:CoreWCF.BasicHttpMessageSecurity.ClientCredentialType
  id: ClientCredentialType
  parent: CoreWCF.BasicHttpMessageSecurity
  langs:
  - csharp
  - vb
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurity.ClientCredentialType
  fullName: CoreWCF.BasicHttpMessageSecurity.ClientCredentialType
  type: Property
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  summary: Specifies the type of credential with which the client authenticates.
  syntax:
    content: public BasicHttpMessageCredentialType ClientCredentialType { get; set; }
    parameters: []
    return:
      type: CoreWCF.BasicHttpMessageCredentialType
      description: "A member of the <xref:CoreWCF.BasicHttpMessageCredentialType> enumeration. The default value is <xref:CoreWCF.BasicHttpMessageCredentialType.UserName>."
    content.vb: Public Property ClientCredentialType As BasicHttpMessageCredentialType
  overload: CoreWCF.BasicHttpMessageSecurity.ClientCredentialType*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  remarks: "The return value can be one of the following enumeration members:\n* <xref: CoreWCF.BasicHttpMessageCredentialType.Certificate>\n \n* <xref: CoreWCF.BasicHttpMessageCredentialType.UserName>\n"
- uid: CoreWCF.BasicHttpMessageSecurity.AlgorithmSuite
  commentId: P:CoreWCF.BasicHttpMessageSecurity.AlgorithmSuite
  id: AlgorithmSuite
  parent: CoreWCF.BasicHttpMessageSecurity
  langs:
  - csharp
  - vb
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurity.AlgorithmSuite
  fullName: CoreWCF.BasicHttpMessageSecurity.AlgorithmSuite
  type: Property
  source:
    path: CoreWCF.Http
    isExternal: true
  assemblies:
  - CoreWCF.Http
  namespace: CoreWCF
  summary: "Specifies the algorithm suite to use with <xref:CoreWCF.BasicHttpMessageSecurity>"
  syntax:
    content: public SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    parameters: []
    return:
      type: CoreWCF.Security.SecurityAlgorithmSuite
      description: "A <xref:CoreWCF.Security.SecurityAlgorithmSuite>. The default value is <xref:CoreWCF.Security.SecurityAlgorithmSuite.Basic256>."
    content.vb: Public Property AlgorithmSuite As SecurityAlgorithmSuite
  overload: CoreWCF.BasicHttpMessageSecurity.AlgorithmSuite*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  remarks: "The <xref:CoreWCF.Security.SecurityAlgorithmSuite> object that is returned contains numerous properties that specify security algorithms to use in specific conditions. It also describes various security capabilities of the service"
references:
- uid: CoreWCF
  commentId: N:CoreWCF
  isExternal: true
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.BasicHttpMessageSecurity.#ctor*
  commentId: Overload:CoreWCF.BasicHttpMessageSecurity.#ctor
  isExternal: true
  name: BasicHttpMessageSecurity
  nameWithType: BasicHttpMessageSecurity.BasicHttpMessageSecurity
  fullName: CoreWCF.BasicHttpMessageSecurity.BasicHttpMessageSecurity
- uid: CoreWCF.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite*
  commentId: Overload:CoreWCF.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
  isExternal: true
  name: ShouldSerializeAlgorithmSuite
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
  fullName: CoreWCF.BasicHttpMessageSecurity.ShouldSerializeAlgorithmSuite
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: CoreWCF.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType*
  commentId: Overload:CoreWCF.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
  isExternal: true
  name: ShouldSerializeClientCredentialType
  nameWithType: BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
  fullName: CoreWCF.BasicHttpMessageSecurity.ShouldSerializeClientCredentialType
- uid: CoreWCF.BasicHttpMessageSecurity.ClientCredentialType*
  commentId: Overload:CoreWCF.BasicHttpMessageSecurity.ClientCredentialType
  isExternal: true
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurity.ClientCredentialType
  fullName: CoreWCF.BasicHttpMessageSecurity.ClientCredentialType
- uid: CoreWCF.BasicHttpMessageCredentialType
  commentId: T:CoreWCF.BasicHttpMessageCredentialType
  parent: CoreWCF
  isExternal: true
  name: BasicHttpMessageCredentialType
  nameWithType: BasicHttpMessageCredentialType
  fullName: CoreWCF.BasicHttpMessageCredentialType
- uid: CoreWCF.BasicHttpMessageSecurity.AlgorithmSuite*
  commentId: Overload:CoreWCF.BasicHttpMessageSecurity.AlgorithmSuite
  isExternal: true
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurity.AlgorithmSuite
  fullName: CoreWCF.BasicHttpMessageSecurity.AlgorithmSuite
- uid: CoreWCF.Security.SecurityAlgorithmSuite
  commentId: T:CoreWCF.Security.SecurityAlgorithmSuite
  parent: CoreWCF.Security
  isExternal: true
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: CoreWCF.Security.SecurityAlgorithmSuite
- uid: CoreWCF.Security
  commentId: N:CoreWCF.Security
  isExternal: true
  name: CoreWCF.Security
  nameWithType: CoreWCF.Security
  fullName: CoreWCF.Security
