### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceEndpointElementCollection
  commentId: T:CoreWCF.Configuration.ServiceEndpointElementCollection
  id: ServiceEndpointElementCollection
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceEndpointElementCollection.#ctor
  - CoreWCF.Configuration.ServiceEndpointElementCollection.CreateNewElement
  - CoreWCF.Configuration.ServiceEndpointElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  - vb
  name: ServiceEndpointElementCollection
  nameWithType: ServiceEndpointElementCollection
  fullName: CoreWCF.Configuration.ServiceEndpointElementCollection
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a collection of  instances. This class cannot be inherited.
  remarks: To be added.
  syntax:
    content: 'public class ServiceEndpointElementCollection : ConfigurationElementCollection'
    content.vb: >-
      Public Class ServiceEndpointElementCollection
          Inherits ConfigurationElementCollection
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.ServiceEndpointElementCollection.CreateNewElement
  commentId: M:CoreWCF.Configuration.ServiceEndpointElementCollection.CreateNewElement
  id: CreateNewElement
  parent: CoreWCF.Configuration.ServiceEndpointElementCollection
  langs:
  - csharp
  - vb
  name: CreateNewElement()
  nameWithType: ServiceEndpointElementCollection.CreateNewElement()
  fullName: CoreWCF.Configuration.ServiceEndpointElementCollection.CreateNewElement()
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override ConfigurationElement CreateNewElement()
    return:
      type: System.Configuration.ConfigurationElement
    content.vb: Protected Overrides Function CreateNewElement As ConfigurationElement
  overload: CoreWCF.Configuration.ServiceEndpointElementCollection.CreateNewElement*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: CoreWCF.Configuration.ServiceEndpointElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  commentId: M:CoreWCF.Configuration.ServiceEndpointElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: CoreWCF.Configuration.ServiceEndpointElementCollection
  langs:
  - csharp
  - vb
  name: GetElementKey(ConfigurationElement)
  nameWithType: ServiceEndpointElementCollection.GetElementKey(ConfigurationElement)
  fullName: CoreWCF.Configuration.ServiceEndpointElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override object GetElementKey(ConfigurationElement element)
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
    return:
      type: System.Object
    content.vb: Protected Overrides Function GetElementKey(element As ConfigurationElement) As Object
  overload: CoreWCF.Configuration.ServiceEndpointElementCollection.GetElementKey*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: CoreWCF.Configuration.ServiceEndpointElementCollection.#ctor
  commentId: M:CoreWCF.Configuration.ServiceEndpointElementCollection.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ServiceEndpointElementCollection
  langs:
  - csharp
  - vb
  name: ServiceEndpointElementCollection()
  nameWithType: ServiceEndpointElementCollection.ServiceEndpointElementCollection()
  fullName: CoreWCF.Configuration.ServiceEndpointElementCollection.ServiceEndpointElementCollection()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceEndpointElementCollection()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.ServiceEndpointElementCollection.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceEndpointElementCollection.CreateNewElement*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElementCollection.CreateNewElement
  isExternal: true
  name: CreateNewElement
  nameWithType: ServiceEndpointElementCollection.CreateNewElement
  fullName: CoreWCF.Configuration.ServiceEndpointElementCollection.CreateNewElement
- uid: System.Configuration.ConfigurationElement
  isExternal: true
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: CoreWCF.Configuration.ServiceEndpointElementCollection.GetElementKey*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElementCollection.GetElementKey
  isExternal: true
  name: GetElementKey
  nameWithType: ServiceEndpointElementCollection.GetElementKey
  fullName: CoreWCF.Configuration.ServiceEndpointElementCollection.GetElementKey
- uid: CoreWCF.Configuration.ServiceEndpointElementCollection.#ctor*
  commentId: Overload:CoreWCF.Configuration.ServiceEndpointElementCollection.#ctor
  isExternal: true
  name: ServiceEndpointElementCollection
  nameWithType: ServiceEndpointElementCollection.ServiceEndpointElementCollection
  fullName: CoreWCF.Configuration.ServiceEndpointElementCollection.ServiceEndpointElementCollection
