### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.BasicHttpSecurityElement
  commentId: T:CoreWCF.Configuration.BasicHttpSecurityElement
  id: BasicHttpSecurityElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.BasicHttpSecurityElement.#ctor
  - CoreWCF.Configuration.BasicHttpSecurityElement.Message
  - CoreWCF.Configuration.BasicHttpSecurityElement.Mode
  - CoreWCF.Configuration.BasicHttpSecurityElement.Transport
  langs:
  - csharp
  - vb
  name: BasicHttpSecurityElement
  nameWithType: BasicHttpSecurityElement
  fullName: CoreWCF.Configuration.BasicHttpSecurityElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents an XML element that configures the security for a basic HTTP service.
  syntax:
    content: 'public class BasicHttpSecurityElement : ServiceModelConfigurationElement'
    content.vb: >-
      Public Class BasicHttpSecurityElement
          Inherits ServiceModelConfigurationElement
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElement
  inheritedMembers:
  - CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.BasicHttpSecurityElement.#ctor
  commentId: M:CoreWCF.Configuration.BasicHttpSecurityElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.BasicHttpSecurityElement
  langs:
  - csharp
  - vb
  name: BasicHttpSecurityElement()
  summary: Initializes a new instance of the [BasicHttpSecurityElement](xref:CoreWCF.Configuration.BasicHttpSecurityElement) class.
  nameWithType: BasicHttpSecurityElement.BasicHttpSecurityElement()
  fullName: CoreWCF.Configuration.BasicHttpSecurityElement.BasicHttpSecurityElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public BasicHttpSecurityElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.BasicHttpSecurityElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.BasicHttpSecurityElement.Mode
  commentId: P:CoreWCF.Configuration.BasicHttpSecurityElement.Mode
  id: Mode
  parent: CoreWCF.Configuration.BasicHttpSecurityElement
  langs:
  - csharp
  - vb
  name: Mode
  description: Gets or sets an XML element that specifies the security mode for a basic HTTP service.
  nameWithType: BasicHttpSecurityElement.Mode
  fullName: CoreWCF.Configuration.BasicHttpSecurityElement.Mode
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public BasicHttpSecurityMode Mode { get; set; }
    parameters: []
    return:
      type: CoreWCF.Channels.BasicHttpSecurityMode
      description: The security mode for a basic HTTP service.
    content.vb: Public Property Mode As BasicHttpSecurityMode
  overload: CoreWCF.Configuration.BasicHttpSecurityElement.Mode*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.BasicHttpSecurityElement.Transport
  commentId: P:CoreWCF.Configuration.BasicHttpSecurityElement.Transport
  id: Transport
  parent: CoreWCF.Configuration.BasicHttpSecurityElement
  langs:
  - csharp
  - vb
  name: Transport
  nameWithType: BasicHttpSecurityElement.Transport
  fullName: CoreWCF.Configuration.BasicHttpSecurityElement.Transport
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public HttpTransportSecurityElement Transport { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.HttpTransportSecurityElement
    content.vb: Public ReadOnly Property Transport As HttpTransportSecurityElement
  overload: CoreWCF.Configuration.BasicHttpSecurityElement.Transport*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: CoreWCF.Configuration.BasicHttpSecurityElement.Message
  commentId: P:CoreWCF.Configuration.BasicHttpSecurityElement.Message
  id: Message
  parent: CoreWCF.Configuration.BasicHttpSecurityElement
  langs:
  - csharp
  - vb
  name: Message
  summary: Gets an XML element that configures the message security for a basic HTTP service.
  nameWithType: BasicHttpSecurityElement.Message
  fullName: CoreWCF.Configuration.BasicHttpSecurityElement.Message
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public BasicHttpMessageSecurityElement Message { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.BasicHttpMessageSecurityElement
      description: An XML element that configures the message security for a basic HTTP service.
    content.vb: Public ReadOnly Property Message As BasicHttpMessageSecurityElement
  overload: CoreWCF.Configuration.BasicHttpSecurityElement.Message*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: CoreWCF.Configuration.ServiceModelConfigurationElement
  definition: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  isExternal: true
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.BasicHttpSecurityElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.BasicHttpSecurityElement.#ctor
  isExternal: true
  name: BasicHttpSecurityElement
  nameWithType: BasicHttpSecurityElement.BasicHttpSecurityElement
  fullName: CoreWCF.Configuration.BasicHttpSecurityElement.BasicHttpSecurityElement
- uid: CoreWCF.Configuration.BasicHttpSecurityElement.Mode*
  commentId: Overload:CoreWCF.Configuration.BasicHttpSecurityElement.Mode
  isExternal: true
  name: Mode
  nameWithType: BasicHttpSecurityElement.Mode
  fullName: CoreWCF.Configuration.BasicHttpSecurityElement.Mode
- uid: CoreWCF.Channels.BasicHttpSecurityMode
  commentId: T:CoreWCF.Channels.BasicHttpSecurityMode
  parent: CoreWCF.Channels
  isExternal: true
  name: BasicHttpSecurityMode
  nameWithType: BasicHttpSecurityMode
  fullName: CoreWCF.Channels.BasicHttpSecurityMode
- uid: CoreWCF.Channels
  commentId: N:CoreWCF.Channels
  isExternal: true
  name: CoreWCF.Channels
  nameWithType: CoreWCF.Channels
  fullName: CoreWCF.Channels
- uid: CoreWCF.Configuration.BasicHttpSecurityElement.Transport*
  commentId: Overload:CoreWCF.Configuration.BasicHttpSecurityElement.Transport
  isExternal: true
  name: Transport
  nameWithType: BasicHttpSecurityElement.Transport
  fullName: CoreWCF.Configuration.BasicHttpSecurityElement.Transport
- uid: CoreWCF.Configuration.HttpTransportSecurityElement
  commentId: T:CoreWCF.Configuration.HttpTransportSecurityElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: HttpTransportSecurityElement
  nameWithType: HttpTransportSecurityElement
  fullName: CoreWCF.Configuration.HttpTransportSecurityElement
- uid: CoreWCF.Configuration.BasicHttpSecurityElement.Message*
  commentId: Overload:CoreWCF.Configuration.BasicHttpSecurityElement.Message
  isExternal: true
  name: Message
  nameWithType: BasicHttpSecurityElement.Message
  fullName: CoreWCF.Configuration.BasicHttpSecurityElement.Message
- uid: CoreWCF.Configuration.BasicHttpMessageSecurityElement
  commentId: T:CoreWCF.Configuration.BasicHttpMessageSecurityElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: BasicHttpMessageSecurityElement
  nameWithType: BasicHttpMessageSecurityElement
  fullName: CoreWCF.Configuration.BasicHttpMessageSecurityElement
