### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceNameElementCollection
  commentId: T:CoreWCF.Configuration.ServiceNameElementCollection
  id: ServiceNameElementCollection
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceNameElementCollection.#ctor
  - CoreWCF.Configuration.ServiceNameElementCollection.Add(CoreWCF.Configuration.ServiceNameElement)
  - CoreWCF.Configuration.ServiceNameElementCollection.Clear
  - CoreWCF.Configuration.ServiceNameElementCollection.CreateNewElement
  - CoreWCF.Configuration.ServiceNameElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - CoreWCF.Configuration.ServiceNameElementCollection.IndexOf(CoreWCF.Configuration.ServiceNameElement)
  - CoreWCF.Configuration.ServiceNameElementCollection.Item(System.Int32)
  - CoreWCF.Configuration.ServiceNameElementCollection.Item(System.String)
  - CoreWCF.Configuration.ServiceNameElementCollection.Remove(CoreWCF.Configuration.ServiceNameElement)
  - CoreWCF.Configuration.ServiceNameElementCollection.Remove(System.String)
  - CoreWCF.Configuration.ServiceNameElementCollection.RemoveAt(System.Int32)
  langs:
  - csharp
  - vb
  name: ServiceNameElementCollection
  nameWithType: ServiceNameElementCollection
  fullName: CoreWCF.Configuration.ServiceNameElementCollection
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: The  class is a collection of service principal names that represent a configuration element for an .
  remarks: To be added.
  syntax:
    content: 'public sealed class ServiceNameElementCollection : ConfigurationElementCollection'
    content.vb: >-
      Public NotInheritable Class ServiceNameElementCollection
          Inherits ConfigurationElementCollection
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.ServiceNameElementCollection.Add(CoreWCF.Configuration.ServiceNameElement)
  commentId: M:CoreWCF.Configuration.ServiceNameElementCollection.Add(CoreWCF.Configuration.ServiceNameElement)
  id: Add(CoreWCF.Configuration.ServiceNameElement)
  parent: CoreWCF.Configuration.ServiceNameElementCollection
  langs:
  - csharp
  - vb
  name: Add(ServiceNameElement)
  nameWithType: ServiceNameElementCollection.Add(ServiceNameElement)
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.Add(CoreWCF.Configuration.ServiceNameElement)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public void Add(ServiceNameElement element)
    parameters:
    - id: element
      type: CoreWCF.Configuration.ServiceNameElement
    content.vb: Public Sub Add(element As ServiceNameElement)
  overload: CoreWCF.Configuration.ServiceNameElementCollection.Add*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceNameElementCollection.Clear
  commentId: M:CoreWCF.Configuration.ServiceNameElementCollection.Clear
  id: Clear
  parent: CoreWCF.Configuration.ServiceNameElementCollection
  langs:
  - csharp
  - vb
  name: Clear()
  nameWithType: ServiceNameElementCollection.Clear()
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.Clear()
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public void Clear()
    content.vb: Public Sub Clear
  overload: CoreWCF.Configuration.ServiceNameElementCollection.Clear*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceNameElementCollection.CreateNewElement
  commentId: M:CoreWCF.Configuration.ServiceNameElementCollection.CreateNewElement
  id: CreateNewElement
  parent: CoreWCF.Configuration.ServiceNameElementCollection
  langs:
  - csharp
  - vb
  name: CreateNewElement()
  nameWithType: ServiceNameElementCollection.CreateNewElement()
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.CreateNewElement()
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override ConfigurationElement CreateNewElement()
    return:
      type: System.Configuration.ConfigurationElement
    content.vb: Protected Overrides Function CreateNewElement As ConfigurationElement
  overload: CoreWCF.Configuration.ServiceNameElementCollection.CreateNewElement*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: CoreWCF.Configuration.ServiceNameElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  commentId: M:CoreWCF.Configuration.ServiceNameElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: CoreWCF.Configuration.ServiceNameElementCollection
  langs:
  - csharp
  - vb
  name: GetElementKey(ConfigurationElement)
  nameWithType: ServiceNameElementCollection.GetElementKey(ConfigurationElement)
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override object GetElementKey(ConfigurationElement element)
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
    return:
      type: System.Object
    content.vb: Protected Overrides Function GetElementKey(element As ConfigurationElement) As Object
  overload: CoreWCF.Configuration.ServiceNameElementCollection.GetElementKey*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: CoreWCF.Configuration.ServiceNameElementCollection.IndexOf(CoreWCF.Configuration.ServiceNameElement)
  commentId: M:CoreWCF.Configuration.ServiceNameElementCollection.IndexOf(CoreWCF.Configuration.ServiceNameElement)
  id: IndexOf(CoreWCF.Configuration.ServiceNameElement)
  parent: CoreWCF.Configuration.ServiceNameElementCollection
  langs:
  - csharp
  - vb
  name: IndexOf(ServiceNameElement)
  nameWithType: ServiceNameElementCollection.IndexOf(ServiceNameElement)
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.IndexOf(CoreWCF.Configuration.ServiceNameElement)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public int IndexOf(ServiceNameElement element)
    parameters:
    - id: element
      type: CoreWCF.Configuration.ServiceNameElement
    return:
      type: System.Int32
    content.vb: Public Function IndexOf(element As ServiceNameElement) As Integer
  overload: CoreWCF.Configuration.ServiceNameElementCollection.IndexOf*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceNameElementCollection.Remove(CoreWCF.Configuration.ServiceNameElement)
  commentId: M:CoreWCF.Configuration.ServiceNameElementCollection.Remove(CoreWCF.Configuration.ServiceNameElement)
  id: Remove(CoreWCF.Configuration.ServiceNameElement)
  parent: CoreWCF.Configuration.ServiceNameElementCollection
  langs:
  - csharp
  - vb
  name: Remove(ServiceNameElement)
  nameWithType: ServiceNameElementCollection.Remove(ServiceNameElement)
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.Remove(CoreWCF.Configuration.ServiceNameElement)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public void Remove(ServiceNameElement element)
    parameters:
    - id: element
      type: CoreWCF.Configuration.ServiceNameElement
    content.vb: Public Sub Remove(element As ServiceNameElement)
  overload: CoreWCF.Configuration.ServiceNameElementCollection.Remove*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceNameElementCollection.Remove(System.String)
  commentId: M:CoreWCF.Configuration.ServiceNameElementCollection.Remove(System.String)
  id: Remove(System.String)
  parent: CoreWCF.Configuration.ServiceNameElementCollection
  langs:
  - csharp
  - vb
  name: Remove(String)
  nameWithType: ServiceNameElementCollection.Remove(String)
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.Remove(System.String)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public void Remove(string name)
    parameters:
    - id: name
      type: System.String
    content.vb: Public Sub Remove(name As String)
  overload: CoreWCF.Configuration.ServiceNameElementCollection.Remove*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceNameElementCollection.RemoveAt(System.Int32)
  commentId: M:CoreWCF.Configuration.ServiceNameElementCollection.RemoveAt(System.Int32)
  id: RemoveAt(System.Int32)
  parent: CoreWCF.Configuration.ServiceNameElementCollection
  langs:
  - csharp
  - vb
  name: RemoveAt(Int32)
  nameWithType: ServiceNameElementCollection.RemoveAt(Int32)
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.RemoveAt(System.Int32)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public void RemoveAt(int index)
    parameters:
    - id: index
      type: System.Int32
    content.vb: Public Sub RemoveAt(index As Integer)
  overload: CoreWCF.Configuration.ServiceNameElementCollection.RemoveAt*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceNameElementCollection.#ctor
  commentId: M:CoreWCF.Configuration.ServiceNameElementCollection.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ServiceNameElementCollection
  langs:
  - csharp
  - vb
  name: ServiceNameElementCollection()
  nameWithType: ServiceNameElementCollection.ServiceNameElementCollection()
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.ServiceNameElementCollection()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceNameElementCollection()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.ServiceNameElementCollection.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceNameElementCollection.Item(System.Int32)
  commentId: P:CoreWCF.Configuration.ServiceNameElementCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: CoreWCF.Configuration.ServiceNameElementCollection
  langs:
  - csharp
  - vb
  name: Item[Int32]
  nameWithType: ServiceNameElementCollection.Item[Int32]
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.Item[System.Int32]
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceNameElement this[int index] { get; set; }
    parameters:
    - id: index
      type: System.Int32
    return:
      type: CoreWCF.Configuration.ServiceNameElement
    content.vb: Public Property Item(index As Integer) As ServiceNameElement
  overload: CoreWCF.Configuration.ServiceNameElementCollection.Item*
  nameWithType.vb: ServiceNameElementCollection.Item(Int32)
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  fullName.vb: CoreWCF.Configuration.ServiceNameElementCollection.Item(System.Int32)
  name.vb: Item(Int32)
- uid: CoreWCF.Configuration.ServiceNameElementCollection.Item(System.String)
  commentId: P:CoreWCF.Configuration.ServiceNameElementCollection.Item(System.String)
  id: Item(System.String)
  parent: CoreWCF.Configuration.ServiceNameElementCollection
  langs:
  - csharp
  - vb
  name: Item[String]
  nameWithType: ServiceNameElementCollection.Item[String]
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.Item[System.String]
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceNameElement this[string name] { get; set; }
    parameters:
    - id: name
      type: System.String
    return:
      type: CoreWCF.Configuration.ServiceNameElement
    content.vb: Public Property Item(name As String) As ServiceNameElement
  overload: CoreWCF.Configuration.ServiceNameElementCollection.Item*
  nameWithType.vb: ServiceNameElementCollection.Item(String)
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
  fullName.vb: CoreWCF.Configuration.ServiceNameElementCollection.Item(System.String)
  name.vb: Item(String)
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceNameElementCollection.Add*
  commentId: Overload:CoreWCF.Configuration.ServiceNameElementCollection.Add
  isExternal: true
  name: Add
  nameWithType: ServiceNameElementCollection.Add
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.Add
- uid: CoreWCF.Configuration.ServiceNameElement
  commentId: T:CoreWCF.Configuration.ServiceNameElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceNameElement
  nameWithType: ServiceNameElement
  fullName: CoreWCF.Configuration.ServiceNameElement
- uid: CoreWCF.Configuration.ServiceNameElementCollection.Clear*
  commentId: Overload:CoreWCF.Configuration.ServiceNameElementCollection.Clear
  isExternal: true
  name: Clear
  nameWithType: ServiceNameElementCollection.Clear
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.Clear
- uid: CoreWCF.Configuration.ServiceNameElementCollection.CreateNewElement*
  commentId: Overload:CoreWCF.Configuration.ServiceNameElementCollection.CreateNewElement
  isExternal: true
  name: CreateNewElement
  nameWithType: ServiceNameElementCollection.CreateNewElement
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.CreateNewElement
- uid: System.Configuration.ConfigurationElement
  isExternal: true
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: CoreWCF.Configuration.ServiceNameElementCollection.GetElementKey*
  commentId: Overload:CoreWCF.Configuration.ServiceNameElementCollection.GetElementKey
  isExternal: true
  name: GetElementKey
  nameWithType: ServiceNameElementCollection.GetElementKey
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.GetElementKey
- uid: CoreWCF.Configuration.ServiceNameElementCollection.IndexOf*
  commentId: Overload:CoreWCF.Configuration.ServiceNameElementCollection.IndexOf
  isExternal: true
  name: IndexOf
  nameWithType: ServiceNameElementCollection.IndexOf
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.IndexOf
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: CoreWCF.Configuration.ServiceNameElementCollection.Remove*
  commentId: Overload:CoreWCF.Configuration.ServiceNameElementCollection.Remove
  isExternal: true
  name: Remove
  nameWithType: ServiceNameElementCollection.Remove
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.Remove
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.Configuration.ServiceNameElementCollection.RemoveAt*
  commentId: Overload:CoreWCF.Configuration.ServiceNameElementCollection.RemoveAt
  isExternal: true
  name: RemoveAt
  nameWithType: ServiceNameElementCollection.RemoveAt
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.RemoveAt
- uid: CoreWCF.Configuration.ServiceNameElementCollection.#ctor*
  commentId: Overload:CoreWCF.Configuration.ServiceNameElementCollection.#ctor
  isExternal: true
  name: ServiceNameElementCollection
  nameWithType: ServiceNameElementCollection.ServiceNameElementCollection
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.ServiceNameElementCollection
- uid: CoreWCF.Configuration.ServiceNameElementCollection.Item*
  commentId: Overload:CoreWCF.Configuration.ServiceNameElementCollection.Item
  isExternal: true
  name: Item
  nameWithType: ServiceNameElementCollection.Item
  fullName: CoreWCF.Configuration.ServiceNameElementCollection.Item
