### YamlMime:ManagedReference
items:
- uid: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute
  id: OpenApiBasePathAttribute
  parent: CoreWCF.OpenApi.Attributes
  children:
  - CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.#ctor(System.String)
  - CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.BasePath
  langs:
  - csharp
  - vb
  name: OpenApiBasePathAttribute
  nameWithType: OpenApiBasePathAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute
  type: Class
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nAttribute to denote base path for the API.\n"
  syntax:
    content: 'public sealed class OpenApiBasePathAttribute : Attribute'
    content.vb: >-
      Public NotInheritable Class OpenApiBasePathAttribute
          Inherits Attribute
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.#ctor(System.String)
  commentId: M:CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute
  langs:
  - csharp
  - vb
  name: OpenApiBasePathAttribute(String)
  nameWithType: OpenApiBasePathAttribute.OpenApiBasePathAttribute(String)
  fullName: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.OpenApiBasePathAttribute(System.String)
  type: Constructor
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nConstructor.\n"
  syntax:
    content: public OpenApiBasePathAttribute(string basePath)
    parameters:
    - id: basePath
      type: System.String
      description: Base path for the API.
    content.vb: Public Sub New(basePath As String)
  overload: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.BasePath
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.BasePath
  id: BasePath
  parent: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute
  langs:
  - csharp
  - vb
  name: BasePath
  nameWithType: OpenApiBasePathAttribute.BasePath
  fullName: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.BasePath
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nBase path for the API.\n"
  syntax:
    content: public string BasePath { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property BasePath As String
  overload: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.BasePath*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: CoreWCF.OpenApi.Attributes
  commentId: N:CoreWCF.OpenApi.Attributes
  isExternal: true
  name: CoreWCF.OpenApi.Attributes
  nameWithType: CoreWCF.OpenApi.Attributes
  fullName: CoreWCF.OpenApi.Attributes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.#ctor*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.#ctor
  isExternal: true
  name: OpenApiBasePathAttribute
  nameWithType: OpenApiBasePathAttribute.OpenApiBasePathAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.OpenApiBasePathAttribute
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.BasePath*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.BasePath
  isExternal: true
  name: BasePath
  nameWithType: OpenApiBasePathAttribute.BasePath
  fullName: CoreWCF.OpenApi.Attributes.OpenApiBasePathAttribute.BasePath
