### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.AddressHeaderCollectionElement
  commentId: T:CoreWCF.Configuration.AddressHeaderCollectionElement
  id: AddressHeaderCollectionElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.AddressHeaderCollectionElement.#ctor
  - CoreWCF.Configuration.AddressHeaderCollectionElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - CoreWCF.Configuration.AddressHeaderCollectionElement.Headers
  - CoreWCF.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  langs:
  - csharp
  - vb
  name: AddressHeaderCollectionElement
  nameWithType: AddressHeaderCollectionElement
  fullName: CoreWCF.Configuration.AddressHeaderCollectionElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents the configuration element that contains a collection of address headers. This class cannot be inherited.
  syntax:
    content: 'public sealed class AddressHeaderCollectionElement : ServiceModelConfigurationElement'
    content.vb: >-
      Public NotInheritable Class AddressHeaderCollectionElement
          Inherits ServiceModelConfigurationElement
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElement
  inheritedMembers:
  - CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.AddressHeaderCollectionElement.#ctor
  commentId: M:CoreWCF.Configuration.AddressHeaderCollectionElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  - vb
  name: AddressHeaderCollectionElement()
  summary: Initializes a new instance of the [AddressHeaderCollectionElement](xref:CoreWCF.Configuration.AddressHeaderCollectionElement) class.
  nameWithType: AddressHeaderCollectionElement.AddressHeaderCollectionElement()
  fullName: CoreWCF.Configuration.AddressHeaderCollectionElement.AddressHeaderCollectionElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public AddressHeaderCollectionElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.AddressHeaderCollectionElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.AddressHeaderCollectionElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  commentId: M:CoreWCF.Configuration.AddressHeaderCollectionElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: CoreWCF.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  - vb
  name: DeserializeElement(XmlReader, Boolean)
  summary: Reads XML from the configuration file.
  nameWithType: AddressHeaderCollectionElement.DeserializeElement(XmlReader, Boolean)
  fullName: CoreWCF.Configuration.AddressHeaderCollectionElement.DeserializeElement(System.Xml.XmlReader, System.Boolean)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override void DeserializeElement(XmlReader reader, bool serializeCollectionKey)
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: The [XmlReader](xref:System.Xml.XmlReader) that reads from the configuration file.
    - id: serializeCollectionKey
      type: System.Boolean
      description: "`true` to serialize only the collection key properties; otherwise, `false`."
    content.vb: Protected Overrides Sub DeserializeElement(reader As XmlReader, serializeCollectionKey As Boolean)
  overload: CoreWCF.Configuration.AddressHeaderCollectionElement.DeserializeElement*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: CoreWCF.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  commentId: M:CoreWCF.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  id: SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  parent: CoreWCF.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  - vb
  name: SerializeToXmlElement(XmlWriter, String)
  summary: Writes the outer tags of this configuration element to the configuration file when implemented in a derived class.
  nameWithType: AddressHeaderCollectionElement.SerializeToXmlElement(XmlWriter, String)
  fullName: CoreWCF.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(System.Xml.XmlWriter, System.String)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override bool SerializeToXmlElement(XmlWriter writer, string elementName)
    parameters:
    - id: writer
      type: System.Xml.XmlWriter
      desription: The [XmlWriter](xref:System.Xml.XmlWriter) that writes to the configuration file.
    - id: elementName
      type: System.String
      description: The name of the [ConfigurationElement](xref:System.Configuration.ConfigurationElement) to be written.
    return:
      type: System.Boolean
      description: "`true` if writing was successful; otherwise, `false`."
    content.vb: Protected Overrides Function SerializeToXmlElement(writer As XmlWriter, elementName As String) As Boolean
  overload: CoreWCF.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
  remarks: The [SerializeToXmlElement](https://learn.microsoft.com/en-us/dotnet/api/system.configuration.configurationelement.serializetoxmlelement?view=netframework-4.8.1) method is called after the call to the [Unmerge](https://learn.microsoft.com/en-us/dotnet/api/system.configuration.configurationelement.unmerge?view=netframework-4.8.1) method during serialization. The [SerializeToXmlElement](https://learn.microsoft.com/en-us/dotnet/api/system.configuration.configurationelement.serializetoxmlelement?view=netframework-4.8.1) method writes out the contents of the configuration element between the beginning and ending tags of the element. Override [SerializeToXmlElement](https://learn.microsoft.com/en-us/dotnet/api/system.configuration.configurationelement.serializetoxmlelement?view=netframework-4.8.1) to provide a custom serialization method.
- uid: CoreWCF.Configuration.AddressHeaderCollectionElement.Headers
  commentId: P:CoreWCF.Configuration.AddressHeaderCollectionElement.Headers
  id: Headers
  parent: CoreWCF.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  - vb
  name: Headers
  summary: Gets or sets a collection of address headers.
  nameWithType: AddressHeaderCollectionElement.Headers
  fullName: CoreWCF.Configuration.AddressHeaderCollectionElement.Headers
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public AddressHeaderCollection Headers { get; set; }
    parameters: []
    return:
      type: CoreWCF.Channels.AddressHeaderCollection
      description: A collection of address headers.
    content.vb: Public Property Headers As AddressHeaderCollection
  overload: CoreWCF.Configuration.AddressHeaderCollectionElement.Headers*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: CoreWCF.Configuration.ServiceModelConfigurationElement
  definition: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  isExternal: true
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.AddressHeaderCollectionElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.AddressHeaderCollectionElement.#ctor
  isExternal: true
  name: AddressHeaderCollectionElement
  nameWithType: AddressHeaderCollectionElement.AddressHeaderCollectionElement
  fullName: CoreWCF.Configuration.AddressHeaderCollectionElement.AddressHeaderCollectionElement
- uid: CoreWCF.Configuration.AddressHeaderCollectionElement.DeserializeElement*
  commentId: Overload:CoreWCF.Configuration.AddressHeaderCollectionElement.DeserializeElement
  isExternal: true
  name: DeserializeElement
  nameWithType: AddressHeaderCollectionElement.DeserializeElement
  fullName: CoreWCF.Configuration.AddressHeaderCollectionElement.DeserializeElement
- uid: System.Xml.XmlReader
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: CoreWCF.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement*
  commentId: Overload:CoreWCF.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement
  isExternal: true
  name: SerializeToXmlElement
  nameWithType: AddressHeaderCollectionElement.SerializeToXmlElement
  fullName: CoreWCF.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement
- uid: System.Xml.XmlWriter
  isExternal: true
  name: XmlWriter
  nameWithType: XmlWriter
  fullName: System.Xml.XmlWriter
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.Configuration.AddressHeaderCollectionElement.Headers*
  commentId: Overload:CoreWCF.Configuration.AddressHeaderCollectionElement.Headers
  isExternal: true
  name: Headers
  nameWithType: AddressHeaderCollectionElement.Headers
  fullName: CoreWCF.Configuration.AddressHeaderCollectionElement.Headers
- uid: CoreWCF.Channels.AddressHeaderCollection
  commentId: T:CoreWCF.Channels.AddressHeaderCollection
  parent: CoreWCF.Channels
  isExternal: true
  name: AddressHeaderCollection
  nameWithType: AddressHeaderCollection
  fullName: CoreWCF.Channels.AddressHeaderCollection
- uid: CoreWCF.Channels
  commentId: N:CoreWCF.Channels
  isExternal: true
  name: CoreWCF.Channels
  nameWithType: CoreWCF.Channels
  fullName: CoreWCF.Channels
