### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.BindingCollectionElement
  commentId: T:CoreWCF.Configuration.BindingCollectionElement
  id: BindingCollectionElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.BindingCollectionElement.#ctor
  langs:
  - csharp
  - vb
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement
  fullName: CoreWCF.Configuration.BindingCollectionElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a configuration section that contains a collection of binding elements, each of which describes an aspect of how an endpoint communicates with other endpoints, that is built, consistently, into a channel factory on the client and a channel listener on the service.
  syntax:
    content: 'public abstract class BindingCollectionElement : ConfigurationElement'
    content.vb: >-
      Public MustInherit Class BindingCollectionElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  derivedClasses:
  - CoreWCF.Configuration.StandardBindingCollectionElement`2
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: CoreWCF.Configuration.BindingCollectionElement.#ctor
  commentId: M:CoreWCF.Configuration.BindingCollectionElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.BindingCollectionElement
  langs:
  - csharp
  - vb
  name: BindingCollectionElement()
  summary: Initializes a new instance of the [BindingCollectionElement](xref:CoreWCF.Configuration.BindingCollectionElement) class.
  nameWithType: BindingCollectionElement.BindingCollectionElement()
  fullName: CoreWCF.Configuration.BindingCollectionElement.BindingCollectionElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected BindingCollectionElement()
    content.vb: Protected Sub New
  overload: CoreWCF.Configuration.BindingCollectionElement.#ctor*
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.BindingCollectionElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.BindingCollectionElement.#ctor
  isExternal: true
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement.BindingCollectionElement
  fullName: CoreWCF.Configuration.BindingCollectionElement.BindingCollectionElement
