### YamlMime:ManagedReference
items:
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
  id: OpenApiPropertyAttribute
  parent: CoreWCF.OpenApi.Attributes
  children:
  - CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.#ctor
  - CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Description
  - CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Format
  - CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.IsRequired
  - CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MaxLength
  - CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MinLength
  langs:
  - csharp
  - vb
  name: OpenApiPropertyAttribute
  nameWithType: OpenApiPropertyAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
  type: Class
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nAttribute to denote a information about a property in a request or response object.\n"
  syntax:
    content: 'public sealed class OpenApiPropertyAttribute : Attribute'
    content.vb: >-
      Public NotInheritable Class OpenApiPropertyAttribute
          Inherits Attribute
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.#ctor
  commentId: M:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.#ctor
  id: '#ctor'
  parent: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
  langs:
  - csharp
  - vb
  name: OpenApiPropertyAttribute()
  nameWithType: OpenApiPropertyAttribute.OpenApiPropertyAttribute()
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.OpenApiPropertyAttribute()
  type: Constructor
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  syntax:
    content: public OpenApiPropertyAttribute()
    content.vb: Public Sub New
  overload: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Description
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Description
  id: Description
  parent: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: OpenApiPropertyAttribute.Description
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Description
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nDescription of the property.\n"
  syntax:
    content: public string Description { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Description As String
  overload: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Description*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.IsRequired
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.IsRequired
  id: IsRequired
  parent: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
  langs:
  - csharp
  - vb
  name: IsRequired
  nameWithType: OpenApiPropertyAttribute.IsRequired
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.IsRequired
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nWhether the property is required or not.\n"
  syntax:
    content: public bool IsRequired { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsRequired As Boolean
  overload: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.IsRequired*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MinLength
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MinLength
  id: MinLength
  parent: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
  langs:
  - csharp
  - vb
  name: MinLength
  nameWithType: OpenApiPropertyAttribute.MinLength
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MinLength
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nMinimum length of the property.\n"
  syntax:
    content: public int MinLength { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MinLength As Integer
  overload: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MinLength*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MaxLength
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MaxLength
  id: MaxLength
  parent: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
  langs:
  - csharp
  - vb
  name: MaxLength
  nameWithType: OpenApiPropertyAttribute.MaxLength
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MaxLength
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nMaximum length of the property.\n"
  syntax:
    content: public int MaxLength { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxLength As Integer
  overload: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MaxLength*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Format
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Format
  id: Format
  parent: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute
  langs:
  - csharp
  - vb
  name: Format
  nameWithType: OpenApiPropertyAttribute.Format
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Format
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nHow the property should be formatted.\n"
  syntax:
    content: public string Format { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Format As String
  overload: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Format*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.OpenApi.Attributes
  commentId: N:CoreWCF.OpenApi.Attributes
  isExternal: true
  name: CoreWCF.OpenApi.Attributes
  nameWithType: CoreWCF.OpenApi.Attributes
  fullName: CoreWCF.OpenApi.Attributes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.#ctor*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.#ctor
  isExternal: true
  name: OpenApiPropertyAttribute
  nameWithType: OpenApiPropertyAttribute.OpenApiPropertyAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.OpenApiPropertyAttribute
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Description*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Description
  isExternal: true
  name: Description
  nameWithType: OpenApiPropertyAttribute.Description
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Description
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.IsRequired*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.IsRequired
  isExternal: true
  name: IsRequired
  nameWithType: OpenApiPropertyAttribute.IsRequired
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.IsRequired
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MinLength*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MinLength
  isExternal: true
  name: MinLength
  nameWithType: OpenApiPropertyAttribute.MinLength
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MinLength
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MaxLength*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MaxLength
  isExternal: true
  name: MaxLength
  nameWithType: OpenApiPropertyAttribute.MaxLength
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.MaxLength
- uid: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Format*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Format
  isExternal: true
  name: Format
  nameWithType: OpenApiPropertyAttribute.Format
  fullName: CoreWCF.OpenApi.Attributes.OpenApiPropertyAttribute.Format
