### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.HandshakeDelegate
  commentId: T:CoreWCF.Configuration.HandshakeDelegate
  id: HandshakeDelegate
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.HandshakeDelegate.#ctor(System.Object,System.IntPtr)
  - CoreWCF.Configuration.HandshakeDelegate.BeginInvoke(CoreWCF.Channels.Framing.FramingConnection,System.AsyncCallback,System.Object)
  - CoreWCF.Configuration.HandshakeDelegate.EndInvoke(System.IAsyncResult)
  - CoreWCF.Configuration.HandshakeDelegate.Invoke(CoreWCF.Channels.Framing.FramingConnection)
  langs:
  - csharp
  - vb
  name: HandshakeDelegate
  nameWithType: HandshakeDelegate
  fullName: CoreWCF.Configuration.HandshakeDelegate
  type: Class
  source:
    path: CoreWCF.NetTcp
    isExternal: true
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public sealed class HandshakeDelegate : MulticastDelegate'
    content.vb: >-
      Public NotInheritable Class HandshakeDelegate
          Inherits MulticastDelegate
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.HandshakeDelegate.#ctor(System.Object,System.IntPtr)
  commentId: M:CoreWCF.Configuration.HandshakeDelegate.#ctor(System.Object,System.IntPtr)
  id: '#ctor(System.Object,System.IntPtr)'
  parent: CoreWCF.Configuration.HandshakeDelegate
  langs:
  - csharp
  - vb
  name: HandshakeDelegate(Object, IntPtr)
  nameWithType: HandshakeDelegate.HandshakeDelegate(Object, IntPtr)
  fullName: CoreWCF.Configuration.HandshakeDelegate.HandshakeDelegate(System.Object, System.IntPtr)
  type: Constructor
  source:
    path: CoreWCF.NetTcp
    isExternal: true
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  syntax:
    content: public HandshakeDelegate(object object, IntPtr method)
    parameters:
    - id: object
      type: System.Object
    - id: method
      type: System.IntPtr
    content.vb: Public Sub New(object As Object, method As IntPtr)
  overload: CoreWCF.Configuration.HandshakeDelegate.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.HandshakeDelegate.Invoke(CoreWCF.Channels.Framing.FramingConnection)
  commentId: M:CoreWCF.Configuration.HandshakeDelegate.Invoke(CoreWCF.Channels.Framing.FramingConnection)
  id: Invoke(CoreWCF.Channels.Framing.FramingConnection)
  parent: CoreWCF.Configuration.HandshakeDelegate
  langs:
  - csharp
  - vb
  name: Invoke(FramingConnection)
  nameWithType: HandshakeDelegate.Invoke(FramingConnection)
  fullName: CoreWCF.Configuration.HandshakeDelegate.Invoke(CoreWCF.Channels.Framing.FramingConnection)
  type: Method
  source:
    path: CoreWCF.NetTcp
    isExternal: true
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  syntax:
    content: public virtual Task Invoke(FramingConnection connection)
    parameters:
    - id: connection
      type: CoreWCF.Channels.Framing.FramingConnection
    return:
      type: System.Threading.Tasks.Task
    content.vb: Public Overridable Function Invoke(connection As FramingConnection) As Task
  overload: CoreWCF.Configuration.HandshakeDelegate.Invoke*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
- uid: CoreWCF.Configuration.HandshakeDelegate.BeginInvoke(CoreWCF.Channels.Framing.FramingConnection,System.AsyncCallback,System.Object)
  commentId: M:CoreWCF.Configuration.HandshakeDelegate.BeginInvoke(CoreWCF.Channels.Framing.FramingConnection,System.AsyncCallback,System.Object)
  id: BeginInvoke(CoreWCF.Channels.Framing.FramingConnection,System.AsyncCallback,System.Object)
  parent: CoreWCF.Configuration.HandshakeDelegate
  langs:
  - csharp
  - vb
  name: BeginInvoke(FramingConnection, AsyncCallback, Object)
  nameWithType: HandshakeDelegate.BeginInvoke(FramingConnection, AsyncCallback, Object)
  fullName: CoreWCF.Configuration.HandshakeDelegate.BeginInvoke(CoreWCF.Channels.Framing.FramingConnection, System.AsyncCallback, System.Object)
  type: Method
  source:
    path: CoreWCF.NetTcp
    isExternal: true
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  syntax:
    content: public virtual IAsyncResult BeginInvoke(FramingConnection connection, AsyncCallback callback, object object)
    parameters:
    - id: connection
      type: CoreWCF.Channels.Framing.FramingConnection
    - id: callback
      type: System.AsyncCallback
    - id: object
      type: System.Object
    return:
      type: System.IAsyncResult
    content.vb: Public Overridable Function BeginInvoke(connection As FramingConnection, callback As AsyncCallback, object As Object) As IAsyncResult
  overload: CoreWCF.Configuration.HandshakeDelegate.BeginInvoke*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
- uid: CoreWCF.Configuration.HandshakeDelegate.EndInvoke(System.IAsyncResult)
  commentId: M:CoreWCF.Configuration.HandshakeDelegate.EndInvoke(System.IAsyncResult)
  id: EndInvoke(System.IAsyncResult)
  parent: CoreWCF.Configuration.HandshakeDelegate
  langs:
  - csharp
  - vb
  name: EndInvoke(IAsyncResult)
  nameWithType: HandshakeDelegate.EndInvoke(IAsyncResult)
  fullName: CoreWCF.Configuration.HandshakeDelegate.EndInvoke(System.IAsyncResult)
  type: Method
  source:
    path: CoreWCF.NetTcp
    isExternal: true
  assemblies:
  - CoreWCF.NetTcp
  namespace: CoreWCF.Configuration
  syntax:
    content: public virtual Task EndInvoke(IAsyncResult result)
    parameters:
    - id: result
      type: System.IAsyncResult
    return:
      type: System.Threading.Tasks.Task
    content.vb: Public Overridable Function EndInvoke(result As IAsyncResult) As Task
  overload: CoreWCF.Configuration.HandshakeDelegate.EndInvoke*
  modifiers.csharp:
  - public
  - virtual
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.HandshakeDelegate.#ctor*
  commentId: Overload:CoreWCF.Configuration.HandshakeDelegate.#ctor
  isExternal: true
  name: HandshakeDelegate
  nameWithType: HandshakeDelegate.HandshakeDelegate
  fullName: CoreWCF.Configuration.HandshakeDelegate.HandshakeDelegate
- uid: System.IntPtr
  commentId: T:System.IntPtr
  parent: System
  isExternal: true
  name: IntPtr
  nameWithType: IntPtr
  fullName: System.IntPtr
- uid: CoreWCF.Configuration.HandshakeDelegate.Invoke*
  commentId: Overload:CoreWCF.Configuration.HandshakeDelegate.Invoke
  isExternal: true
  name: Invoke
  nameWithType: HandshakeDelegate.Invoke
  fullName: CoreWCF.Configuration.HandshakeDelegate.Invoke
- uid: CoreWCF.Channels.Framing.FramingConnection
  commentId: T:CoreWCF.Channels.Framing.FramingConnection
  parent: CoreWCF.Channels.Framing
  isExternal: true
  name: FramingConnection
  nameWithType: FramingConnection
  fullName: CoreWCF.Channels.Framing.FramingConnection
- uid: System.Threading.Tasks.Task
  isExternal: true
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: CoreWCF.Channels.Framing
  commentId: N:CoreWCF.Channels.Framing
  isExternal: true
  name: CoreWCF.Channels.Framing
  nameWithType: CoreWCF.Channels.Framing
  fullName: CoreWCF.Channels.Framing
- uid: CoreWCF.Configuration.HandshakeDelegate.BeginInvoke*
  commentId: Overload:CoreWCF.Configuration.HandshakeDelegate.BeginInvoke
  isExternal: true
  name: BeginInvoke
  nameWithType: HandshakeDelegate.BeginInvoke
  fullName: CoreWCF.Configuration.HandshakeDelegate.BeginInvoke
- uid: System.AsyncCallback
  isExternal: true
  name: AsyncCallback
  nameWithType: AsyncCallback
  fullName: System.AsyncCallback
- uid: System.IAsyncResult
  isExternal: true
  name: IAsyncResult
  nameWithType: IAsyncResult
  fullName: System.IAsyncResult
- uid: CoreWCF.Configuration.HandshakeDelegate.EndInvoke*
  commentId: Overload:CoreWCF.Configuration.HandshakeDelegate.EndInvoke
  isExternal: true
  name: EndInvoke
  nameWithType: HandshakeDelegate.EndInvoke
  fullName: CoreWCF.Configuration.HandshakeDelegate.EndInvoke
