### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement
  commentId: T:CoreWCF.Configuration.MessageSecurityOverHttpElement
  id: MessageSecurityOverHttpElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.MessageSecurityOverHttpElement.#ctor
  - CoreWCF.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite
  - CoreWCF.Configuration.MessageSecurityOverHttpElement.ClientCredentialType
  - CoreWCF.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential
  langs:
  - csharp
  - vb
  name: MessageSecurityOverHttpElement
  nameWithType: MessageSecurityOverHttpElement
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Defines the security configuration settings for message sent using HTTP.
  remarks: To be added.
  syntax:
    content: 'public class MessageSecurityOverHttpElement : ServiceModelConfigurationElement'
    content.vb: >-
      Public Class MessageSecurityOverHttpElement
          Inherits ServiceModelConfigurationElement
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElement
  derivedClasses:
  - CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement
  inheritedMembers:
  - CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement.#ctor
  commentId: M:CoreWCF.Configuration.MessageSecurityOverHttpElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.MessageSecurityOverHttpElement
  langs:
  - csharp
  - vb
  name: MessageSecurityOverHttpElement()
  nameWithType: MessageSecurityOverHttpElement.MessageSecurityOverHttpElement()
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement.MessageSecurityOverHttpElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public MessageSecurityOverHttpElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.MessageSecurityOverHttpElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement.ClientCredentialType
  commentId: P:CoreWCF.Configuration.MessageSecurityOverHttpElement.ClientCredentialType
  id: ClientCredentialType
  parent: CoreWCF.Configuration.MessageSecurityOverHttpElement
  langs:
  - csharp
  - vb
  name: ClientCredentialType
  nameWithType: MessageSecurityOverHttpElement.ClientCredentialType
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement.ClientCredentialType
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public MessageCredentialType ClientCredentialType { get; set; }
    parameters: []
    return:
      type: CoreWCF.MessageCredentialType
    content.vb: Public Property ClientCredentialType As MessageCredentialType
  overload: CoreWCF.Configuration.MessageSecurityOverHttpElement.ClientCredentialType*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential
  commentId: P:CoreWCF.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential
  id: NegotiateServiceCredential
  parent: CoreWCF.Configuration.MessageSecurityOverHttpElement
  langs:
  - csharp
  - vb
  name: NegotiateServiceCredential
  nameWithType: MessageSecurityOverHttpElement.NegotiateServiceCredential
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public bool NegotiateServiceCredential { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property NegotiateServiceCredential As Boolean
  overload: CoreWCF.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite
  commentId: P:CoreWCF.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite
  id: AlgorithmSuite
  parent: CoreWCF.Configuration.MessageSecurityOverHttpElement
  langs:
  - csharp
  - vb
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverHttpElement.AlgorithmSuite
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    parameters: []
    return:
      type: CoreWCF.Security.SecurityAlgorithmSuite
    content.vb: Public Property AlgorithmSuite As SecurityAlgorithmSuite
  overload: CoreWCF.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: CoreWCF.Configuration.ServiceModelConfigurationElement
  definition: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  isExternal: true
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.MessageSecurityOverHttpElement.#ctor
  isExternal: true
  name: MessageSecurityOverHttpElement
  nameWithType: MessageSecurityOverHttpElement.MessageSecurityOverHttpElement
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement.MessageSecurityOverHttpElement
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement.ClientCredentialType*
  commentId: Overload:CoreWCF.Configuration.MessageSecurityOverHttpElement.ClientCredentialType
  isExternal: true
  name: ClientCredentialType
  nameWithType: MessageSecurityOverHttpElement.ClientCredentialType
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement.ClientCredentialType
- uid: CoreWCF.MessageCredentialType
  commentId: T:CoreWCF.MessageCredentialType
  parent: CoreWCF
  isExternal: true
  name: MessageCredentialType
  nameWithType: MessageCredentialType
  fullName: CoreWCF.MessageCredentialType
- uid: CoreWCF
  commentId: N:CoreWCF
  isExternal: true
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential*
  commentId: Overload:CoreWCF.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential
  isExternal: true
  name: NegotiateServiceCredential
  nameWithType: MessageSecurityOverHttpElement.NegotiateServiceCredential
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement.NegotiateServiceCredential
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: CoreWCF.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite*
  commentId: Overload:CoreWCF.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite
  isExternal: true
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverHttpElement.AlgorithmSuite
  fullName: CoreWCF.Configuration.MessageSecurityOverHttpElement.AlgorithmSuite
- uid: CoreWCF.Security.SecurityAlgorithmSuite
  commentId: T:CoreWCF.Security.SecurityAlgorithmSuite
  parent: CoreWCF.Security
  isExternal: true
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: CoreWCF.Security.SecurityAlgorithmSuite
- uid: CoreWCF.Security
  commentId: N:CoreWCF.Security
  isExternal: true
  name: CoreWCF.Security
  nameWithType: CoreWCF.Security
  fullName: CoreWCF.Security
