### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.AuthenticationMode
  commentId: T:CoreWCF.Configuration.AuthenticationMode
  id: AuthenticationMode
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.AuthenticationMode.CertificateOverTransport
  - CoreWCF.Configuration.AuthenticationMode.IssuedTokenForCertificate
  - CoreWCF.Configuration.AuthenticationMode.IssuedTokenForSslNegotiated
  - CoreWCF.Configuration.AuthenticationMode.IssuedTokenOverTransport
  - CoreWCF.Configuration.AuthenticationMode.SecureConversation
  - CoreWCF.Configuration.AuthenticationMode.SspiNegotiatedOverTransport
  - CoreWCF.Configuration.AuthenticationMode.UserNameOverTransport
  - CoreWCF.Configuration.AuthenticationMode.value__
  langs:
  - csharp
  - vb
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: CoreWCF.Configuration.AuthenticationMode
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Specifies the authentication setting used for message exchange.
  syntax:
    content: 'public sealed class AuthenticationMode : Enum'
    content.vb: >-
      Public NotInheritable Class AuthenticationMode
          Inherits

           Enum
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.AuthenticationMode.value__
  commentId: F:CoreWCF.Configuration.AuthenticationMode.value__
  id: value__
  parent: CoreWCF.Configuration.AuthenticationMode
  langs:
  - csharp
  - vb
  name: value__
  nameWithType: AuthenticationMode.value__
  fullName: CoreWCF.Configuration.AuthenticationMode.value__
  type: Field
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public int value__
    return:
      type: System.Int32
    content.vb: Public value__ As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.AuthenticationMode.CertificateOverTransport
  commentId: F:CoreWCF.Configuration.AuthenticationMode.CertificateOverTransport
  id: CertificateOverTransport
  parent: CoreWCF.Configuration.AuthenticationMode
  langs:
  - csharp
  - vb
  name: CertificateOverTransport
  summary: Specifies that the initiator is authenticated by an X.509 version 3 certificate, and that the responder is authenticated by SSL over HTTPS.
  nameWithType: AuthenticationMode.CertificateOverTransport
  fullName: CoreWCF.Configuration.AuthenticationMode.CertificateOverTransport
  type: Field
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public const AuthenticationMode CertificateOverTransport
    return:
      type: CoreWCF.Configuration.AuthenticationMode
    content.vb: Public Const CertificateOverTransport As AuthenticationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: CoreWCF.Configuration.AuthenticationMode.IssuedTokenForCertificate
  commentId: F:CoreWCF.Configuration.AuthenticationMode.IssuedTokenForCertificate
  id: IssuedTokenForCertificate
  parent: CoreWCF.Configuration.AuthenticationMode
  langs:
  - csharp
  - vb
  name: IssuedTokenForCertificate
  summary: Specifies that the initiator is authenticated by an XML symmetric key token, and that the responder is authenticated by an X.509 version 3 certificate.
  nameWithType: AuthenticationMode.IssuedTokenForCertificate
  fullName: CoreWCF.Configuration.AuthenticationMode.IssuedTokenForCertificate
  type: Field
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public const AuthenticationMode IssuedTokenForCertificate
    return:
      type: CoreWCF.Configuration.AuthenticationMode
    content.vb: Public Const IssuedTokenForCertificate As AuthenticationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: CoreWCF.Configuration.AuthenticationMode.IssuedTokenForSslNegotiated
  commentId: F:CoreWCF.Configuration.AuthenticationMode.IssuedTokenForSslNegotiated
  id: IssuedTokenForSslNegotiated
  parent: CoreWCF.Configuration.AuthenticationMode
  langs:
  - csharp
  - vb
  name: IssuedTokenForSslNegotiated
  summary: Specifies that the initiator is authenticated by an XML symmetric key token, and that the responder is authenticated by the SOAP implementation of SSL.
  nameWithType: AuthenticationMode.IssuedTokenForSslNegotiated
  fullName: CoreWCF.Configuration.AuthenticationMode.IssuedTokenForSslNegotiated
  type: Field
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public const AuthenticationMode IssuedTokenForSslNegotiated
    return:
      type: CoreWCF.Configuration.AuthenticationMode
    content.vb: Public Const IssuedTokenForSslNegotiated As AuthenticationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: CoreWCF.Configuration.AuthenticationMode.IssuedTokenOverTransport
  commentId: F:CoreWCF.Configuration.AuthenticationMode.IssuedTokenOverTransport
  id: IssuedTokenOverTransport
  parent: CoreWCF.Configuration.AuthenticationMode
  langs:
  - csharp
  - vb
  name: IssuedTokenOverTransport
  summary: Specifies that the initiator is authenticated by an XML symmetric key token, and that the responder is authenticated by SSL over HTTPS.
  nameWithType: AuthenticationMode.IssuedTokenOverTransport
  fullName: CoreWCF.Configuration.AuthenticationMode.IssuedTokenOverTransport
  type: Field
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public const AuthenticationMode IssuedTokenOverTransport
    return:
      type: CoreWCF.Configuration.AuthenticationMode
    content.vb: Public Const IssuedTokenOverTransport As AuthenticationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: CoreWCF.Configuration.AuthenticationMode.SecureConversation
  commentId: F:CoreWCF.Configuration.AuthenticationMode.SecureConversation
  id: SecureConversation
  parent: CoreWCF.Configuration.AuthenticationMode
  langs:
  - csharp
  - vb
  name: SecureConversation
  summary: Specifies that WS-SecureConversation authentication is used.
  nameWithType: AuthenticationMode.SecureConversation
  fullName: CoreWCF.Configuration.AuthenticationMode.SecureConversation
  type: Field
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public const AuthenticationMode SecureConversation
    return:
      type: CoreWCF.Configuration.AuthenticationMode
    content.vb: Public Const SecureConversation As AuthenticationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: CoreWCF.Configuration.AuthenticationMode.UserNameOverTransport
  commentId: F:CoreWCF.Configuration.AuthenticationMode.UserNameOverTransport
  id: UserNameOverTransport
  parent: CoreWCF.Configuration.AuthenticationMode
  langs:
  - csharp
  - vb
  name: UserNameOverTransport
  summary: Specifies that the initiator is authenticated using a username token, and that the responder is authenticated by SSL over HTTPS.
  nameWithType: AuthenticationMode.UserNameOverTransport
  fullName: CoreWCF.Configuration.AuthenticationMode.UserNameOverTransport
  type: Field
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public const AuthenticationMode UserNameOverTransport
    return:
      type: CoreWCF.Configuration.AuthenticationMode
    content.vb: Public Const UserNameOverTransport As AuthenticationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: CoreWCF.Configuration.AuthenticationMode.SspiNegotiatedOverTransport
  commentId: F:CoreWCF.Configuration.AuthenticationMode.SspiNegotiatedOverTransport
  id: SspiNegotiatedOverTransport
  parent: CoreWCF.Configuration.AuthenticationMode
  langs:
  - csharp
  - vb
  name: SspiNegotiatedOverTransport
  summary: Specifies that the initiator is authenticated by a security context using the Security Service Provider Interface (SSPI), and the responder is authenticated by SSL over HTTPS.
  nameWithType: AuthenticationMode.SspiNegotiatedOverTransport
  fullName: CoreWCF.Configuration.AuthenticationMode.SspiNegotiatedOverTransport
  type: Field
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public const AuthenticationMode SspiNegotiatedOverTransport
    return:
      type: CoreWCF.Configuration.AuthenticationMode
    content.vb: Public Const SspiNegotiatedOverTransport As AuthenticationMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: CoreWCF.Configuration.AuthenticationMode
  commentId: T:CoreWCF.Configuration.AuthenticationMode
  parent: CoreWCF.Configuration
  isExternal: true
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: CoreWCF.Configuration.AuthenticationMode
