### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement
  commentId: T:CoreWCF.Configuration.ExtendedProtectionPolicyElement
  id: ExtendedProtectionPolicyElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ExtendedProtectionPolicyElement.#ctor
  - CoreWCF.Configuration.ExtendedProtectionPolicyElement.BuildPolicy
  - CoreWCF.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames
  - CoreWCF.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement
  - CoreWCF.Configuration.ExtendedProtectionPolicyElement.Properties
  - CoreWCF.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario
  langs:
  - csharp
  - vb
  name: ExtendedProtectionPolicyElement
  nameWithType: ExtendedProtectionPolicyElement
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: The  class represents a configuration element for an .
  remarks: "An &lt;xref:System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy> can be configured for server applications using standard configuration files.  \n\n"
  syntax:
    content: 'public sealed class ExtendedProtectionPolicyElement : ConfigurationElement'
    content.vb: >-
      Public NotInheritable Class ExtendedProtectionPolicyElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement.#ctor
  commentId: M:CoreWCF.Configuration.ExtendedProtectionPolicyElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ExtendedProtectionPolicyElement
  langs:
  - csharp
  - vb
  name: ExtendedProtectionPolicyElement()
  nameWithType: ExtendedProtectionPolicyElement.ExtendedProtectionPolicyElement()
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement.ExtendedProtectionPolicyElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ExtendedProtectionPolicyElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.ExtendedProtectionPolicyElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement.BuildPolicy
  commentId: M:CoreWCF.Configuration.ExtendedProtectionPolicyElement.BuildPolicy
  id: BuildPolicy
  parent: CoreWCF.Configuration.ExtendedProtectionPolicyElement
  langs:
  - csharp
  - vb
  name: BuildPolicy()
  nameWithType: ExtendedProtectionPolicyElement.BuildPolicy()
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement.BuildPolicy()
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ExtendedProtectionPolicy BuildPolicy()
    return:
      type: System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy
    content.vb: Public Function BuildPolicy As ExtendedProtectionPolicy
  overload: CoreWCF.Configuration.ExtendedProtectionPolicyElement.BuildPolicy*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement.Properties
  commentId: P:CoreWCF.Configuration.ExtendedProtectionPolicyElement.Properties
  id: Properties
  parent: CoreWCF.Configuration.ExtendedProtectionPolicyElement
  langs:
  - csharp
  - vb
  name: Properties
  nameWithType: ExtendedProtectionPolicyElement.Properties
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement.Properties
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override ConfigurationPropertyCollection Properties { get; }
    parameters: []
    return:
      type: System.Configuration.ConfigurationPropertyCollection
    content.vb: Protected Overrides ReadOnly Property Properties As ConfigurationPropertyCollection
  overload: CoreWCF.Configuration.ExtendedProtectionPolicyElement.Properties*
  modifiers.csharp:
  - protected
  - override
  - get
  modifiers.vb:
  - Protected
  - Overrides
  - ReadOnly
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement
  commentId: P:CoreWCF.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement
  id: PolicyEnforcement
  parent: CoreWCF.Configuration.ExtendedProtectionPolicyElement
  langs:
  - csharp
  - vb
  name: PolicyEnforcement
  nameWithType: ExtendedProtectionPolicyElement.PolicyEnforcement
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public PolicyEnforcement PolicyEnforcement { get; set; }
    parameters: []
    return:
      type: System.Security.Authentication.ExtendedProtection.PolicyEnforcement
    content.vb: Public Property PolicyEnforcement As PolicyEnforcement
  overload: CoreWCF.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario
  commentId: P:CoreWCF.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario
  id: ProtectionScenario
  parent: CoreWCF.Configuration.ExtendedProtectionPolicyElement
  langs:
  - csharp
  - vb
  name: ProtectionScenario
  nameWithType: ExtendedProtectionPolicyElement.ProtectionScenario
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ProtectionScenario ProtectionScenario { get; set; }
    parameters: []
    return:
      type: System.Security.Authentication.ExtendedProtection.ProtectionScenario
    content.vb: Public Property ProtectionScenario As ProtectionScenario
  overload: CoreWCF.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames
  commentId: P:CoreWCF.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames
  id: CustomServiceNames
  parent: CoreWCF.Configuration.ExtendedProtectionPolicyElement
  langs:
  - csharp
  - vb
  name: CustomServiceNames
  nameWithType: ExtendedProtectionPolicyElement.CustomServiceNames
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceNameElementCollection CustomServiceNames { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.ServiceNameElementCollection
    content.vb: Public ReadOnly Property CustomServiceNames As ServiceNameElementCollection
  overload: CoreWCF.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.ExtendedProtectionPolicyElement.#ctor
  isExternal: true
  name: ExtendedProtectionPolicyElement
  nameWithType: ExtendedProtectionPolicyElement.ExtendedProtectionPolicyElement
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement.ExtendedProtectionPolicyElement
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement.BuildPolicy*
  commentId: Overload:CoreWCF.Configuration.ExtendedProtectionPolicyElement.BuildPolicy
  isExternal: true
  name: BuildPolicy
  nameWithType: ExtendedProtectionPolicyElement.BuildPolicy
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement.BuildPolicy
- uid: System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy
  isExternal: true
  name: ExtendedProtectionPolicy
  nameWithType: ExtendedProtectionPolicy
  fullName: System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement.Properties*
  commentId: Overload:CoreWCF.Configuration.ExtendedProtectionPolicyElement.Properties
  isExternal: true
  name: Properties
  nameWithType: ExtendedProtectionPolicyElement.Properties
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  isExternal: true
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement*
  commentId: Overload:CoreWCF.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement
  isExternal: true
  name: PolicyEnforcement
  nameWithType: ExtendedProtectionPolicyElement.PolicyEnforcement
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement
- uid: System.Security.Authentication.ExtendedProtection.PolicyEnforcement
  commentId: '!:System.Security.Authentication.ExtendedProtection.PolicyEnforcement'
  isExternal: true
  name: PolicyEnforcement
  nameWithType: PolicyEnforcement
  fullName: System.Security.Authentication.ExtendedProtection.PolicyEnforcement
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario*
  commentId: Overload:CoreWCF.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario
  isExternal: true
  name: ProtectionScenario
  nameWithType: ExtendedProtectionPolicyElement.ProtectionScenario
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario
- uid: System.Security.Authentication.ExtendedProtection.ProtectionScenario
  commentId: '!:System.Security.Authentication.ExtendedProtection.ProtectionScenario'
  isExternal: true
  name: ProtectionScenario
  nameWithType: ProtectionScenario
  fullName: System.Security.Authentication.ExtendedProtection.ProtectionScenario
- uid: CoreWCF.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames*
  commentId: Overload:CoreWCF.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames
  isExternal: true
  name: CustomServiceNames
  nameWithType: ExtendedProtectionPolicyElement.CustomServiceNames
  fullName: CoreWCF.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames
- uid: CoreWCF.Configuration.ServiceNameElementCollection
  commentId: T:CoreWCF.Configuration.ServiceNameElementCollection
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceNameElementCollection
  nameWithType: ServiceNameElementCollection
  fullName: CoreWCF.Configuration.ServiceNameElementCollection
