### YamlMime:ManagedReference
items:
- uid: CoreWCF.Security
  commentId: N:CoreWCF.Security
  id: CoreWCF.Security
  children:
  - CoreWCF.Security.Basic128SecurityAlgorithmSuite
  - CoreWCF.Security.Basic192SecurityAlgorithmSuite
  - CoreWCF.Security.Basic256SecurityAlgorithmSuite
  - CoreWCF.Security.BasicSecurityProfileVersion
  - CoreWCF.Security.BinarySecretKeyIdentifierClause
  - CoreWCF.Security.ChannelProtectionRequirements
  - CoreWCF.Security.DataProtectionSecurityStateEncoder
  - CoreWCF.Security.FederatedMessageSecurityOverHttp
  - CoreWCF.Security.ImpersonateOnSerializingReplyMessageProperty
  - CoreWCF.Security.IssuedTokenServiceCredential
  - CoreWCF.Security.LdapSettings
  - CoreWCF.Security.MessagePartSpecification
  - CoreWCF.Security.MessageProtectionOrder
  - CoreWCF.Security.MessageSecurityException
  - CoreWCF.Security.MessageSecurityOverTcp
  - CoreWCF.Security.NonceCache
  - CoreWCF.Security.SamlSerializer
  - CoreWCF.Security.ScopedMessagePartSpecification
  - CoreWCF.Security.SecureConversationServiceCredential
  - CoreWCF.Security.SecureConversationVersion
  - CoreWCF.Security.SecurityAlgorithmSuite
  - CoreWCF.Security.SecurityContextKeyIdentifierClause
  - CoreWCF.Security.SecurityCredentialsManager
  - CoreWCF.Security.SecurityKeyEntropyMode
  - CoreWCF.Security.SecurityMessageProperty
  - CoreWCF.Security.SecurityNegotiationException
  - CoreWCF.Security.SecurityPolicyVersion
  - CoreWCF.Security.SecurityProtocolFactory
  - CoreWCF.Security.SecurityStateEncoder
  - CoreWCF.Security.SecurityTokenAttachmentMode
  - CoreWCF.Security.SecurityTokenSpecification
  - CoreWCF.Security.SecurityVersion
  - CoreWCF.Security.SspiSecurityTokenProvider
  - CoreWCF.Security.SupportingTokenAuthenticatorSpecification
  - CoreWCF.Security.SupportingTokenProviderSpecification
  - CoreWCF.Security.SupportingTokenSpecification
  - CoreWCF.Security.TripleDesSecurityAlgorithmSuite
  - CoreWCF.Security.TrustVersion
  - CoreWCF.Security.UserNamePasswordServiceCredential
  - CoreWCF.Security.UserNamePasswordValidationMode
  - CoreWCF.Security.WindowsServiceCredential
  - CoreWCF.Security.WSSecurityTokenSerializer
  - CoreWCF.Security.X509CertificateInitiatorServiceCredential
  - CoreWCF.Security.X509CertificateRecipientServiceCredential
  - CoreWCF.Security.X509CertificateValidationMode
  - CoreWCF.Security.X509ClientCertificateAuthentication
  langs:
  - csharp
  - vb
  name: CoreWCF.Security
  nameWithType: CoreWCF.Security
  fullName: CoreWCF.Security
  type: Namespace
  assemblies:
  - CoreWCF.NetTcp
references:
- uid: CoreWCF.Security.MessageSecurityOverTcp
  commentId: T:CoreWCF.Security.MessageSecurityOverTcp
  parent: CoreWCF.Security
  isExternal: true
  name: MessageSecurityOverTcp
  nameWithType: MessageSecurityOverTcp
  fullName: CoreWCF.Security.MessageSecurityOverTcp
- uid: CoreWCF.Security.BasicSecurityProfileVersion
  commentId: T:CoreWCF.Security.BasicSecurityProfileVersion
  parent: CoreWCF.Security
  isExternal: true
  name: BasicSecurityProfileVersion
  nameWithType: BasicSecurityProfileVersion
  fullName: CoreWCF.Security.BasicSecurityProfileVersion
- uid: CoreWCF.Security.BinarySecretKeyIdentifierClause
  commentId: T:CoreWCF.Security.BinarySecretKeyIdentifierClause
  isExternal: true
  name: BinarySecretKeyIdentifierClause
  nameWithType: BinarySecretKeyIdentifierClause
  fullName: CoreWCF.Security.BinarySecretKeyIdentifierClause
- uid: CoreWCF.Security.ChannelProtectionRequirements
  commentId: T:CoreWCF.Security.ChannelProtectionRequirements
  parent: CoreWCF.Security
  isExternal: true
  name: ChannelProtectionRequirements
  nameWithType: ChannelProtectionRequirements
  fullName: CoreWCF.Security.ChannelProtectionRequirements
- uid: CoreWCF.Security.DataProtectionSecurityStateEncoder
  commentId: T:CoreWCF.Security.DataProtectionSecurityStateEncoder
  isExternal: true
  name: DataProtectionSecurityStateEncoder
  nameWithType: DataProtectionSecurityStateEncoder
  fullName: CoreWCF.Security.DataProtectionSecurityStateEncoder
- uid: CoreWCF.Security.FederatedMessageSecurityOverHttp
  commentId: T:CoreWCF.Security.FederatedMessageSecurityOverHttp
  parent: CoreWCF.Security
  isExternal: true
  name: FederatedMessageSecurityOverHttp
  nameWithType: FederatedMessageSecurityOverHttp
  fullName: CoreWCF.Security.FederatedMessageSecurityOverHttp
- uid: CoreWCF.Security.ImpersonateOnSerializingReplyMessageProperty
  commentId: T:CoreWCF.Security.ImpersonateOnSerializingReplyMessageProperty
  parent: CoreWCF.Security
  isExternal: true
  name: ImpersonateOnSerializingReplyMessageProperty
  nameWithType: ImpersonateOnSerializingReplyMessageProperty
  fullName: CoreWCF.Security.ImpersonateOnSerializingReplyMessageProperty
- uid: CoreWCF.Security.IssuedTokenServiceCredential
  commentId: T:CoreWCF.Security.IssuedTokenServiceCredential
  parent: CoreWCF.Security
  isExternal: true
  name: IssuedTokenServiceCredential
  nameWithType: IssuedTokenServiceCredential
  fullName: CoreWCF.Security.IssuedTokenServiceCredential
- uid: CoreWCF.Security.LdapSettings
  commentId: T:CoreWCF.Security.LdapSettings
  parent: CoreWCF.Security
  isExternal: true
  name: LdapSettings
  nameWithType: LdapSettings
  fullName: CoreWCF.Security.LdapSettings
- uid: CoreWCF.Security.MessagePartSpecification
  commentId: T:CoreWCF.Security.MessagePartSpecification
  parent: CoreWCF.Security
  isExternal: true
  name: MessagePartSpecification
  nameWithType: MessagePartSpecification
  fullName: CoreWCF.Security.MessagePartSpecification
- uid: CoreWCF.Security.MessageProtectionOrder
  commentId: T:CoreWCF.Security.MessageProtectionOrder
  parent: CoreWCF.Security
  isExternal: true
  name: MessageProtectionOrder
  nameWithType: MessageProtectionOrder
  fullName: CoreWCF.Security.MessageProtectionOrder
- uid: CoreWCF.Security.MessageSecurityException
  commentId: T:CoreWCF.Security.MessageSecurityException
  isExternal: true
  name: MessageSecurityException
  nameWithType: MessageSecurityException
  fullName: CoreWCF.Security.MessageSecurityException
- uid: CoreWCF.Security.NonceCache
  commentId: T:CoreWCF.Security.NonceCache
  parent: CoreWCF.Security
  isExternal: true
  name: NonceCache
  nameWithType: NonceCache
  fullName: CoreWCF.Security.NonceCache
- uid: CoreWCF.Security.SamlSerializer
  commentId: T:CoreWCF.Security.SamlSerializer
  parent: CoreWCF.Security
  isExternal: true
  name: SamlSerializer
  nameWithType: SamlSerializer
  fullName: CoreWCF.Security.SamlSerializer
- uid: CoreWCF.Security.ScopedMessagePartSpecification
  commentId: T:CoreWCF.Security.ScopedMessagePartSpecification
  parent: CoreWCF.Security
  isExternal: true
  name: ScopedMessagePartSpecification
  nameWithType: ScopedMessagePartSpecification
  fullName: CoreWCF.Security.ScopedMessagePartSpecification
- uid: CoreWCF.Security.SecureConversationServiceCredential
  commentId: T:CoreWCF.Security.SecureConversationServiceCredential
  parent: CoreWCF.Security
  isExternal: true
  name: SecureConversationServiceCredential
  nameWithType: SecureConversationServiceCredential
  fullName: CoreWCF.Security.SecureConversationServiceCredential
- uid: CoreWCF.Security.SecureConversationVersion
  commentId: T:CoreWCF.Security.SecureConversationVersion
  parent: CoreWCF.Security
  isExternal: true
  name: SecureConversationVersion
  nameWithType: SecureConversationVersion
  fullName: CoreWCF.Security.SecureConversationVersion
- uid: CoreWCF.Security.SecurityAlgorithmSuite
  commentId: T:CoreWCF.Security.SecurityAlgorithmSuite
  parent: CoreWCF.Security
  isExternal: true
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: CoreWCF.Security.SecurityAlgorithmSuite
- uid: CoreWCF.Security.Basic256SecurityAlgorithmSuite
  commentId: T:CoreWCF.Security.Basic256SecurityAlgorithmSuite
  isExternal: true
  name: Basic256SecurityAlgorithmSuite
  nameWithType: Basic256SecurityAlgorithmSuite
  fullName: CoreWCF.Security.Basic256SecurityAlgorithmSuite
- uid: CoreWCF.Security.Basic192SecurityAlgorithmSuite
  commentId: T:CoreWCF.Security.Basic192SecurityAlgorithmSuite
  isExternal: true
  name: Basic192SecurityAlgorithmSuite
  nameWithType: Basic192SecurityAlgorithmSuite
  fullName: CoreWCF.Security.Basic192SecurityAlgorithmSuite
- uid: CoreWCF.Security.Basic128SecurityAlgorithmSuite
  commentId: T:CoreWCF.Security.Basic128SecurityAlgorithmSuite
  isExternal: true
  name: Basic128SecurityAlgorithmSuite
  nameWithType: Basic128SecurityAlgorithmSuite
  fullName: CoreWCF.Security.Basic128SecurityAlgorithmSuite
- uid: CoreWCF.Security.TripleDesSecurityAlgorithmSuite
  commentId: T:CoreWCF.Security.TripleDesSecurityAlgorithmSuite
  isExternal: true
  name: TripleDesSecurityAlgorithmSuite
  nameWithType: TripleDesSecurityAlgorithmSuite
  fullName: CoreWCF.Security.TripleDesSecurityAlgorithmSuite
- uid: CoreWCF.Security.SecurityContextKeyIdentifierClause
  commentId: T:CoreWCF.Security.SecurityContextKeyIdentifierClause
  isExternal: true
  name: SecurityContextKeyIdentifierClause
  nameWithType: SecurityContextKeyIdentifierClause
  fullName: CoreWCF.Security.SecurityContextKeyIdentifierClause
- uid: CoreWCF.Security.SecurityCredentialsManager
  commentId: T:CoreWCF.Security.SecurityCredentialsManager
  parent: CoreWCF.Security
  isExternal: true
  name: SecurityCredentialsManager
  nameWithType: SecurityCredentialsManager
  fullName: CoreWCF.Security.SecurityCredentialsManager
- uid: CoreWCF.Security.SecurityKeyEntropyMode
  commentId: T:CoreWCF.Security.SecurityKeyEntropyMode
  parent: CoreWCF.Security
  isExternal: true
  name: SecurityKeyEntropyMode
  nameWithType: SecurityKeyEntropyMode
  fullName: CoreWCF.Security.SecurityKeyEntropyMode
- uid: CoreWCF.Security.SecurityMessageProperty
  commentId: T:CoreWCF.Security.SecurityMessageProperty
  parent: CoreWCF.Security
  isExternal: true
  name: SecurityMessageProperty
  nameWithType: SecurityMessageProperty
  fullName: CoreWCF.Security.SecurityMessageProperty
- uid: CoreWCF.Security.SecurityNegotiationException
  commentId: T:CoreWCF.Security.SecurityNegotiationException
  isExternal: true
  name: SecurityNegotiationException
  nameWithType: SecurityNegotiationException
  fullName: CoreWCF.Security.SecurityNegotiationException
- uid: CoreWCF.Security.SecurityPolicyVersion
  commentId: T:CoreWCF.Security.SecurityPolicyVersion
  parent: CoreWCF.Security
  isExternal: true
  name: SecurityPolicyVersion
  nameWithType: SecurityPolicyVersion
  fullName: CoreWCF.Security.SecurityPolicyVersion
- uid: CoreWCF.Security.SecurityProtocolFactory
  commentId: T:CoreWCF.Security.SecurityProtocolFactory
  isExternal: true
  name: SecurityProtocolFactory
  nameWithType: SecurityProtocolFactory
  fullName: CoreWCF.Security.SecurityProtocolFactory
- uid: CoreWCF.Security.SecurityStateEncoder
  commentId: T:CoreWCF.Security.SecurityStateEncoder
  parent: CoreWCF.Security
  isExternal: true
  name: SecurityStateEncoder
  nameWithType: SecurityStateEncoder
  fullName: CoreWCF.Security.SecurityStateEncoder
- uid: CoreWCF.Security.SecurityTokenAttachmentMode
  commentId: T:CoreWCF.Security.SecurityTokenAttachmentMode
  parent: CoreWCF.Security
  isExternal: true
  name: SecurityTokenAttachmentMode
  nameWithType: SecurityTokenAttachmentMode
  fullName: CoreWCF.Security.SecurityTokenAttachmentMode
- uid: CoreWCF.Security.SecurityTokenSpecification
  commentId: T:CoreWCF.Security.SecurityTokenSpecification
  parent: CoreWCF.Security
  isExternal: true
  name: SecurityTokenSpecification
  nameWithType: SecurityTokenSpecification
  fullName: CoreWCF.Security.SecurityTokenSpecification
- uid: CoreWCF.Security.SecurityVersion
  commentId: T:CoreWCF.Security.SecurityVersion
  parent: CoreWCF.Security
  isExternal: true
  name: SecurityVersion
  nameWithType: SecurityVersion
  fullName: CoreWCF.Security.SecurityVersion
- uid: CoreWCF.Security.SspiSecurityTokenProvider
  commentId: T:CoreWCF.Security.SspiSecurityTokenProvider
  isExternal: true
  name: SspiSecurityTokenProvider
  nameWithType: SspiSecurityTokenProvider
  fullName: CoreWCF.Security.SspiSecurityTokenProvider
- uid: CoreWCF.Security.SupportingTokenAuthenticatorSpecification
  commentId: T:CoreWCF.Security.SupportingTokenAuthenticatorSpecification
  isExternal: true
  name: SupportingTokenAuthenticatorSpecification
  nameWithType: SupportingTokenAuthenticatorSpecification
  fullName: CoreWCF.Security.SupportingTokenAuthenticatorSpecification
- uid: CoreWCF.Security.SupportingTokenProviderSpecification
  commentId: T:CoreWCF.Security.SupportingTokenProviderSpecification
  isExternal: true
  name: SupportingTokenProviderSpecification
  nameWithType: SupportingTokenProviderSpecification
  fullName: CoreWCF.Security.SupportingTokenProviderSpecification
- uid: CoreWCF.Security.SupportingTokenSpecification
  commentId: T:CoreWCF.Security.SupportingTokenSpecification
  isExternal: true
  name: SupportingTokenSpecification
  nameWithType: SupportingTokenSpecification
  fullName: CoreWCF.Security.SupportingTokenSpecification
- uid: CoreWCF.Security.TrustVersion
  commentId: T:CoreWCF.Security.TrustVersion
  parent: CoreWCF.Security
  isExternal: true
  name: TrustVersion
  nameWithType: TrustVersion
  fullName: CoreWCF.Security.TrustVersion
- uid: CoreWCF.Security.UserNamePasswordServiceCredential
  commentId: T:CoreWCF.Security.UserNamePasswordServiceCredential
  parent: CoreWCF.Security
  isExternal: true
  name: UserNamePasswordServiceCredential
  nameWithType: UserNamePasswordServiceCredential
  fullName: CoreWCF.Security.UserNamePasswordServiceCredential
- uid: CoreWCF.Security.UserNamePasswordValidationMode
  commentId: T:CoreWCF.Security.UserNamePasswordValidationMode
  parent: CoreWCF.Security
  isExternal: true
  name: UserNamePasswordValidationMode
  nameWithType: UserNamePasswordValidationMode
  fullName: CoreWCF.Security.UserNamePasswordValidationMode
- uid: CoreWCF.Security.WindowsServiceCredential
  commentId: T:CoreWCF.Security.WindowsServiceCredential
  parent: CoreWCF.Security
  isExternal: true
  name: WindowsServiceCredential
  nameWithType: WindowsServiceCredential
  fullName: CoreWCF.Security.WindowsServiceCredential
- uid: CoreWCF.Security.WSSecurityTokenSerializer
  commentId: T:CoreWCF.Security.WSSecurityTokenSerializer
  parent: CoreWCF.Security
  isExternal: true
  name: WSSecurityTokenSerializer
  nameWithType: WSSecurityTokenSerializer
  fullName: CoreWCF.Security.WSSecurityTokenSerializer
- uid: CoreWCF.Security.X509CertificateInitiatorServiceCredential
  commentId: T:CoreWCF.Security.X509CertificateInitiatorServiceCredential
  parent: CoreWCF.Security
  isExternal: true
  name: X509CertificateInitiatorServiceCredential
  nameWithType: X509CertificateInitiatorServiceCredential
  fullName: CoreWCF.Security.X509CertificateInitiatorServiceCredential
- uid: CoreWCF.Security.X509CertificateRecipientServiceCredential
  commentId: T:CoreWCF.Security.X509CertificateRecipientServiceCredential
  parent: CoreWCF.Security
  isExternal: true
  name: X509CertificateRecipientServiceCredential
  nameWithType: X509CertificateRecipientServiceCredential
  fullName: CoreWCF.Security.X509CertificateRecipientServiceCredential
- uid: CoreWCF.Security.X509CertificateValidationMode
  commentId: T:CoreWCF.Security.X509CertificateValidationMode
  parent: CoreWCF.Security
  isExternal: true
  name: X509CertificateValidationMode
  nameWithType: X509CertificateValidationMode
  fullName: CoreWCF.Security.X509CertificateValidationMode
- uid: CoreWCF.Security.X509ClientCertificateAuthentication
  commentId: T:CoreWCF.Security.X509ClientCertificateAuthentication
  parent: CoreWCF.Security
  isExternal: true
  name: X509ClientCertificateAuthentication
  nameWithType: X509ClientCertificateAuthentication
  fullName: CoreWCF.Security.X509ClientCertificateAuthentication
- uid: CoreWCF.Security
  commentId: N:CoreWCF.Security
  isExternal: true
  name: CoreWCF.Security
  nameWithType: CoreWCF.Security
  fullName: CoreWCF.Security
