### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceModelOptions
  commentId: T:CoreWCF.Configuration.ServiceModelOptions
  id: ServiceModelOptions
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceModelOptions.#ctor
  - CoreWCF.Configuration.ServiceModelOptions.ConfigureService(System.Type,System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder})
  langs:
  - csharp
  - vb
  name: ServiceModelOptions
  nameWithType: ServiceModelOptions
  fullName: CoreWCF.Configuration.ServiceModelOptions
  type: Class
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: 'public class ServiceModelOptions : Object'
    content.vb: >-
      Public Class ServiceModelOptions
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.ServiceModelOptions.ConfigureService(System.Type,System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder})
  commentId: M:CoreWCF.Configuration.ServiceModelOptions.ConfigureService(System.Type,System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder})
  id: ConfigureService(System.Type,System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder})
  parent: CoreWCF.Configuration.ServiceModelOptions
  langs:
  - csharp
  - vb
  name: ConfigureService(Type, Action<ServiceConfigurationBuilder>)
  nameWithType: ServiceModelOptions.ConfigureService(Type, Action<ServiceConfigurationBuilder>)
  fullName: CoreWCF.Configuration.ServiceModelOptions.ConfigureService(System.Type, System.Action<CoreWCF.Configuration.ServiceConfigurationBuilder>)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public void ConfigureService(Type serviceType, Action<ServiceConfigurationBuilder> configure)
    parameters:
    - id: serviceType
      type: System.Type
    - id: configure
      type: System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder}
    content.vb: Public Sub ConfigureService(serviceType As Type, configure As Action(Of ServiceConfigurationBuilder))
  overload: CoreWCF.Configuration.ServiceModelOptions.ConfigureService*
  nameWithType.vb: ServiceModelOptions.ConfigureService(Type, Action(Of ServiceConfigurationBuilder))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: CoreWCF.Configuration.ServiceModelOptions.ConfigureService(System.Type, System.Action(Of CoreWCF.Configuration.ServiceConfigurationBuilder))
  name.vb: ConfigureService(Type, Action(Of ServiceConfigurationBuilder))
- uid: CoreWCF.Configuration.ServiceModelOptions.#ctor
  commentId: M:CoreWCF.Configuration.ServiceModelOptions.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ServiceModelOptions
  langs:
  - csharp
  - vb
  name: ServiceModelOptions()
  nameWithType: ServiceModelOptions.ServiceModelOptions()
  fullName: CoreWCF.Configuration.ServiceModelOptions.ServiceModelOptions()
  type: Constructor
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceModelOptions()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.ServiceModelOptions.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelOptions.ConfigureService*
  commentId: Overload:CoreWCF.Configuration.ServiceModelOptions.ConfigureService
  isExternal: true
  name: ConfigureService
  nameWithType: ServiceModelOptions.ConfigureService
  fullName: CoreWCF.Configuration.ServiceModelOptions.ConfigureService
- uid: System.Type
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder}
  commentId: '!:System.Action{CoreWCF.Configuration.ServiceConfigurationBuilder}'
  definition: System.Action`1
  name: Action<ServiceConfigurationBuilder>
  nameWithType: Action<ServiceConfigurationBuilder>
  fullName: System.Action<CoreWCF.Configuration.ServiceConfigurationBuilder>
  nameWithType.vb: Action(Of ServiceConfigurationBuilder)
  fullName.vb: System.Action(Of CoreWCF.Configuration.ServiceConfigurationBuilder)
  name.vb: Action(Of ServiceConfigurationBuilder)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.Configuration.ServiceConfigurationBuilder
    name: ServiceConfigurationBuilder
    nameWithType: ServiceConfigurationBuilder
    fullName: CoreWCF.Configuration.ServiceConfigurationBuilder
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.Configuration.ServiceConfigurationBuilder
    name: ServiceConfigurationBuilder
    nameWithType: ServiceConfigurationBuilder
    fullName: CoreWCF.Configuration.ServiceConfigurationBuilder
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Action`1
  isExternal: true
  name: Action<>
  nameWithType: Action<>
  fullName: System.Action<>
  nameWithType.vb: Action(Of )
  fullName.vb: System.Action(Of )
  name.vb: Action(Of )
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceModelOptions.#ctor*
  commentId: Overload:CoreWCF.Configuration.ServiceModelOptions.#ctor
  isExternal: true
  name: ServiceModelOptions
  nameWithType: ServiceModelOptions.ServiceModelOptions
  fullName: CoreWCF.Configuration.ServiceModelOptions.ServiceModelOptions
