### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.NetHttpBindingCollectionElement
  commentId: T:CoreWCF.Configuration.NetHttpBindingCollectionElement
  id: NetHttpBindingCollectionElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.NetHttpBindingCollectionElement.#ctor
  langs:
  - csharp
  - vb
  name: NetHttpBindingCollectionElement
  nameWithType: NetHttpBindingCollectionElement
  fullName: CoreWCF.Configuration.NetHttpBindingCollectionElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a net http binding collection element.
  remarks: To be added.
  syntax:
    content: 'public class NetHttpBindingCollectionElement : StandardBindingCollectionElement<NetHttpBinding, NetHttpBindingElement>'
    content.vb: >-
      Public Class NetHttpBindingCollectionElement
          Inherits StandardBindingCollectionElement(Of NetHttpBinding, NetHttpBindingElement)
  inheritance:
  - System.Object
  - CoreWCF.Configuration.BindingCollectionElement
  - CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetHttpBinding,CoreWCF.Configuration.NetHttpBindingElement}
  inheritedMembers:
  - CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetHttpBinding,CoreWCF.Configuration.NetHttpBindingElement}.Bindings
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.NetHttpBindingCollectionElement.#ctor
  commentId: M:CoreWCF.Configuration.NetHttpBindingCollectionElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.NetHttpBindingCollectionElement
  langs:
  - csharp
  - vb
  name: NetHttpBindingCollectionElement()
  nameWithType: NetHttpBindingCollectionElement.NetHttpBindingCollectionElement()
  fullName: CoreWCF.Configuration.NetHttpBindingCollectionElement.NetHttpBindingCollectionElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public NetHttpBindingCollectionElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.NetHttpBindingCollectionElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.BindingCollectionElement
  commentId: T:CoreWCF.Configuration.BindingCollectionElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement
  fullName: CoreWCF.Configuration.BindingCollectionElement
- uid: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetHttpBinding,CoreWCF.Configuration.NetHttpBindingElement}
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetHttpBinding,CoreWCF.Configuration.NetHttpBindingElement}
  parent: CoreWCF.Configuration
  definition: CoreWCF.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<NetHttpBinding, NetHttpBindingElement>
  nameWithType: StandardBindingCollectionElement<NetHttpBinding, NetHttpBindingElement>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<CoreWCF.NetHttpBinding, CoreWCF.Configuration.NetHttpBindingElement>
  nameWithType.vb: StandardBindingCollectionElement(Of NetHttpBinding, NetHttpBindingElement)
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of CoreWCF.NetHttpBinding, CoreWCF.Configuration.NetHttpBindingElement)
  name.vb: StandardBindingCollectionElement(Of NetHttpBinding, NetHttpBindingElement)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.NetHttpBinding
    name: NetHttpBinding
    nameWithType: NetHttpBinding
    fullName: CoreWCF.NetHttpBinding
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: CoreWCF.Configuration.NetHttpBindingElement
    name: NetHttpBindingElement
    nameWithType: NetHttpBindingElement
    fullName: CoreWCF.Configuration.NetHttpBindingElement
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.NetHttpBinding
    name: NetHttpBinding
    nameWithType: NetHttpBinding
    fullName: CoreWCF.NetHttpBinding
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: CoreWCF.Configuration.NetHttpBindingElement
    name: NetHttpBindingElement
    nameWithType: NetHttpBindingElement
    fullName: CoreWCF.Configuration.NetHttpBindingElement
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetHttpBinding,CoreWCF.Configuration.NetHttpBindingElement}.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetHttpBinding,CoreWCF.Configuration.NetHttpBindingElement}.Bindings
  parent: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.NetHttpBinding,CoreWCF.Configuration.NetHttpBindingElement}
  definition: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  name: Bindings
  nameWithType: StandardBindingCollectionElement<NetHttpBinding, NetHttpBindingElement>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<CoreWCF.NetHttpBinding, CoreWCF.Configuration.NetHttpBindingElement>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of NetHttpBinding, NetHttpBindingElement).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of CoreWCF.NetHttpBinding, CoreWCF.Configuration.NetHttpBindingElement).Bindings
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement`2
  isExternal: true
  name: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  name.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TStandardBinding
    nameWithType: TStandardBinding
    fullName: TStandardBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TStandardBinding
    nameWithType: TStandardBinding
    fullName: TStandardBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  isExternal: true
  name: Bindings
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
- uid: CoreWCF.Configuration.NetHttpBindingCollectionElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.NetHttpBindingCollectionElement.#ctor
  isExternal: true
  name: NetHttpBindingCollectionElement
  nameWithType: NetHttpBindingCollectionElement.NetHttpBindingCollectionElement
  fullName: CoreWCF.Configuration.NetHttpBindingCollectionElement.NetHttpBindingCollectionElement
