### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.IServiceChannelDispatcher
  commentId: T:CoreWCF.Configuration.IServiceChannelDispatcher
  id: IServiceChannelDispatcher
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync(CoreWCF.Channels.Message)
  - CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync(CoreWCF.Channels.RequestContext)
  langs:
  - csharp
  - vb
  name: IServiceChannelDispatcher
  nameWithType: IServiceChannelDispatcher
  fullName: CoreWCF.Configuration.IServiceChannelDispatcher
  type: Interface
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: public interface IServiceChannelDispatcher
    content.vb: Public Interface IServiceChannelDispatcher
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync(CoreWCF.Channels.RequestContext)
  commentId: M:CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync(CoreWCF.Channels.RequestContext)
  id: DispatchAsync(CoreWCF.Channels.RequestContext)
  parent: CoreWCF.Configuration.IServiceChannelDispatcher
  langs:
  - csharp
  - vb
  name: DispatchAsync(RequestContext)
  nameWithType: IServiceChannelDispatcher.DispatchAsync(RequestContext)
  fullName: CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync(CoreWCF.Channels.RequestContext)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: Task DispatchAsync(RequestContext context)
    parameters:
    - id: context
      type: CoreWCF.Channels.RequestContext
    return:
      type: System.Threading.Tasks.Task
    content.vb: Function DispatchAsync(context As RequestContext) As Task
  overload: CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync*
- uid: CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync(CoreWCF.Channels.Message)
  commentId: M:CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync(CoreWCF.Channels.Message)
  id: DispatchAsync(CoreWCF.Channels.Message)
  parent: CoreWCF.Configuration.IServiceChannelDispatcher
  langs:
  - csharp
  - vb
  name: DispatchAsync(Message)
  nameWithType: IServiceChannelDispatcher.DispatchAsync(Message)
  fullName: CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync(CoreWCF.Channels.Message)
  type: Method
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Configuration
  syntax:
    content: Task DispatchAsync(Message message)
    parameters:
    - id: message
      type: CoreWCF.Channels.Message
    return:
      type: System.Threading.Tasks.Task
    content.vb: Function DispatchAsync(message As Message) As Task
  overload: CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync*
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync*
  commentId: Overload:CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync
  isExternal: true
  name: DispatchAsync
  nameWithType: IServiceChannelDispatcher.DispatchAsync
  fullName: CoreWCF.Configuration.IServiceChannelDispatcher.DispatchAsync
- uid: CoreWCF.Channels.RequestContext
  commentId: T:CoreWCF.Channels.RequestContext
  parent: CoreWCF.Channels
  isExternal: true
  name: RequestContext
  nameWithType: RequestContext
  fullName: CoreWCF.Channels.RequestContext
- uid: System.Threading.Tasks.Task
  isExternal: true
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: CoreWCF.Channels
  commentId: N:CoreWCF.Channels
  isExternal: true
  name: CoreWCF.Channels
  nameWithType: CoreWCF.Channels
  fullName: CoreWCF.Channels
- uid: CoreWCF.Channels.Message
  commentId: T:CoreWCF.Channels.Message
  parent: CoreWCF.Channels
  isExternal: true
  name: Message
  nameWithType: Message
  fullName: CoreWCF.Channels.Message
