### YamlMime:ManagedReference
items:
- uid: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute
  id: OpenApiResponseAttribute
  parent: CoreWCF.OpenApi.Attributes
  children:
  - CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.#ctor
  - CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.ContentTypes
  - CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Description
  - CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.StatusCode
  - CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Type
  langs:
  - csharp
  - vb
  name: OpenApiResponseAttribute
  nameWithType: OpenApiResponseAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute
  type: Class
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nAttribute to denote information about a response from an operation.\n"
  syntax:
    content: 'public sealed class OpenApiResponseAttribute : Attribute'
    content.vb: >-
      Public NotInheritable Class OpenApiResponseAttribute
          Inherits Attribute
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.#ctor
  commentId: M:CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.#ctor
  id: '#ctor'
  parent: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute
  langs:
  - csharp
  - vb
  name: OpenApiResponseAttribute()
  nameWithType: OpenApiResponseAttribute.OpenApiResponseAttribute()
  fullName: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.OpenApiResponseAttribute()
  type: Constructor
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  syntax:
    content: public OpenApiResponseAttribute()
    content.vb: Public Sub New
  overload: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.StatusCode
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.StatusCode
  id: StatusCode
  parent: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute
  langs:
  - csharp
  - vb
  name: StatusCode
  nameWithType: OpenApiResponseAttribute.StatusCode
  fullName: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.StatusCode
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nA status code that can be returned by an operation.\n"
  syntax:
    content: public HttpStatusCode StatusCode { get; set; }
    parameters: []
    return:
      type: System.Net.HttpStatusCode
    content.vb: Public Property StatusCode As HttpStatusCode
  overload: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.StatusCode*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Type
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Type
  id: Type
  parent: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: OpenApiResponseAttribute.Type
  fullName: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Type
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nA type that can be returned by an operation.\n"
  syntax:
    content: public Type Type { get; set; }
    parameters: []
    return:
      type: System.Type
    content.vb: Public Property Type As Type
  overload: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Type*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Description
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Description
  id: Description
  parent: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: OpenApiResponseAttribute.Description
  fullName: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Description
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nA description of why this type and status code would be returned by an operation.\n"
  syntax:
    content: public string Description { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Description As String
  overload: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Description*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.ContentTypes
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.ContentTypes
  id: ContentTypes
  parent: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute
  langs:
  - csharp
  - vb
  name: ContentTypes
  nameWithType: OpenApiResponseAttribute.ContentTypes
  fullName: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.ContentTypes
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nContent types this response can be returned as.\n"
  syntax:
    content: public string[] ContentTypes { get; set; }
    parameters: []
    return:
      type: System.String[]
    content.vb: Public Property ContentTypes As String()
  overload: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.ContentTypes*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.OpenApi.Attributes
  commentId: N:CoreWCF.OpenApi.Attributes
  isExternal: true
  name: CoreWCF.OpenApi.Attributes
  nameWithType: CoreWCF.OpenApi.Attributes
  fullName: CoreWCF.OpenApi.Attributes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.#ctor*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.#ctor
  isExternal: true
  name: OpenApiResponseAttribute
  nameWithType: OpenApiResponseAttribute.OpenApiResponseAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.OpenApiResponseAttribute
- uid: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.StatusCode*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.StatusCode
  isExternal: true
  name: StatusCode
  nameWithType: OpenApiResponseAttribute.StatusCode
  fullName: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.StatusCode
- uid: System.Net.HttpStatusCode
  isExternal: true
  name: HttpStatusCode
  nameWithType: HttpStatusCode
  fullName: System.Net.HttpStatusCode
- uid: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Type*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Type
  isExternal: true
  name: Type
  nameWithType: OpenApiResponseAttribute.Type
  fullName: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Type
- uid: System.Type
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Description*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Description
  isExternal: true
  name: Description
  nameWithType: OpenApiResponseAttribute.Description
  fullName: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.Description
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.ContentTypes*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.ContentTypes
  isExternal: true
  name: ContentTypes
  nameWithType: OpenApiResponseAttribute.ContentTypes
  fullName: CoreWCF.OpenApi.Attributes.OpenApiResponseAttribute.ContentTypes
- uid: System.String[]
  isExternal: true
  name: String[]
  nameWithType: String[]
  fullName: System.String[]
  nameWithType.vb: String()
  fullName.vb: System.String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
