### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceModelSectionGroup
  commentId: T:CoreWCF.Configuration.ServiceModelSectionGroup
  id: ServiceModelSectionGroup
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServiceModelSectionGroup.#ctor
  - CoreWCF.Configuration.ServiceModelSectionGroup.Bindings
  - CoreWCF.Configuration.ServiceModelSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  - CoreWCF.Configuration.ServiceModelSectionGroup.Services
  langs:
  - csharp
  - vb
  name: ServiceModelSectionGroup
  nameWithType: ServiceModelSectionGroup
  fullName: CoreWCF.Configuration.ServiceModelSectionGroup
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents the main configuration section for Windows Communication Foundation (WCF). This class cannot be inherited.
  remarks: "All WCF configuration elements are nested in the `system.serviceModel` element of the configuration file. WCF does not add elements to the configuration sections of other products.  \n\n"
  syntax:
    content: 'public sealed class ServiceModelSectionGroup : ConfigurationSectionGroup'
    content.vb: >-
      Public NotInheritable Class ServiceModelSectionGroup
          Inherits ConfigurationSectionGroup
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.ServiceModelSectionGroup.#ctor
  commentId: M:CoreWCF.Configuration.ServiceModelSectionGroup.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ServiceModelSectionGroup
  langs:
  - csharp
  - vb
  name: ServiceModelSectionGroup()
  nameWithType: ServiceModelSectionGroup.ServiceModelSectionGroup()
  fullName: CoreWCF.Configuration.ServiceModelSectionGroup.ServiceModelSectionGroup()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceModelSectionGroup()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.ServiceModelSectionGroup.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServiceModelSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  commentId: M:CoreWCF.Configuration.ServiceModelSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  id: GetSectionGroup(System.Configuration.Configuration)
  parent: CoreWCF.Configuration.ServiceModelSectionGroup
  langs:
  - csharp
  - vb
  name: GetSectionGroup(Configuration)
  nameWithType: ServiceModelSectionGroup.GetSectionGroup(Configuration)
  fullName: CoreWCF.Configuration.ServiceModelSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public static ServiceModelSectionGroup GetSectionGroup(Configuration config)
    parameters:
    - id: config
      type: System.Configuration.Configuration
    return:
      type: CoreWCF.Configuration.ServiceModelSectionGroup
    content.vb: Public Shared Function GetSectionGroup(config As Configuration) As ServiceModelSectionGroup
  overload: CoreWCF.Configuration.ServiceModelSectionGroup.GetSectionGroup*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: CoreWCF.Configuration.ServiceModelSectionGroup.Bindings
  commentId: P:CoreWCF.Configuration.ServiceModelSectionGroup.Bindings
  id: Bindings
  parent: CoreWCF.Configuration.ServiceModelSectionGroup
  langs:
  - csharp
  - vb
  name: Bindings
  nameWithType: ServiceModelSectionGroup.Bindings
  fullName: CoreWCF.Configuration.ServiceModelSectionGroup.Bindings
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public BindingsSection Bindings { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.BindingsSection
    content.vb: Public ReadOnly Property Bindings As BindingsSection
  overload: CoreWCF.Configuration.ServiceModelSectionGroup.Bindings*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: CoreWCF.Configuration.ServiceModelSectionGroup.Services
  commentId: P:CoreWCF.Configuration.ServiceModelSectionGroup.Services
  id: Services
  parent: CoreWCF.Configuration.ServiceModelSectionGroup
  langs:
  - csharp
  - vb
  name: Services
  nameWithType: ServiceModelSectionGroup.Services
  fullName: CoreWCF.Configuration.ServiceModelSectionGroup.Services
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServicesSection Services { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.ServicesSection
    content.vb: Public ReadOnly Property Services As ServicesSection
  overload: CoreWCF.Configuration.ServiceModelSectionGroup.Services*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelSectionGroup.#ctor*
  commentId: Overload:CoreWCF.Configuration.ServiceModelSectionGroup.#ctor
  isExternal: true
  name: ServiceModelSectionGroup
  nameWithType: ServiceModelSectionGroup.ServiceModelSectionGroup
  fullName: CoreWCF.Configuration.ServiceModelSectionGroup.ServiceModelSectionGroup
- uid: CoreWCF.Configuration.ServiceModelSectionGroup.GetSectionGroup*
  commentId: Overload:CoreWCF.Configuration.ServiceModelSectionGroup.GetSectionGroup
  isExternal: true
  name: GetSectionGroup
  nameWithType: ServiceModelSectionGroup.GetSectionGroup
  fullName: CoreWCF.Configuration.ServiceModelSectionGroup.GetSectionGroup
- uid: System.Configuration.Configuration
  commentId: '!:System.Configuration.Configuration'
  isExternal: true
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: CoreWCF.Configuration.ServiceModelSectionGroup
  commentId: T:CoreWCF.Configuration.ServiceModelSectionGroup
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceModelSectionGroup
  nameWithType: ServiceModelSectionGroup
  fullName: CoreWCF.Configuration.ServiceModelSectionGroup
- uid: CoreWCF.Configuration.ServiceModelSectionGroup.Bindings*
  commentId: Overload:CoreWCF.Configuration.ServiceModelSectionGroup.Bindings
  isExternal: true
  name: Bindings
  nameWithType: ServiceModelSectionGroup.Bindings
  fullName: CoreWCF.Configuration.ServiceModelSectionGroup.Bindings
- uid: CoreWCF.Configuration.BindingsSection
  commentId: T:CoreWCF.Configuration.BindingsSection
  parent: CoreWCF.Configuration
  isExternal: true
  name: BindingsSection
  nameWithType: BindingsSection
  fullName: CoreWCF.Configuration.BindingsSection
- uid: CoreWCF.Configuration.ServiceModelSectionGroup.Services*
  commentId: Overload:CoreWCF.Configuration.ServiceModelSectionGroup.Services
  isExternal: true
  name: Services
  nameWithType: ServiceModelSectionGroup.Services
  fullName: CoreWCF.Configuration.ServiceModelSectionGroup.Services
- uid: CoreWCF.Configuration.ServicesSection
  commentId: T:CoreWCF.Configuration.ServicesSection
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServicesSection
  nameWithType: ServicesSection
  fullName: CoreWCF.Configuration.ServicesSection
