### YamlMime:ManagedReference
items:
- uid: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute
  commentId: T:CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute
  id: OpenApiParameterAttribute
  parent: CoreWCF.OpenApi.Attributes
  children:
  - CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.#ctor
  - CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.ContentTypes
  - CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.Description
  langs:
  - csharp
  - vb
  name: OpenApiParameterAttribute
  nameWithType: OpenApiParameterAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute
  type: Class
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nAttribute to denote information about a parameter to an operation.\n"
  syntax:
    content: 'public sealed class OpenApiParameterAttribute : Attribute'
    content.vb: >-
      Public NotInheritable Class OpenApiParameterAttribute
          Inherits Attribute
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.#ctor
  commentId: M:CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.#ctor
  id: '#ctor'
  parent: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute
  langs:
  - csharp
  - vb
  name: OpenApiParameterAttribute()
  nameWithType: OpenApiParameterAttribute.OpenApiParameterAttribute()
  fullName: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.OpenApiParameterAttribute()
  type: Constructor
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  syntax:
    content: public OpenApiParameterAttribute()
    content.vb: Public Sub New
  overload: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.Description
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.Description
  id: Description
  parent: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: OpenApiParameterAttribute.Description
  fullName: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.Description
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nA description of the parameter.\n"
  syntax:
    content: public string Description { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Description As String
  overload: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.Description*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.ContentTypes
  commentId: P:CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.ContentTypes
  id: ContentTypes
  parent: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute
  langs:
  - csharp
  - vb
  name: ContentTypes
  nameWithType: OpenApiParameterAttribute.ContentTypes
  fullName: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.ContentTypes
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF.OpenApi.Attributes
  summary: "\nContent types the parameter can be provided as.\n"
  syntax:
    content: public string[] ContentTypes { get; set; }
    parameters: []
    return:
      type: System.String[]
    content.vb: Public Property ContentTypes As String()
  overload: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.ContentTypes*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.OpenApi.Attributes
  commentId: N:CoreWCF.OpenApi.Attributes
  isExternal: true
  name: CoreWCF.OpenApi.Attributes
  nameWithType: CoreWCF.OpenApi.Attributes
  fullName: CoreWCF.OpenApi.Attributes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.#ctor*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.#ctor
  isExternal: true
  name: OpenApiParameterAttribute
  nameWithType: OpenApiParameterAttribute.OpenApiParameterAttribute
  fullName: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.OpenApiParameterAttribute
- uid: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.Description*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.Description
  isExternal: true
  name: Description
  nameWithType: OpenApiParameterAttribute.Description
  fullName: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.Description
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.ContentTypes*
  commentId: Overload:CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.ContentTypes
  isExternal: true
  name: ContentTypes
  nameWithType: OpenApiParameterAttribute.ContentTypes
  fullName: CoreWCF.OpenApi.Attributes.OpenApiParameterAttribute.ContentTypes
- uid: System.String[]
  isExternal: true
  name: String[]
  nameWithType: String[]
  fullName: System.String[]
  nameWithType.vb: String()
  fullName.vb: System.String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
