### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.BasicHttpBindingCollectionElement
  commentId: T:CoreWCF.Configuration.BasicHttpBindingCollectionElement
  id: BasicHttpBindingCollectionElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.BasicHttpBindingCollectionElement.#ctor
  langs:
  - csharp
  - vb
  name: BasicHttpBindingCollectionElement
  nameWithType: BasicHttpBindingCollectionElement
  fullName: CoreWCF.Configuration.BasicHttpBindingCollectionElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a configuration section that holds a collection of [BasicHttpContextBindingElement](xref:CoreWCF.Configuration.BasicHttpBindingCollectionElement) instances.
  syntax:
    content: 'public class BasicHttpBindingCollectionElement : StandardBindingCollectionElement<BasicHttpBinding, BasicHttpBindingElement>'
    content.vb: >-
      Public Class BasicHttpBindingCollectionElement
          Inherits StandardBindingCollectionElement(Of BasicHttpBinding, BasicHttpBindingElement)
  inheritance:
  - System.Object
  - CoreWCF.Configuration.BindingCollectionElement
  - CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}
  inheritedMembers:
  - CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}.Bindings
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.BasicHttpBindingCollectionElement.#ctor
  commentId: M:CoreWCF.Configuration.BasicHttpBindingCollectionElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.BasicHttpBindingCollectionElement
  langs:
  - csharp
  - vb
  name: BasicHttpBindingCollectionElement()
  summary: Initializes a new instance of the [BasicHttpContextBindingCollectionElement](xref:CoreWCF.Configuration.BasicHttpBindingCollectionElement) class.
  nameWithType: BasicHttpBindingCollectionElement.BasicHttpBindingCollectionElement()
  fullName: CoreWCF.Configuration.BasicHttpBindingCollectionElement.BasicHttpBindingCollectionElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public BasicHttpBindingCollectionElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.BasicHttpBindingCollectionElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.BindingCollectionElement
  commentId: T:CoreWCF.Configuration.BindingCollectionElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement
  fullName: CoreWCF.Configuration.BindingCollectionElement
- uid: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}
  parent: CoreWCF.Configuration
  definition: CoreWCF.Configuration.StandardBindingCollectionElement`2
  name: StandardBindingCollectionElement<BasicHttpBinding, BasicHttpBindingElement>
  nameWithType: StandardBindingCollectionElement<BasicHttpBinding, BasicHttpBindingElement>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<CoreWCF.BasicHttpBinding, CoreWCF.Configuration.BasicHttpBindingElement>
  nameWithType.vb: StandardBindingCollectionElement(Of BasicHttpBinding, BasicHttpBindingElement)
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of CoreWCF.BasicHttpBinding, CoreWCF.Configuration.BasicHttpBindingElement)
  name.vb: StandardBindingCollectionElement(Of BasicHttpBinding, BasicHttpBindingElement)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: CoreWCF.BasicHttpBinding
    name: BasicHttpBinding
    nameWithType: BasicHttpBinding
    fullName: CoreWCF.BasicHttpBinding
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: CoreWCF.Configuration.BasicHttpBindingElement
    name: BasicHttpBindingElement
    nameWithType: BasicHttpBindingElement
    fullName: CoreWCF.Configuration.BasicHttpBindingElement
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: CoreWCF.BasicHttpBinding
    name: BasicHttpBinding
    nameWithType: BasicHttpBinding
    fullName: CoreWCF.BasicHttpBinding
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: CoreWCF.Configuration.BasicHttpBindingElement
    name: BasicHttpBindingElement
    nameWithType: BasicHttpBindingElement
    fullName: CoreWCF.Configuration.BasicHttpBindingElement
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}.Bindings
  parent: CoreWCF.Configuration.StandardBindingCollectionElement{CoreWCF.BasicHttpBinding,CoreWCF.Configuration.BasicHttpBindingElement}
  definition: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  name: Bindings
  nameWithType: StandardBindingCollectionElement<BasicHttpBinding, BasicHttpBindingElement>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<CoreWCF.BasicHttpBinding, CoreWCF.Configuration.BasicHttpBindingElement>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of BasicHttpBinding, BasicHttpBindingElement).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of CoreWCF.BasicHttpBinding, CoreWCF.Configuration.BasicHttpBindingElement).Bindings
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
  commentId: T:CoreWCF.Configuration.StandardBindingCollectionElement`2
  isExternal: true
  name: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  name.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration)
  spec.csharp:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TStandardBinding
    nameWithType: TStandardBinding
    fullName: TStandardBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.StandardBindingCollectionElement`2
    name: StandardBindingCollectionElement
    nameWithType: StandardBindingCollectionElement
    fullName: CoreWCF.Configuration.StandardBindingCollectionElement
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TStandardBinding
    nameWithType: TStandardBinding
    fullName: TStandardBinding
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  commentId: P:CoreWCF.Configuration.StandardBindingCollectionElement`2.Bindings
  isExternal: true
  name: Bindings
  nameWithType: StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  fullName: CoreWCF.Configuration.StandardBindingCollectionElement<TStandardBinding, TBindingConfiguration>.Bindings
  nameWithType.vb: StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
  fullName.vb: CoreWCF.Configuration.StandardBindingCollectionElement(Of TStandardBinding, TBindingConfiguration).Bindings
- uid: CoreWCF.Configuration.BasicHttpBindingCollectionElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.BasicHttpBindingCollectionElement.#ctor
  isExternal: true
  name: BasicHttpBindingCollectionElement
  nameWithType: BasicHttpBindingCollectionElement.BasicHttpBindingCollectionElement
  fullName: CoreWCF.Configuration.BasicHttpBindingCollectionElement.BasicHttpBindingCollectionElement
