### YamlMime:ManagedReference
items:
- uid: CoreWCF.Channels.ITransportFactorySettings
  commentId: T:CoreWCF.Channels.ITransportFactorySettings
  id: ITransportFactorySettings
  parent: CoreWCF.Channels
  children:
  - CoreWCF.Channels.ITransportFactorySettings.BufferManager
  - CoreWCF.Channels.ITransportFactorySettings.ManualAddressing
  - CoreWCF.Channels.ITransportFactorySettings.MaxReceivedMessageSize
  - CoreWCF.Channels.ITransportFactorySettings.MessageEncoderFactory
  - CoreWCF.Channels.ITransportFactorySettings.MessageVersion
  langs:
  - csharp
  - vb
  name: ITransportFactorySettings
  nameWithType: ITransportFactorySettings
  fullName: CoreWCF.Channels.ITransportFactorySettings
  type: Interface
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Channels
  syntax:
    content: 'public interface ITransportFactorySettings : IDefaultCommunicationTimeouts'
    content.vb: >-
      Public Interface ITransportFactorySettings
          Inherits IDefaultCommunicationTimeouts
  inheritedMembers:
  - CoreWCF.IDefaultCommunicationTimeouts.CloseTimeout
  - CoreWCF.IDefaultCommunicationTimeouts.OpenTimeout
  - CoreWCF.IDefaultCommunicationTimeouts.ReceiveTimeout
  - CoreWCF.IDefaultCommunicationTimeouts.SendTimeout
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: CoreWCF.Channels.ITransportFactorySettings.ManualAddressing
  commentId: P:CoreWCF.Channels.ITransportFactorySettings.ManualAddressing
  id: ManualAddressing
  parent: CoreWCF.Channels.ITransportFactorySettings
  langs:
  - csharp
  - vb
  name: ManualAddressing
  nameWithType: ITransportFactorySettings.ManualAddressing
  fullName: CoreWCF.Channels.ITransportFactorySettings.ManualAddressing
  type: Property
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Channels
  syntax:
    content: bool ManualAddressing { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property ManualAddressing As Boolean
  overload: CoreWCF.Channels.ITransportFactorySettings.ManualAddressing*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: CoreWCF.Channels.ITransportFactorySettings.BufferManager
  commentId: P:CoreWCF.Channels.ITransportFactorySettings.BufferManager
  id: BufferManager
  parent: CoreWCF.Channels.ITransportFactorySettings
  langs:
  - csharp
  - vb
  name: BufferManager
  nameWithType: ITransportFactorySettings.BufferManager
  fullName: CoreWCF.Channels.ITransportFactorySettings.BufferManager
  type: Property
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Channels
  syntax:
    content: BufferManager BufferManager { get; }
    parameters: []
    return:
      type: CoreWCF.Channels.BufferManager
    content.vb: ReadOnly Property BufferManager As BufferManager
  overload: CoreWCF.Channels.ITransportFactorySettings.BufferManager*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: CoreWCF.Channels.ITransportFactorySettings.MaxReceivedMessageSize
  commentId: P:CoreWCF.Channels.ITransportFactorySettings.MaxReceivedMessageSize
  id: MaxReceivedMessageSize
  parent: CoreWCF.Channels.ITransportFactorySettings
  langs:
  - csharp
  - vb
  name: MaxReceivedMessageSize
  nameWithType: ITransportFactorySettings.MaxReceivedMessageSize
  fullName: CoreWCF.Channels.ITransportFactorySettings.MaxReceivedMessageSize
  type: Property
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Channels
  syntax:
    content: long MaxReceivedMessageSize { get; }
    parameters: []
    return:
      type: System.Int64
    content.vb: ReadOnly Property MaxReceivedMessageSize As Long
  overload: CoreWCF.Channels.ITransportFactorySettings.MaxReceivedMessageSize*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: CoreWCF.Channels.ITransportFactorySettings.MessageEncoderFactory
  commentId: P:CoreWCF.Channels.ITransportFactorySettings.MessageEncoderFactory
  id: MessageEncoderFactory
  parent: CoreWCF.Channels.ITransportFactorySettings
  langs:
  - csharp
  - vb
  name: MessageEncoderFactory
  nameWithType: ITransportFactorySettings.MessageEncoderFactory
  fullName: CoreWCF.Channels.ITransportFactorySettings.MessageEncoderFactory
  type: Property
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Channels
  syntax:
    content: MessageEncoderFactory MessageEncoderFactory { get; }
    parameters: []
    return:
      type: CoreWCF.Channels.MessageEncoderFactory
    content.vb: ReadOnly Property MessageEncoderFactory As MessageEncoderFactory
  overload: CoreWCF.Channels.ITransportFactorySettings.MessageEncoderFactory*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: CoreWCF.Channels.ITransportFactorySettings.MessageVersion
  commentId: P:CoreWCF.Channels.ITransportFactorySettings.MessageVersion
  id: MessageVersion
  parent: CoreWCF.Channels.ITransportFactorySettings
  langs:
  - csharp
  - vb
  name: MessageVersion
  nameWithType: ITransportFactorySettings.MessageVersion
  fullName: CoreWCF.Channels.ITransportFactorySettings.MessageVersion
  type: Property
  source:
    path: CoreWCF.Primitives
    isExternal: true
  assemblies:
  - CoreWCF.Primitives
  namespace: CoreWCF.Channels
  syntax:
    content: MessageVersion MessageVersion { get; }
    parameters: []
    return:
      type: CoreWCF.Channels.MessageVersion
    content.vb: ReadOnly Property MessageVersion As MessageVersion
  overload: CoreWCF.Channels.ITransportFactorySettings.MessageVersion*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: CoreWCF.Channels
  commentId: N:CoreWCF.Channels
  isExternal: true
  name: CoreWCF.Channels
  nameWithType: CoreWCF.Channels
  fullName: CoreWCF.Channels
- uid: CoreWCF.IDefaultCommunicationTimeouts.CloseTimeout
  commentId: P:CoreWCF.IDefaultCommunicationTimeouts.CloseTimeout
  parent: CoreWCF.IDefaultCommunicationTimeouts
  isExternal: true
  name: CloseTimeout
  nameWithType: IDefaultCommunicationTimeouts.CloseTimeout
  fullName: CoreWCF.IDefaultCommunicationTimeouts.CloseTimeout
- uid: CoreWCF.IDefaultCommunicationTimeouts.OpenTimeout
  commentId: P:CoreWCF.IDefaultCommunicationTimeouts.OpenTimeout
  parent: CoreWCF.IDefaultCommunicationTimeouts
  isExternal: true
  name: OpenTimeout
  nameWithType: IDefaultCommunicationTimeouts.OpenTimeout
  fullName: CoreWCF.IDefaultCommunicationTimeouts.OpenTimeout
- uid: CoreWCF.IDefaultCommunicationTimeouts.ReceiveTimeout
  commentId: P:CoreWCF.IDefaultCommunicationTimeouts.ReceiveTimeout
  parent: CoreWCF.IDefaultCommunicationTimeouts
  isExternal: true
  name: ReceiveTimeout
  nameWithType: IDefaultCommunicationTimeouts.ReceiveTimeout
  fullName: CoreWCF.IDefaultCommunicationTimeouts.ReceiveTimeout
- uid: CoreWCF.IDefaultCommunicationTimeouts.SendTimeout
  commentId: P:CoreWCF.IDefaultCommunicationTimeouts.SendTimeout
  parent: CoreWCF.IDefaultCommunicationTimeouts
  isExternal: true
  name: SendTimeout
  nameWithType: IDefaultCommunicationTimeouts.SendTimeout
  fullName: CoreWCF.IDefaultCommunicationTimeouts.SendTimeout
- uid: CoreWCF.IDefaultCommunicationTimeouts
  commentId: T:CoreWCF.IDefaultCommunicationTimeouts
  parent: CoreWCF
  isExternal: true
  name: IDefaultCommunicationTimeouts
  nameWithType: IDefaultCommunicationTimeouts
  fullName: CoreWCF.IDefaultCommunicationTimeouts
- uid: CoreWCF
  commentId: N:CoreWCF
  isExternal: true
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: CoreWCF.Channels.ITransportFactorySettings.ManualAddressing*
  commentId: Overload:CoreWCF.Channels.ITransportFactorySettings.ManualAddressing
  isExternal: true
  name: ManualAddressing
  nameWithType: ITransportFactorySettings.ManualAddressing
  fullName: CoreWCF.Channels.ITransportFactorySettings.ManualAddressing
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Channels.ITransportFactorySettings.BufferManager*
  commentId: Overload:CoreWCF.Channels.ITransportFactorySettings.BufferManager
  isExternal: true
  name: BufferManager
  nameWithType: ITransportFactorySettings.BufferManager
  fullName: CoreWCF.Channels.ITransportFactorySettings.BufferManager
- uid: CoreWCF.Channels.BufferManager
  commentId: T:CoreWCF.Channels.BufferManager
  parent: CoreWCF.Channels
  isExternal: true
  name: BufferManager
  nameWithType: BufferManager
  fullName: CoreWCF.Channels.BufferManager
- uid: CoreWCF.Channels.ITransportFactorySettings.MaxReceivedMessageSize*
  commentId: Overload:CoreWCF.Channels.ITransportFactorySettings.MaxReceivedMessageSize
  isExternal: true
  name: MaxReceivedMessageSize
  nameWithType: ITransportFactorySettings.MaxReceivedMessageSize
  fullName: CoreWCF.Channels.ITransportFactorySettings.MaxReceivedMessageSize
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: CoreWCF.Channels.ITransportFactorySettings.MessageEncoderFactory*
  commentId: Overload:CoreWCF.Channels.ITransportFactorySettings.MessageEncoderFactory
  isExternal: true
  name: MessageEncoderFactory
  nameWithType: ITransportFactorySettings.MessageEncoderFactory
  fullName: CoreWCF.Channels.ITransportFactorySettings.MessageEncoderFactory
- uid: CoreWCF.Channels.MessageEncoderFactory
  commentId: T:CoreWCF.Channels.MessageEncoderFactory
  parent: CoreWCF.Channels
  isExternal: true
  name: MessageEncoderFactory
  nameWithType: MessageEncoderFactory
  fullName: CoreWCF.Channels.MessageEncoderFactory
- uid: CoreWCF.Channels.ITransportFactorySettings.MessageVersion*
  commentId: Overload:CoreWCF.Channels.ITransportFactorySettings.MessageVersion
  isExternal: true
  name: MessageVersion
  nameWithType: ITransportFactorySettings.MessageVersion
  fullName: CoreWCF.Channels.ITransportFactorySettings.MessageVersion
- uid: CoreWCF.Channels.MessageVersion
  commentId: T:CoreWCF.Channels.MessageVersion
  parent: CoreWCF.Channels
  isExternal: true
  name: MessageVersion
  nameWithType: MessageVersion
  fullName: CoreWCF.Channels.MessageVersion
