### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.StandardBindingElementCollection`1
  commentId: T:CoreWCF.Configuration.StandardBindingElementCollection`1
  id: StandardBindingElementCollection`1
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.StandardBindingElementCollection`1.#ctor
  - CoreWCF.Configuration.StandardBindingElementCollection`1.GetElementKey(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  - vb
  name: StandardBindingElementCollection<TBindingConfiguration>
  nameWithType: StandardBindingElementCollection<TBindingConfiguration>
  fullName: CoreWCF.Configuration.StandardBindingElementCollection<TBindingConfiguration>
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents a collection of  objects. This class cannot be inherited.
  remarks: To be added.
  syntax:
    content: 'public class StandardBindingElementCollection<TBindingConfiguration> : ServiceModelEnhancedConfigurationElementCollection<TBindingConfiguration> where TBindingConfiguration : ConfigurationElement, IDefaultCommunicationTimeouts, IStandardBindingElement, new()'
    typeParameters:
    - id: TBindingConfiguration
    content.vb: >-
      Public Class StandardBindingElementCollection(Of TBindingConfiguration As {ConfigurationElement, IDefaultCommunicationTimeouts, IStandardBindingElement, New})
          Inherits ServiceModelEnhancedConfigurationElementCollection(Of TBindingConfiguration)
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElementCollection{{TBindingConfiguration}}
  - CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection{{TBindingConfiguration}}
  inheritedMembers:
  - CoreWCF.Configuration.ServiceModelConfigurationElementCollection{{TBindingConfiguration}}.CreateNewElement
  nameWithType.vb: StandardBindingElementCollection(Of TBindingConfiguration)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  fullName.vb: CoreWCF.Configuration.StandardBindingElementCollection(Of TBindingConfiguration)
  name.vb: StandardBindingElementCollection(Of TBindingConfiguration)
- uid: CoreWCF.Configuration.StandardBindingElementCollection`1.#ctor
  commentId: M:CoreWCF.Configuration.StandardBindingElementCollection`1.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.StandardBindingElementCollection`1
  langs:
  - csharp
  - vb
  name: StandardBindingElementCollection()
  nameWithType: StandardBindingElementCollection<TBindingConfiguration>.StandardBindingElementCollection()
  fullName: CoreWCF.Configuration.StandardBindingElementCollection<TBindingConfiguration>.StandardBindingElementCollection()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public StandardBindingElementCollection()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.StandardBindingElementCollection`1.#ctor*
  nameWithType.vb: StandardBindingElementCollection(Of TBindingConfiguration).StandardBindingElementCollection()
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: CoreWCF.Configuration.StandardBindingElementCollection(Of TBindingConfiguration).StandardBindingElementCollection()
- uid: CoreWCF.Configuration.StandardBindingElementCollection`1.GetElementKey(System.Configuration.ConfigurationElement)
  commentId: M:CoreWCF.Configuration.StandardBindingElementCollection`1.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: CoreWCF.Configuration.StandardBindingElementCollection`1
  langs:
  - csharp
  - vb
  name: GetElementKey(ConfigurationElement)
  nameWithType: StandardBindingElementCollection<TBindingConfiguration>.GetElementKey(ConfigurationElement)
  fullName: CoreWCF.Configuration.StandardBindingElementCollection<TBindingConfiguration>.GetElementKey(System.Configuration.ConfigurationElement)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override object GetElementKey(ConfigurationElement element)
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
    return:
      type: System.Object
    content.vb: Protected Overrides Function GetElementKey(element As ConfigurationElement) As Object
  overload: CoreWCF.Configuration.StandardBindingElementCollection`1.GetElementKey*
  nameWithType.vb: StandardBindingElementCollection(Of TBindingConfiguration).GetElementKey(ConfigurationElement)
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
  fullName.vb: CoreWCF.Configuration.StandardBindingElementCollection(Of TBindingConfiguration).GetElementKey(System.Configuration.ConfigurationElement)
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection{{TBindingConfiguration}}
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElementCollection{`0}
  parent: CoreWCF.Configuration
  definition: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  name: ServiceModelConfigurationElementCollection<TBindingConfiguration>
  nameWithType: ServiceModelConfigurationElementCollection<TBindingConfiguration>
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TBindingConfiguration>
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TBindingConfiguration)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TBindingConfiguration)
  name.vb: ServiceModelConfigurationElementCollection(Of TBindingConfiguration)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection{{TBindingConfiguration}}
  commentId: T:CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection{`0}
  parent: CoreWCF.Configuration
  definition: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
  name: ServiceModelEnhancedConfigurationElementCollection<TBindingConfiguration>
  nameWithType: ServiceModelEnhancedConfigurationElementCollection<TBindingConfiguration>
  fullName: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection<TBindingConfiguration>
  nameWithType.vb: ServiceModelEnhancedConfigurationElementCollection(Of TBindingConfiguration)
  fullName.vb: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection(Of TBindingConfiguration)
  name.vb: ServiceModelEnhancedConfigurationElementCollection(Of TBindingConfiguration)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
    name: ServiceModelEnhancedConfigurationElementCollection
    nameWithType: ServiceModelEnhancedConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
    name: ServiceModelEnhancedConfigurationElementCollection
    nameWithType: ServiceModelEnhancedConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TBindingConfiguration
    nameWithType: TBindingConfiguration
    fullName: TBindingConfiguration
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection{{TBindingConfiguration}}.CreateNewElement
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElementCollection{`0}.CreateNewElement
  parent: CoreWCF.Configuration.ServiceModelConfigurationElementCollection{{TBindingConfiguration}}
  definition: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  name: CreateNewElement()
  nameWithType: ServiceModelConfigurationElementCollection<TBindingConfiguration>.CreateNewElement()
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TBindingConfiguration>.CreateNewElement()
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TBindingConfiguration).CreateNewElement()
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TBindingConfiguration).CreateNewElement()
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection<TBindingConfiguration>.CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TBindingConfiguration>.CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection(Of TBindingConfiguration).CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TBindingConfiguration).CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  isExternal: true
  name: ServiceModelConfigurationElementCollection<TConfigurationElementType>
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  name.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TConfigurationElementType
    nameWithType: TConfigurationElementType
    fullName: TConfigurationElementType
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TConfigurationElementType
    nameWithType: TConfigurationElementType
    fullName: TConfigurationElementType
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
  commentId: T:CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
  isExternal: true
  name: ServiceModelEnhancedConfigurationElementCollection<TConfigurationElement>
  nameWithType: ServiceModelEnhancedConfigurationElementCollection<TConfigurationElement>
  fullName: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection<TConfigurationElement>
  nameWithType.vb: ServiceModelEnhancedConfigurationElementCollection(Of TConfigurationElement)
  fullName.vb: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection(Of TConfigurationElement)
  name.vb: ServiceModelEnhancedConfigurationElementCollection(Of TConfigurationElement)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
    name: ServiceModelEnhancedConfigurationElementCollection
    nameWithType: ServiceModelEnhancedConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TConfigurationElement
    nameWithType: TConfigurationElement
    fullName: TConfigurationElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
    name: ServiceModelEnhancedConfigurationElementCollection
    nameWithType: ServiceModelEnhancedConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TConfigurationElement
    nameWithType: TConfigurationElement
    fullName: TConfigurationElement
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  isExternal: true
  name: CreateNewElement()
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement()
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement()
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement()
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement()
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.StandardBindingElementCollection`1.#ctor*
  commentId: Overload:CoreWCF.Configuration.StandardBindingElementCollection`1.#ctor
  isExternal: true
  name: StandardBindingElementCollection
  nameWithType: StandardBindingElementCollection<TBindingConfiguration>.StandardBindingElementCollection
  fullName: CoreWCF.Configuration.StandardBindingElementCollection<TBindingConfiguration>.StandardBindingElementCollection
  nameWithType.vb: StandardBindingElementCollection(Of TBindingConfiguration).StandardBindingElementCollection
  fullName.vb: CoreWCF.Configuration.StandardBindingElementCollection(Of TBindingConfiguration).StandardBindingElementCollection
- uid: CoreWCF.Configuration.StandardBindingElementCollection`1.GetElementKey*
  commentId: Overload:CoreWCF.Configuration.StandardBindingElementCollection`1.GetElementKey
  isExternal: true
  name: GetElementKey
  nameWithType: StandardBindingElementCollection<TBindingConfiguration>.GetElementKey
  fullName: CoreWCF.Configuration.StandardBindingElementCollection<TBindingConfiguration>.GetElementKey
  nameWithType.vb: StandardBindingElementCollection(Of TBindingConfiguration).GetElementKey
  fullName.vb: CoreWCF.Configuration.StandardBindingElementCollection(Of TBindingConfiguration).GetElementKey
- uid: System.Configuration.ConfigurationElement
  isExternal: true
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
