### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
  commentId: T:CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
  id: ServiceModelEnhancedConfigurationElementCollection`1
  parent: CoreWCF.Configuration
  children: []
  langs:
  - csharp
  - vb
  name: ServiceModelEnhancedConfigurationElementCollection<TConfigurationElement>
  nameWithType: ServiceModelEnhancedConfigurationElementCollection<TConfigurationElement>
  fullName: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection<TConfigurationElement>
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: An abstract base class for a  looking for a merge semantic similar to an  that allows duplicates, but throws an exception when duplicates are found in the same configuration scope (e.g. same configuration file).
  remarks: To be added.
  syntax:
    content: 'public abstract class ServiceModelEnhancedConfigurationElementCollection<TConfigurationElement> : ServiceModelConfigurationElementCollection<TConfigurationElement> where TConfigurationElement : ConfigurationElement, new()'
    typeParameters:
    - id: TConfigurationElement
    content.vb: >-
      Public MustInherit Class ServiceModelEnhancedConfigurationElementCollection(Of TConfigurationElement As {ConfigurationElement, New})
          Inherits ServiceModelConfigurationElementCollection(Of TConfigurationElement)
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElementCollection{{TConfigurationElement}}
  derivedClasses:
  - CoreWCF.Configuration.StandardBindingElementCollection`1
  inheritedMembers:
  - CoreWCF.Configuration.ServiceModelConfigurationElementCollection{{TConfigurationElement}}.CreateNewElement
  nameWithType.vb: ServiceModelEnhancedConfigurationElementCollection(Of TConfigurationElement)
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
  fullName.vb: CoreWCF.Configuration.ServiceModelEnhancedConfigurationElementCollection(Of TConfigurationElement)
  name.vb: ServiceModelEnhancedConfigurationElementCollection(Of TConfigurationElement)
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection{{TConfigurationElement}}
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElementCollection{`0}
  parent: CoreWCF.Configuration
  definition: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  name: ServiceModelConfigurationElementCollection<TConfigurationElement>
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElement>
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElement>
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElement)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElement)
  name.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElement)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TConfigurationElement
    nameWithType: TConfigurationElement
    fullName: TConfigurationElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TConfigurationElement
    nameWithType: TConfigurationElement
    fullName: TConfigurationElement
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection{{TConfigurationElement}}.CreateNewElement
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElementCollection{`0}.CreateNewElement
  parent: CoreWCF.Configuration.ServiceModelConfigurationElementCollection{{TConfigurationElement}}
  definition: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  name: CreateNewElement()
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElement>.CreateNewElement()
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElement>.CreateNewElement()
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElement).CreateNewElement()
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElement).CreateNewElement()
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElement>.CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElement>.CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection(Of TConfigurationElement).CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElement).CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
  isExternal: true
  name: ServiceModelConfigurationElementCollection<TConfigurationElementType>
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  name.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TConfigurationElementType
    nameWithType: TConfigurationElementType
    fullName: TConfigurationElementType
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1
    name: ServiceModelConfigurationElementCollection
    nameWithType: ServiceModelConfigurationElementCollection
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TConfigurationElementType
    nameWithType: TConfigurationElementType
    fullName: TConfigurationElementType
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  isExternal: true
  name: CreateNewElement()
  nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement()
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement()
  nameWithType.vb: ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement()
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement()
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection<TConfigurationElementType>.CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
    name: CreateNewElement
    nameWithType: ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElementCollection(Of TConfigurationElementType).CreateNewElement
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
