### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.WSHttpSecurityElement
  commentId: T:CoreWCF.Configuration.WSHttpSecurityElement
  id: WSHttpSecurityElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.WSHttpSecurityElement.#ctor
  - CoreWCF.Configuration.WSHttpSecurityElement.Message
  - CoreWCF.Configuration.WSHttpSecurityElement.Mode
  - CoreWCF.Configuration.WSHttpSecurityElement.Transport
  langs:
  - csharp
  - vb
  name: WSHttpSecurityElement
  nameWithType: WSHttpSecurityElement
  fullName: CoreWCF.Configuration.WSHttpSecurityElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: An XML element that defines the security settings for a wsHttpBinding binding.
  remarks: To be added.
  syntax:
    content: 'public class WSHttpSecurityElement : ServiceModelConfigurationElement'
    content.vb: >-
      Public Class WSHttpSecurityElement
          Inherits ServiceModelConfigurationElement
  inheritance:
  - System.Object
  - CoreWCF.Configuration.ServiceModelConfigurationElement
  inheritedMembers:
  - CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.WSHttpSecurityElement.#ctor
  commentId: M:CoreWCF.Configuration.WSHttpSecurityElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.WSHttpSecurityElement
  langs:
  - csharp
  - vb
  name: WSHttpSecurityElement()
  nameWithType: WSHttpSecurityElement.WSHttpSecurityElement()
  fullName: CoreWCF.Configuration.WSHttpSecurityElement.WSHttpSecurityElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public WSHttpSecurityElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.WSHttpSecurityElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.WSHttpSecurityElement.Mode
  commentId: P:CoreWCF.Configuration.WSHttpSecurityElement.Mode
  id: Mode
  parent: CoreWCF.Configuration.WSHttpSecurityElement
  langs:
  - csharp
  - vb
  name: Mode
  nameWithType: WSHttpSecurityElement.Mode
  fullName: CoreWCF.Configuration.WSHttpSecurityElement.Mode
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public SecurityMode Mode { get; set; }
    parameters: []
    return:
      type: CoreWCF.SecurityMode
    content.vb: Public Property Mode As SecurityMode
  overload: CoreWCF.Configuration.WSHttpSecurityElement.Mode*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.WSHttpSecurityElement.Transport
  commentId: P:CoreWCF.Configuration.WSHttpSecurityElement.Transport
  id: Transport
  parent: CoreWCF.Configuration.WSHttpSecurityElement
  langs:
  - csharp
  - vb
  name: Transport
  nameWithType: WSHttpSecurityElement.Transport
  fullName: CoreWCF.Configuration.WSHttpSecurityElement.Transport
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public WSHttpTransportSecurityElement Transport { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.WSHttpTransportSecurityElement
    content.vb: Public ReadOnly Property Transport As WSHttpTransportSecurityElement
  overload: CoreWCF.Configuration.WSHttpSecurityElement.Transport*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: CoreWCF.Configuration.WSHttpSecurityElement.Message
  commentId: P:CoreWCF.Configuration.WSHttpSecurityElement.Message
  id: Message
  parent: CoreWCF.Configuration.WSHttpSecurityElement
  langs:
  - csharp
  - vb
  name: Message
  nameWithType: WSHttpSecurityElement.Message
  fullName: CoreWCF.Configuration.WSHttpSecurityElement.Message
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public NonDualMessageSecurityOverHttpElement Message { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement
    content.vb: Public ReadOnly Property Message As NonDualMessageSecurityOverHttpElement
  overload: CoreWCF.Configuration.WSHttpSecurityElement.Message*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement
  commentId: T:CoreWCF.Configuration.ServiceModelConfigurationElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,{T})
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: CoreWCF.Configuration.ServiceModelConfigurationElement
  definition: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  commentId: M:CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  isExternal: true
  name: SetPropertyValueIfNotDefaultValue<T>(String, T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(String, T)
  fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>(System.String, T)
  nameWithType.vb: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  fullName.vb: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)(System.String, T)
  name.vb: SetPropertyValueIfNotDefaultValue(Of T)(String, T)
  spec.csharp:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue<T>
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
    name: SetPropertyValueIfNotDefaultValue(Of T)
    nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    fullName: CoreWCF.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(Of T)
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: CoreWCF.Configuration.WSHttpSecurityElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.WSHttpSecurityElement.#ctor
  isExternal: true
  name: WSHttpSecurityElement
  nameWithType: WSHttpSecurityElement.WSHttpSecurityElement
  fullName: CoreWCF.Configuration.WSHttpSecurityElement.WSHttpSecurityElement
- uid: CoreWCF.Configuration.WSHttpSecurityElement.Mode*
  commentId: Overload:CoreWCF.Configuration.WSHttpSecurityElement.Mode
  isExternal: true
  name: Mode
  nameWithType: WSHttpSecurityElement.Mode
  fullName: CoreWCF.Configuration.WSHttpSecurityElement.Mode
- uid: CoreWCF.SecurityMode
  commentId: T:CoreWCF.SecurityMode
  parent: CoreWCF
  isExternal: true
  name: SecurityMode
  nameWithType: SecurityMode
  fullName: CoreWCF.SecurityMode
- uid: CoreWCF
  commentId: N:CoreWCF
  isExternal: true
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: CoreWCF.Configuration.WSHttpSecurityElement.Transport*
  commentId: Overload:CoreWCF.Configuration.WSHttpSecurityElement.Transport
  isExternal: true
  name: Transport
  nameWithType: WSHttpSecurityElement.Transport
  fullName: CoreWCF.Configuration.WSHttpSecurityElement.Transport
- uid: CoreWCF.Configuration.WSHttpTransportSecurityElement
  commentId: T:CoreWCF.Configuration.WSHttpTransportSecurityElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: WSHttpTransportSecurityElement
  nameWithType: WSHttpTransportSecurityElement
  fullName: CoreWCF.Configuration.WSHttpTransportSecurityElement
- uid: CoreWCF.Configuration.WSHttpSecurityElement.Message*
  commentId: Overload:CoreWCF.Configuration.WSHttpSecurityElement.Message
  isExternal: true
  name: Message
  nameWithType: WSHttpSecurityElement.Message
  fullName: CoreWCF.Configuration.WSHttpSecurityElement.Message
- uid: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement
  commentId: T:CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: NonDualMessageSecurityOverHttpElement
  nameWithType: NonDualMessageSecurityOverHttpElement
  fullName: CoreWCF.Configuration.NonDualMessageSecurityOverHttpElement
