### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.XmlElementElement
  commentId: T:CoreWCF.Configuration.XmlElementElement
  id: XmlElementElement
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.XmlElementElement.#ctor
  - CoreWCF.Configuration.XmlElementElement.#ctor(System.Xml.XmlElement)
  - CoreWCF.Configuration.XmlElementElement.Copy(CoreWCF.Configuration.XmlElementElement)
  - CoreWCF.Configuration.XmlElementElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - CoreWCF.Configuration.XmlElementElement.PostDeserialize
  - CoreWCF.Configuration.XmlElementElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - CoreWCF.Configuration.XmlElementElement.XmlElement
  langs:
  - csharp
  - vb
  name: XmlElementElement
  nameWithType: XmlElementElement
  fullName: CoreWCF.Configuration.XmlElementElement
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents the configuration settings for an XML element. This class cannot be inherited.
  remarks: To be added.
  syntax:
    content: 'public sealed class XmlElementElement : ConfigurationElement'
    content.vb: >-
      Public NotInheritable Class XmlElementElement
          Inherits ConfigurationElement
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.Configuration.XmlElementElement.#ctor
  commentId: M:CoreWCF.Configuration.XmlElementElement.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.XmlElementElement
  langs:
  - csharp
  - vb
  name: XmlElementElement()
  nameWithType: XmlElementElement.XmlElementElement()
  fullName: CoreWCF.Configuration.XmlElementElement.XmlElementElement()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public XmlElementElement()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.XmlElementElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.XmlElementElement.#ctor(System.Xml.XmlElement)
  commentId: M:CoreWCF.Configuration.XmlElementElement.#ctor(System.Xml.XmlElement)
  id: '#ctor(System.Xml.XmlElement)'
  parent: CoreWCF.Configuration.XmlElementElement
  langs:
  - csharp
  - vb
  name: XmlElementElement(XmlElement)
  nameWithType: XmlElementElement.XmlElementElement(XmlElement)
  fullName: CoreWCF.Configuration.XmlElementElement.XmlElementElement(System.Xml.XmlElement)
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public XmlElementElement(XmlElement element)
    parameters:
    - id: element
      type: System.Xml.XmlElement
    content.vb: Public Sub New(element As XmlElement)
  overload: CoreWCF.Configuration.XmlElementElement.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.XmlElementElement.Copy(CoreWCF.Configuration.XmlElementElement)
  commentId: M:CoreWCF.Configuration.XmlElementElement.Copy(CoreWCF.Configuration.XmlElementElement)
  id: Copy(CoreWCF.Configuration.XmlElementElement)
  parent: CoreWCF.Configuration.XmlElementElement
  langs:
  - csharp
  - vb
  name: Copy(XmlElementElement)
  nameWithType: XmlElementElement.Copy(XmlElementElement)
  fullName: CoreWCF.Configuration.XmlElementElement.Copy(CoreWCF.Configuration.XmlElementElement)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public void Copy(XmlElementElement source)
    parameters:
    - id: source
      type: CoreWCF.Configuration.XmlElementElement
    content.vb: Public Sub Copy(source As XmlElementElement)
  overload: CoreWCF.Configuration.XmlElementElement.Copy*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.XmlElementElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  commentId: M:CoreWCF.Configuration.XmlElementElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: CoreWCF.Configuration.XmlElementElement
  langs:
  - csharp
  - vb
  name: DeserializeElement(XmlReader, Boolean)
  nameWithType: XmlElementElement.DeserializeElement(XmlReader, Boolean)
  fullName: CoreWCF.Configuration.XmlElementElement.DeserializeElement(System.Xml.XmlReader, System.Boolean)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override void DeserializeElement(XmlReader reader, bool serializeCollectionKey)
    parameters:
    - id: reader
      type: System.Xml.XmlReader
    - id: serializeCollectionKey
      type: System.Boolean
    content.vb: Protected Overrides Sub DeserializeElement(reader As XmlReader, serializeCollectionKey As Boolean)
  overload: CoreWCF.Configuration.XmlElementElement.DeserializeElement*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: CoreWCF.Configuration.XmlElementElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  commentId: M:CoreWCF.Configuration.XmlElementElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  id: SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  parent: CoreWCF.Configuration.XmlElementElement
  langs:
  - csharp
  - vb
  name: SerializeToXmlElement(XmlWriter, String)
  nameWithType: XmlElementElement.SerializeToXmlElement(XmlWriter, String)
  fullName: CoreWCF.Configuration.XmlElementElement.SerializeToXmlElement(System.Xml.XmlWriter, System.String)
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override bool SerializeToXmlElement(XmlWriter writer, string elementName)
    parameters:
    - id: writer
      type: System.Xml.XmlWriter
    - id: elementName
      type: System.String
    return:
      type: System.Boolean
    content.vb: Protected Overrides Function SerializeToXmlElement(writer As XmlWriter, elementName As String) As Boolean
  overload: CoreWCF.Configuration.XmlElementElement.SerializeToXmlElement*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: CoreWCF.Configuration.XmlElementElement.PostDeserialize
  commentId: M:CoreWCF.Configuration.XmlElementElement.PostDeserialize
  id: PostDeserialize
  parent: CoreWCF.Configuration.XmlElementElement
  langs:
  - csharp
  - vb
  name: PostDeserialize()
  nameWithType: XmlElementElement.PostDeserialize()
  fullName: CoreWCF.Configuration.XmlElementElement.PostDeserialize()
  type: Method
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: protected override void PostDeserialize()
    content.vb: Protected Overrides Sub PostDeserialize
  overload: CoreWCF.Configuration.XmlElementElement.PostDeserialize*
  modifiers.csharp:
  - protected
  - override
  modifiers.vb:
  - Protected
  - Overrides
- uid: CoreWCF.Configuration.XmlElementElement.XmlElement
  commentId: P:CoreWCF.Configuration.XmlElementElement.XmlElement
  id: XmlElement
  parent: CoreWCF.Configuration.XmlElementElement
  langs:
  - csharp
  - vb
  name: XmlElement
  nameWithType: XmlElementElement.XmlElement
  fullName: CoreWCF.Configuration.XmlElementElement.XmlElement
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public XmlElement XmlElement { get; set; }
    parameters: []
    return:
      type: System.Xml.XmlElement
    content.vb: Public Property XmlElement As XmlElement
  overload: CoreWCF.Configuration.XmlElementElement.XmlElement*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.XmlElementElement.#ctor*
  commentId: Overload:CoreWCF.Configuration.XmlElementElement.#ctor
  isExternal: true
  name: XmlElementElement
  nameWithType: XmlElementElement.XmlElementElement
  fullName: CoreWCF.Configuration.XmlElementElement.XmlElementElement
- uid: System.Xml.XmlElement
  isExternal: true
  name: XmlElement
  nameWithType: XmlElement
  fullName: System.Xml.XmlElement
- uid: CoreWCF.Configuration.XmlElementElement.Copy*
  commentId: Overload:CoreWCF.Configuration.XmlElementElement.Copy
  isExternal: true
  name: Copy
  nameWithType: XmlElementElement.Copy
  fullName: CoreWCF.Configuration.XmlElementElement.Copy
- uid: CoreWCF.Configuration.XmlElementElement
  commentId: T:CoreWCF.Configuration.XmlElementElement
  parent: CoreWCF.Configuration
  isExternal: true
  name: XmlElementElement
  nameWithType: XmlElementElement
  fullName: CoreWCF.Configuration.XmlElementElement
- uid: CoreWCF.Configuration.XmlElementElement.DeserializeElement*
  commentId: Overload:CoreWCF.Configuration.XmlElementElement.DeserializeElement
  isExternal: true
  name: DeserializeElement
  nameWithType: XmlElementElement.DeserializeElement
  fullName: CoreWCF.Configuration.XmlElementElement.DeserializeElement
- uid: System.Xml.XmlReader
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: CoreWCF.Configuration.XmlElementElement.SerializeToXmlElement*
  commentId: Overload:CoreWCF.Configuration.XmlElementElement.SerializeToXmlElement
  isExternal: true
  name: SerializeToXmlElement
  nameWithType: XmlElementElement.SerializeToXmlElement
  fullName: CoreWCF.Configuration.XmlElementElement.SerializeToXmlElement
- uid: System.Xml.XmlWriter
  isExternal: true
  name: XmlWriter
  nameWithType: XmlWriter
  fullName: System.Xml.XmlWriter
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CoreWCF.Configuration.XmlElementElement.PostDeserialize*
  commentId: Overload:CoreWCF.Configuration.XmlElementElement.PostDeserialize
  isExternal: true
  name: PostDeserialize
  nameWithType: XmlElementElement.PostDeserialize
  fullName: CoreWCF.Configuration.XmlElementElement.PostDeserialize
- uid: CoreWCF.Configuration.XmlElementElement.XmlElement*
  commentId: Overload:CoreWCF.Configuration.XmlElementElement.XmlElement
  isExternal: true
  name: XmlElement
  nameWithType: XmlElementElement.XmlElement
  fullName: CoreWCF.Configuration.XmlElementElement.XmlElement
