### YamlMime:ManagedReference
items:
- uid: CoreWCF.WebHttpSecurity
  commentId: T:CoreWCF.WebHttpSecurity
  id: WebHttpSecurity
  parent: CoreWCF
  children:
  - CoreWCF.WebHttpSecurity.#ctor
  - CoreWCF.WebHttpSecurity.Mode
  - CoreWCF.WebHttpSecurity.Transport
  langs:
  - csharp
  - vb
  name: WebHttpSecurity
  nameWithType: WebHttpSecurity
  fullName: CoreWCF.WebHttpSecurity
  type: Class
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF
  summary: Specifies the types of security available to a service endpoint configured to receive HTTP requests.
  remarks: "&lt;xref:CoreWCF.WebHttpSecurity> provides the security requirements for an endpoint configured with a &lt;xref:CoreWCF.WebHttpBinding>.  \n\nIf the &lt;xref:CoreWCF.WebHttpSecurityMode.Transport> value is specified by the &lt;xref:CoreWCF.WebHttpBinding.%23ctor%28CoreWCF.WebHttpSecurityMode%29> method, then the settings provided by the &lt;xref:CoreWCF.WebHttpSecurity.Transport%2A> property become effective for the service endpoint. The value of &lt;xref:CoreWCF.WebHttpSecurityMode> can only be set in the &lt;xref:CoreWCF.WebHttpBinding> constructor that takes it as an explicit parameter and its value cannot be set again after the binding instance is created.  \n\n"
  syntax:
    content: 'public sealed class WebHttpSecurity : Object'
    content.vb: >-
      Public NotInheritable Class WebHttpSecurity
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CoreWCF.WebHttpSecurity.#ctor
  commentId: M:CoreWCF.WebHttpSecurity.#ctor
  id: '#ctor'
  parent: CoreWCF.WebHttpSecurity
  langs:
  - csharp
  - vb
  name: WebHttpSecurity()
  nameWithType: WebHttpSecurity.WebHttpSecurity()
  fullName: CoreWCF.WebHttpSecurity.WebHttpSecurity()
  type: Constructor
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF
  syntax:
    content: public WebHttpSecurity()
    content.vb: Public Sub New
  overload: CoreWCF.WebHttpSecurity.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.WebHttpSecurity.Mode
  commentId: P:CoreWCF.WebHttpSecurity.Mode
  id: Mode
  parent: CoreWCF.WebHttpSecurity
  langs:
  - csharp
  - vb
  name: Mode
  nameWithType: WebHttpSecurity.Mode
  fullName: CoreWCF.WebHttpSecurity.Mode
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF
  syntax:
    content: public WebHttpSecurityMode Mode { get; set; }
    parameters: []
    return:
      type: CoreWCF.WebHttpSecurityMode
    content.vb: Public Property Mode As WebHttpSecurityMode
  overload: CoreWCF.WebHttpSecurity.Mode*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CoreWCF.WebHttpSecurity.Transport
  commentId: P:CoreWCF.WebHttpSecurity.Transport
  id: Transport
  parent: CoreWCF.WebHttpSecurity
  langs:
  - csharp
  - vb
  name: Transport
  nameWithType: WebHttpSecurity.Transport
  fullName: CoreWCF.WebHttpSecurity.Transport
  type: Property
  source:
    path: CoreWCF.WebHttp
    isExternal: true
  assemblies:
  - CoreWCF.WebHttp
  namespace: CoreWCF
  syntax:
    content: public HttpTransportSecurity Transport { get; set; }
    parameters: []
    return:
      type: CoreWCF.HttpTransportSecurity
    content.vb: Public Property Transport As HttpTransportSecurity
  overload: CoreWCF.WebHttpSecurity.Transport*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CoreWCF
  commentId: N:CoreWCF
  isExternal: true
  name: CoreWCF
  nameWithType: CoreWCF
  fullName: CoreWCF
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.WebHttpSecurity.#ctor*
  commentId: Overload:CoreWCF.WebHttpSecurity.#ctor
  isExternal: true
  name: WebHttpSecurity
  nameWithType: WebHttpSecurity.WebHttpSecurity
  fullName: CoreWCF.WebHttpSecurity.WebHttpSecurity
- uid: CoreWCF.WebHttpSecurity.Mode*
  commentId: Overload:CoreWCF.WebHttpSecurity.Mode
  isExternal: true
  name: Mode
  nameWithType: WebHttpSecurity.Mode
  fullName: CoreWCF.WebHttpSecurity.Mode
- uid: CoreWCF.WebHttpSecurityMode
  commentId: T:CoreWCF.WebHttpSecurityMode
  parent: CoreWCF
  isExternal: true
  name: WebHttpSecurityMode
  nameWithType: WebHttpSecurityMode
  fullName: CoreWCF.WebHttpSecurityMode
- uid: CoreWCF.WebHttpSecurity.Transport*
  commentId: Overload:CoreWCF.WebHttpSecurity.Transport
  isExternal: true
  name: Transport
  nameWithType: WebHttpSecurity.Transport
  fullName: CoreWCF.WebHttpSecurity.Transport
- uid: CoreWCF.HttpTransportSecurity
  commentId: T:CoreWCF.HttpTransportSecurity
  parent: CoreWCF
  isExternal: true
  name: HttpTransportSecurity
  nameWithType: HttpTransportSecurity
  fullName: CoreWCF.HttpTransportSecurity
