### YamlMime:ManagedReference
items:
- uid: CoreWCF.Configuration.ServicesSection
  commentId: T:CoreWCF.Configuration.ServicesSection
  id: ServicesSection
  parent: CoreWCF.Configuration
  children:
  - CoreWCF.Configuration.ServicesSection.#ctor
  - CoreWCF.Configuration.ServicesSection.Services
  langs:
  - csharp
  - vb
  name: ServicesSection
  nameWithType: ServicesSection
  fullName: CoreWCF.Configuration.ServicesSection
  type: Class
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  summary: Represents the configuration section that contains services.
  remarks: "Services are defined in the services section of the configuration file. Each service has its own service configuration section.  \n\n"
  syntax:
    content: 'public class ServicesSection : ConfigurationSection'
    content.vb: >-
      Public Class ServicesSection
          Inherits ConfigurationSection
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CoreWCF.Configuration.ServicesSection.#ctor
  commentId: M:CoreWCF.Configuration.ServicesSection.#ctor
  id: '#ctor'
  parent: CoreWCF.Configuration.ServicesSection
  langs:
  - csharp
  - vb
  name: ServicesSection()
  nameWithType: ServicesSection.ServicesSection()
  fullName: CoreWCF.Configuration.ServicesSection.ServicesSection()
  type: Constructor
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServicesSection()
    content.vb: Public Sub New
  overload: CoreWCF.Configuration.ServicesSection.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CoreWCF.Configuration.ServicesSection.Services
  commentId: P:CoreWCF.Configuration.ServicesSection.Services
  id: Services
  parent: CoreWCF.Configuration.ServicesSection
  langs:
  - csharp
  - vb
  name: Services
  nameWithType: ServicesSection.Services
  fullName: CoreWCF.Configuration.ServicesSection.Services
  type: Property
  source:
    path: CoreWCF.ConfigurationManager
    isExternal: true
  assemblies:
  - CoreWCF.ConfigurationManager
  namespace: CoreWCF.Configuration
  syntax:
    content: public ServiceElementCollection Services { get; }
    parameters: []
    return:
      type: CoreWCF.Configuration.ServiceElementCollection
    content.vb: Public ReadOnly Property Services As ServiceElementCollection
  overload: CoreWCF.Configuration.ServicesSection.Services*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: CoreWCF.Configuration
  commentId: N:CoreWCF.Configuration
  isExternal: true
  name: CoreWCF.Configuration
  nameWithType: CoreWCF.Configuration
  fullName: CoreWCF.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CoreWCF.Configuration.ServicesSection.#ctor*
  commentId: Overload:CoreWCF.Configuration.ServicesSection.#ctor
  isExternal: true
  name: ServicesSection
  nameWithType: ServicesSection.ServicesSection
  fullName: CoreWCF.Configuration.ServicesSection.ServicesSection
- uid: CoreWCF.Configuration.ServicesSection.Services*
  commentId: Overload:CoreWCF.Configuration.ServicesSection.Services
  isExternal: true
  name: Services
  nameWithType: ServicesSection.Services
  fullName: CoreWCF.Configuration.ServicesSection.Services
- uid: CoreWCF.Configuration.ServiceElementCollection
  commentId: T:CoreWCF.Configuration.ServiceElementCollection
  parent: CoreWCF.Configuration
  isExternal: true
  name: ServiceElementCollection
  nameWithType: ServiceElementCollection
  fullName: CoreWCF.Configuration.ServiceElementCollection
